uc-cdis/cloud-automation

- .gitignore
- README.md
- pack_and_terraform.bash
- setup_kube.bash
- tf_files/configs/kube-up.sh
- tf_files/variables.template
docs(readme): Made Google steps more clear
feat(script): Script to make process more auto
Resolves #41
> Further automation for Packer & Terraform

- apis_configs/gdcapi_settings.py
- apis_configs/userapi_settings.py
- destroy.bash
- pack_and_terraform.bash
- setup_kube.bash
- tf_files/cloud.tf
- tf_files/configs/cluster.yaml
- tf_files/configs/kube-services.sh
- tf_files/configs/render_creds.py
- tf_files/configs/revproxy-setup.sh
- tf_files/variables.template
> feat(autoscaler): Added autoscaler to yaml

- kube/services/gdcapi/gdcapi-deploy.yaml
- kube/services/portal/portal-deploy.yaml
- tf_files/cloud.tf
- tf_files/configs/00configmap.yaml
- tf_files/configs/kube-services.sh
- tf_files/configs/kube-up.sh
required for https://github.com/uc-cdis/data-portal/pull/91
r? @thanh-nguyen-dang
> feat(portal): get schema before running nginx

- pack_and_terraform.bash
- tf_files/cloud.tf
- tf_files/configs/cluster.yaml
- tf_files/variables.template
- tf_files/variables.tf
> Feat/region & instance type

- apis_configs/gdcapi_settings.py
- pack_and_terraform.bash
- tf_files/kube.tf
- tf_files/variables.template
- tf_files/variables.tf
added secret key to work with https://github.com/uc-cdis/gdcapi/pull/39
r? @rudyardrichter
> feat(gdcapi-secret): add secret key

- README.md
- apis_configs/gdcapi_settings.py
- destroy.bash
- pack_and_terraform.bash
- setup_kube.bash
- tf_files/cloud.tf
- tf_files/configs/creds.tpl
- tf_files/configs/kube-up.sh
- tf_files/kube.tf
- tf_files/terraform.tfvars
- tf_files/variables.template
- tf_files/variables.tf
> feat(vpc): add vpc endpoint for s3

- pack_and_terraform.bash
- Print errors raised by packer
- Exit on packer failure
- Factor repeated tasks into functions
- Clean up indentation
A few opinionated changes—the indentation was inconsistent in some places so I made it all 4 spaces.
r? @philloooo @zflamig
> fix(script): clean up pack_and_terraform.bash

- kube/README.md
- removed the _scale-up_ section and _release a new version_ section
- fixed some outdated part
r? @zflamig
> docs(readme): remove cdis specific instructions

- kube/services/portal/portal-deploy.yaml
- kube/services/revproxy/00nginx-config.yaml
* launch data-portal via dockerStart.sh
* revproxy nginx compress javascript and json responses
> chore(revproxy): tweak gzip nginx config

- tf_files/configs/kube-up.sh
fix(kube-up): better git commands
> chore(kube-aws): version to v0.9.8

- apis_configs/fence_settings.py
- apis_configs/peregrine_settings.py
- apis_configs/sheepdog_settings.py
update fence, peregrine and sheepdog config for oidc epic
> feat(oidc): update oauth config

- tf_files/configs/kube-setup-sheepdog.sh
* grant sheepdog all permissions on postgres sequences
* alter default priviledges on sheepdog and peregrine, so they automagically get the appropriate permissions on new tables and sequences:
https://www.postgresql.org/docs/current/static/sql-alterdefaultprivileges.html
Applied fixes to planxplanetv1, dcfqav1, bhcprodv2, edcprodv2 - will give fix to Alex@chop for gen3qa.kids-first after this PR is merged
> fix(kube-setup-sheepdog): work on sql grants

- .gitignore
- apis_configs/fence_settings.py
- kube/kubes.sh
- kube/services/fence/fence-deploy.yaml
- kube/services/fluentd/README.md
- kube/services/fluentd/fluentd.yaml
- kube/services/gdcapi/gdcapi-deploy.yaml
- kube/services/indexd/indexd-deploy.yaml
- kube/services/jenkins/jenkins-deploy.yaml
- kube/services/peregrine/peregrine-deploy.yaml
- kube/services/portal/portal-deploy.yaml
- kube/services/revproxy/revproxy-deploy.yaml
- kube/services/sheepdog/sheepdog-deploy.yaml
- kube/services/userapi/userapi-deploy.yaml
- tf_files/aws/cloud.tf
- tf_files/aws/data.tf
- tf_files/aws/kube.tf
- tf_files/aws/outputs.tf
- tf_files/configs/cluster.yaml
- tf_files/configs/kube-backup.sh
- tf_files/configs/kube-services-body.sh
- tf_files/configs/kube-setup-fluentd.sh
- tf_files/configs/kube-up-body.sh
- tf_files/configs/ssh_config.tpl
- tf_files/modules/cdis-aws-vpc/cloud.tf
- tf_files/modules/cdis-aws-vpc/data.tf
- tf_files/modules/cdis-aws-vpc/outputs.tf
- tf_files/modules/cdis-aws-vpc/security-groups.tf
WIP - @fauzigo is working on:
* wire up terraform VM's with with awslogs client and IAM roles and subnet routes to log into cloudwatch
* add filebeat and logstash to k8s cluster with logstash configured to funnel logs into cloudwatch logs
Once the logs are in cloudwatch, then we'll work on a separate PR to:
* route logs from commons account cloudwatch to SOC cloudwatch
* setup ELK stack in SOC to monitor logs from all commons
* setup cloudwatch alerts in SOC
* route cloudwatch logs to per-commons monitoring by client (ex - kidsfirst runs an ELK stack)
resolves #149
> Feat/logging - WIP

- tf_files/configs/kube-setup-fence.sh
> fix(kube-setup-fence): typo

- gen3/gen3setup.sh
- tf_files/modules/cdis-s3-bucket/cloud.tf
pre-creating the instance profile makes it easy to
attach the role to a VM in the AWS web console
> fix(s3bucket): need EC2 instance profs 4 IAM roles

- kube/services/jupyterhub/README.md
- kube/services/jupyterhub/jupyterhub-config.yaml
- kube/services/jupyterhub/jupyterhub-deployment.yaml
- kube/services/jupyterhub/jupyterhub-service.yaml
- kube/services/jupyterhub/jupyterhub-storage.yaml
- kube/services/revproxy/00nginx-config.yaml
- kube/services/revproxy/revproxy-deploy.yaml
- tf_files/configs/kube-setup-jupyterhub.sh
Adds the configs for the jupyterhub service
Adds the shell script to install jupyterhub service
Not automatically installed on new commons
Resolves #176
Resolves #175 
Resolves #174 
Resolves #173 
To actually enable jupyterhub we also need to switch the ELB from HTTPS to TCP right now.
> feat(jupyterhub): JupyterHub Service

- kube/services/revproxy/00nginx-config.yaml
previous config doesn't work, has duplicated scheme and port
> fix(revproxy): fix proxy pass syntax

- gen3/README.md
- gen3/bin/approve_vpcpeering_request.sh
Adds a bash script [approve_vpcpeering_request.sh] to accept the peering request and add the appropriate route.
> chore(vpcpeering): automating VPC peering request at csoc admin VM

- tf_files/configs/kube-setup-workvm.sh
> fix(bashrc): kube-setup-workvm bad HEREDOC

- Jenkinsfile
- gen3/bin/testsuite.sh
- gen3/bin/workon.sh
- pack_and_terraform_aws.bash
- tf_files/aws/cloud.tf
- tf_files/aws/kube.tf
- tf_files/aws/variables.template
- tf_files/aws/variables.tf
- tf_files/aws_user_vpc/root.tf
- tf_files/aws_user_vpc/variables.tf
- tf_files/modules/cdis-aws-vpc/cloud.tf
- tf_files/modules/cdis-aws-vpc/security-groups.tf
- tf_files/modules/cdis-aws-vpc/variables.tf
#261 
This will take care of the saturation for the network space 172.24.X.0/20  for VPC data commons
> Changed supplying 3rd vpc cidr octet to supplying both 2nd and 3rd octet

- kube/services/revproxy/apply_service
apply_service script incorrect use of default namespace
> fix(revproxy): bad namespace handling

- tf_files/aws/cloud.tf
- tf_files/aws/outputs.tf
- tf_files/aws/variables.tf
- tf_files/modules/cdis-aws-vpc/cloud.tf
- tf_files/modules/cdis-aws-vpc/outputs.tf
> Adding route to the default route table to talk to the csoc adminVM

- .gitmodules
- gen3/bin/workon.sh
for new commons - sheepdog and gdcapi
db password variables in config.tfvars should
be the same
> fix(workon.sh): db password consistency

- kube/services/jobs/usersync-cronjob.yaml
- kube/services/jobs/usersync-job.yaml
- kube/services/shiny/shiny-deploy.yaml
- tf_files/configs/00configmap.yaml
Needs `slack_webhook` in the global configmap now.
> feat(webhook): Add slack message to cronjob

- apis_configs/fence_settings.py
> fix(warning): remove warning google json

- gen3/bin/kube-setup-secrets.sh
Needs `[[ ]]` instead of `[ ]`
> refactor(fence-kid): fix conditional

- gen3/bin/kube-extract-config.sh
- gen3/bin/kube-setup-secrets.sh
- gen3/lib/testData/default/expectedFenceResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
- kube/services/fence/fence-deploy.yaml
- kube/services/jobs/google-create-bucket-job.yaml
- kube/services/jobs/google-manage-account-access-cronjob.yaml
- kube/services/jobs/google-manage-account-access-job.yaml
- kube/services/jobs/google-manage-keys-cronjob.yaml
- kube/services/jobs/google-manage-keys-job.yaml
- kube/services/jobs/useryaml-job.yaml
and tweak fence-deploy to untar
> fix(jwt-keys): bundle keys into tar ball

- gen3/bin/kube-setup-secrets.sh
only setup local user.yaml if necessary
resolves #359
> PXD-807 fix(kube-setup-secrets): avoid local user.yaml

- Docker/Jenkins/Dockerfile
- Jenkinsfile
- gen3/bin/g3k_testsuite.sh
- gen3/bin/testsuite.sh
- gen3/lib/utils.sh
- tf_files/gcp/commons/root.tf
- tf_files/gcp/commons/variables.tf
- tf_files/gcp/modules/commons_sql/root.tf
- tf_files/gcp/modules/commons_sql/variables.tf
- tf_files/gcp/modules/gke/variables.tf
to avoid dbs for different vpc's having
the same name
> fix(gcp/sql): add vpc-name to db-names

- gen3/lib/onprem.sh
> fix(onprem): onprem config file generation

- gen3/bin/kube-roll-all.sh
- gen3/lib/g3k.sh
wait for peregrine and sheepdog to come up
before rolling the portal
> fix(gen3 roll all): wait b4 portal roll

- flavors/squid_nlb/startup_configs/web_wildcard_whitelist
- flavors/squid_nlb/web_wildcard_whitelist
- flavors/squid_nlb_central/startup_configs/web_wildcard_whitelist
- flavors/squid_nlb_central/web_wildcard_whitelist
so we can install and update nodejs
> fix(squid-whitelist): add .nodesource.com

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-wait4-pods.sh
loop until all pods look like they are Running
> fix(gen3): add kube-wait4-pods

- Docker/Jenkins/Dockerfile
* add R to Jenkins for data simulation in QA Automation
> feat(Jenkins): add r and packages to Jenkins Dockerfile

- kube/services/pidgin/pidgin-deploy.yaml
Commented out the memory limit on pidgin.
> feat(pidgin): fix memory limit issue

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-arranger.sh
- gen3/bin/kube-setup-networkpolicy.sh
- kube/services/arranger/arranger-deploy.yaml
- kube/services/arranger/arranger-service.yaml
- kube/services/netpolicy/networkpolicy_arranger_templ.yaml
- kube/services/netpolicy/networkpolicy_revproxy_templ.yaml
- kube/services/revproxy/00nginx-config.yaml
* PXD-843
* PXD-847
* PXD-892
* PXD-893
* PXD-894
> chore(arranger): initial automation

- gen3/bin/approve_vpcpeering_request.sh
- gen3/lib/aws.sh
- gen3/lib/onprem.sh
- tf_files/aws/csoc_qualys_vm/outputs.tf
- tf_files/aws/csoc_qualys_vm/root.tf
- tf_files/aws/csoc_qualys_vm/variables.tf
- tf_files/aws/modules/qualys-vm/README.md
- tf_files/aws/modules/qualys-vm/cloud.tf
- tf_files/aws/modules/qualys-vm/outputs.tf
- tf_files/aws/modules/qualys-vm/variables.tf
> Automation for qualys scanner VM in csoc

- Docker/Jenkins/Dockerfile
- kube/services/jenkins/jenkins-deploy.yaml
* adding another container to run the selenium-standalone server
> feat(jenkins-deploy): add selenium container to pod

- gen3/README.md
- gen3/bin/devterm.sh
- gen3/bin/es.sh
- gen3/bin/g3k_testsuite.sh
- gen3/bin/kube-setup-arranger.sh
- gen3/bin/kube-setup-cronjobs.sh
- gen3/bin/kube-setup-fluentd.sh
- gen3/bin/kube-setup-secrets.sh
- gen3/gen3setup.sh
- gen3/lib/g3k.sh
- gen3/lib/g3k_manifest.sh
- gen3/lib/testData/bogusExpectedResult.yaml
- gen3/lib/testData/bogusInput.yaml
- kube/README.md
- kube/services/arranger/arranger-deploy.yaml
- kube/services/jenkins/apply_service.sh
- kube/services/revproxy/README.md
- kube/services/revproxy/apply_service
- tf_files/README.md
* pull arranger project-id from cdis-manifest
- extend gen3 templates to pull more values from cdis-manifest,
and support default values via '|-DEFAULT-|' syntax
* add `gen3 es` helpers:
- gen3 es indices
- gen3 es dump indexName
* generalize `gen3 devterm` to accept a `bash -c` command:
`gen3 devterm "nslookup fence-service"`
> PXD-1361 - Chore/more arranger

- tf_files/aws/modules/eks/cloud.tf
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
> update(eks workers): new version released by AWS

- gen3/bin/kube-setup-secrets.sh
> fix(configmaps): update-guard logic tweak

- gen3/lib/g3k_manifest.sh
- kube/services/jobs/gdcdb-create-job.yaml
- kube/services/jobs/gentestdata-job.yaml
- kube/services/jobs/graph-create-job.yaml
- kube/services/jobs/tube-job.yaml
- kube/services/spark/spark-deploy.yaml
- kube/services/tube/tube-deploy.yaml
roll all should not require global configmap
as precondition - it should set it up
> fix(roll-all): do not require global config map

- kube/services/revproxy/00nginx-config.yaml
> fix(cors): always set headers

- kube/services/revproxy/00nginx-config.yaml
Requires using quay.io/cdis/nginx:1.15.5-ctds for revproxy
> feat(CORS): Change nginx for CORS

- gen3/lib/g3k_manifest.sh
- gen3/lib/testData/default/manifest.json
simple sed templates can only deal with
simple types
> fix(g3k_manifest_filter): filter manifest by type

- gen3/bin/kube-setup-portal.sh
- gen3/lib/testData/default/expectedSheepdogResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
- kube/services/portal/portal-deploy.yaml
to support binary .png data in old k8s clusters
> fix(portal): switch configmap to secret

- gen3/bin/kube-setup-fluentd.sh
do not delete daemonset that does not exist
> fix(kube-setup-fluentd): check daemonset exists

- tf_files/aws/modules/common-logging/logging.tf
> chore(log rotation): from montly to weekly

- tf_files/aws/modules/vpn_nlb_central_csoc/cloud.tf
> Add more disk space to vpn

- gen3/bin/kube-setup-workvm.sh
- Usage of sudo in line 58 was wrong, it wouldn't create a new file due to sudo applied to `echo` function which wouldn't have any effect on the file or folder where the file needs to be created.
> fix(workvm): wrong sudo usage

- tf_files/aws/modules/fence-bot-user/iam.tf
- tf_files/aws/modules/upload-data-bucket/cloud-trail.tf
- Missing read access on the fence-bot user policy
> fix(permission): missing read access to the bucket

- kube/services/jobs/usersync-cronjob.yaml
- kube/services/jobs/usersync-job.yaml
- report emptyfile to slack for usersync
- check none useryamlpath, the empty string is not populated by gitops
> fix(usersync): check none useryaml

- kube/services/jobs/usersync-cronjob.yaml
- catch stderr and handle the dbgap empty file case better
> chore(usersync): catch stderr and to slack

- tf_files/aws/modules/commons-sns/README.md
- Typo in the README file for the SNS module
> fix(README): typo in the example

- gen3/bin/kube-roll-all.sh
- update usersync cronjob too for gitops sync when manifest changes
> fix(gen3-roll): roll usersync if exists

- gen3/bin/gitops.sh
- kube/services/peregrine/peregrine-deploy.yaml
peregrine takes forever to start
king for review.
> fix(peregrine): need a long initial health delay

- gen3/bin/kube-setup-portal.sh
- kube/services/portal/portal-deploy.yaml
- mount sponsor images into portal pod
> PXD-2248 chore(img): mount sponsor image directory

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-wait4-pods.sh
peregrine takes 10 minutes to get healthy
> fix(wait4-pods): wait up to 15 minutes

- gen3/bin/kube-wait4-pods.sh
> fix(wait4): wait4 90 not 900

- gen3/bin/kube-roll-all.sh
- fix `gen3 roll all` to use g3kubectl to get pods
> fix(roll): use g3kubectl

- tf_files/aws/commons/kube.tf
> feat(backup db)

- kube/services/arborist/arborist-deploy.yaml
- kube/services/jobs/gentestdata-job.yaml
> fix(gentestdata and arborist-deploy): yaml errors

- kube/services/jobs/gentestdata-job.yaml
- Python version of generate test data
> PXD-2439 Feat/data simulator

- files/integration_testing/test1_user.yaml
- files/integration_testing/test2_user.yaml
- Fix integration test files (name for qa project to be QA since it's case-sensitive)
> fix(test-useryamls): fix case for qa project to be QA (like other files)

- apis_configs/config_helper.py
- gen3/bin/kube-setup-fence.sh
- gen3/bin/kube-setup-secrets.sh
- kube/services/jobs/indexd-userdb-job.yaml
- kube/services/netpolicy/networkpolicy_arborist_templ.yaml
- tf_files/shared/modules/k8s_configs/creds.tpl
Add `indexd_password` field to the fence `creds.json`
> chore(creds): add indexd password to fence creds

- doc/job.md
- doc/roll.md
- gen3/bin/job.sh
- gen3/bin/roll.sh
- kube/services/jobs/etl-job.yaml
- kube/services/jobs/gentestdata-job.yaml
- kube/services/spark/spark-deploy.yaml
- kube/services/tube/tube-deploy.yaml
Add ETL job and some util bash that wait for job finish and wait for pod being brought up successfully
- Implemented some utils functions supporting to the ETL integration test
- Refactor etl-job
- Add wait4 job finish
> feat(etl-job): add etl job and scrip to run

- gen3/bin/kube-setup-spark.sh
- gen3/bin/kube-setup-tube.sh
add wait to kube-setup-spark and kube-setup-etl
- add wait to kube-setup-spark and kube-setup-etl
> feat(setup-wait): call kube-setup and wait

- Docker/Jenkins/Dockerfile
- gen3/bin/kube-setup-workvm.sh
- kube/services/jenkins/jenkins-deploy.yaml
> chore(Jenkins): add psql to docker

- gen3/bin/reset.sh
- fix db names for integration test reset
> fix(db-names): replace - with _ for db names in environments

- gen3/bin/reset.sh
integration tests may overwrite user.yaml, so
need to re-sync with S3
> fix(gen3 reset): run usersync - not useryaml

- gen3/bin/job.sh
> chore(failtstop): add check fail and stop the job

- kube/services/jobs/etl-job.yaml
- kube/services/tube/tube-deploy.yaml
- Get rid of obsolete config for ETL
> chore(etl): get rid of obsolete config

- tf_files/aws/modules/common-logging/logging.tf
- Files retention time in CSOC S3 for commons logs
> chore(retention for logs): in CSOC

- kube/services/jobs/etl-cronjob.yaml
New ETL cronjob for incoming new data
> Cronjob for hourly ETL run

- kube/services/jobs/etl-cronjob.yaml
- kube/services/jobs/etl-job.yaml
remove old etl results from HDFS
> clearing old etl results from hdfs from etl jobs

- kube/services/google-sa-validation/google-sa-validation-deploy.yaml
- kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
- kube/services/jobs/google-delete-expired-service-account-job.yaml
- kube/services/jobs/google-init-proxy-groups-cronjob.yaml
- kube/services/jobs/google-manage-keys-cronjob.yaml
- kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
- kube/services/jobs/google-verify-bucket-access-group-job.yaml
- fix google jobs/cronjobs (errors when applying)
> fix(jobs): fix google cronjob errors

- kube/services/indexd/indexd-deploy.yaml
> fix(resource): add resource limit

- gen3/bin/reset.sh
force user.yaml re-sync
fix Jenkins pipeline for DCF PRs
> fix(reset): reset fence user.yaml configmap

- files/scripts/jupyter_migration.sh
misplaced echo was crashing the script
> fix(bug): removed misplaced echo

- files/squid_whitelist/web_whitelist
> add(domain): hooks.slack.com/services/

- gen3/bin/gitops.sh
- kube/services/jobs/gitops-sync-cronjob.yaml
Add slack notifications to gitops sync cronjob.
add `--slack` flag to `gen3 gitops sync` command
> refactor/gitopssync PXP-2284

- tf_files/aws/modules/eks-nodepool/data.tf
- tf_files/aws/modules/eks-nodepool/templates.tf
- tf_files/aws/modules/eks/cloud.tf
- tf_files/aws/modules/eks/templates.tf
- New AMI used for worker nodes with latest version of kubernets. Official released by amazon according to: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
Also a simplified bootstrap script, less cumbersome.
> added(new AMI): ami-04358410d28eaab63 official AWS release

- gen3/bin/reset.sh
Grant SQL permissions to peregrine in `gen3 reset`
* grant SQL changes to peregrine in `gen3 reset`, since `kube-setup-secrets` does not do it in Jenkins
> fix(gen3 reset): peregrine SQL grants

- gen3/lib/testData/default/expectedSheepdogResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
- kube/services/peregrine/peregrine-canary-deploy.yaml
- kube/services/peregrine/peregrine-deploy.yaml
- kube/services/sheepdog/sheepdog-canary-deploy.yaml
- kube/services/sheepdog/sheepdog-deploy.yaml
- back to have a single container for peregrine pod
> feat(peregrine): drop sidecar

- kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
- Cluster-autoscaler upgrade to version 1.2.4
> chore(cluster-autoscaler update); bumped to version 1.2.4

- gen3/bin/kube-setup-autoscaler.sh
- If changes are added to any of the cluster-autoscaler deployments/DS... , you can force kube-setup-autoscaler to run over existing deployments/DS ...
> add(force flag): allow a forced apply

- doc/api.md
- gen3/bin/api.sh
- gen3/bin/job.sh
- gen3/bin/testsuite.sh
- gen3/lib/kube-setup-init.sh
- gen3/lib/utils.sh
- kube/services/jobs/usersync-job.yaml
- kube/services/revproxy/gen3.nginx.conf/arranger-service.conf
- kube/services/revproxy/gen3.nginx.conf/fence-service.conf
- kube/services/revproxy/gen3.nginx.conf/google-sa-validation-service.conf
- kube/services/revproxy/gen3.nginx.conf/indexd-service.conf
- kube/services/revproxy/gen3.nginx.conf/jupyterhub-service.conf
- kube/services/revproxy/gen3.nginx.conf/peregrine-service.conf
- kube/services/revproxy/gen3.nginx.conf/pidgin-service.conf
- kube/services/revproxy/gen3.nginx.conf/portal-service.conf
- kube/services/revproxy/gen3.nginx.conf/sheepdog-service.conf
- kube/services/revproxy/gen3.nginx.conf/shiny-service.conf
- kube/services/revproxy/nginx.conf
Small fixes
- re-enable json log format at revproxy, and add proxy_service field
- usersync job retries s3 download if necessary
- flesh out `gen3 api`
* `gen3 api curl ...`
* `gen3 api new-program ...`
* `gen3 api new-project ...`
- re-enable json log format at revproxy, and add proxy_service field
- usersync job retries s3 download if necessary
- flesh out `gen3 api`
* `gen3 api curl ...`
* `gen3 api new-program ...`
* `gen3 api new-project ...`
> Fix/stuff - logging, usersync, api helper

- kube/services/jobs/gentestdata-job.yaml
Add fence-create retry loop to gentestdata ...
> fix(gentestdata-job): add fence-create retries

- kube/services/jobs/etl-cronjob.yaml
- kube/services/jobs/etl-job.yaml
- kube/services/tube/tube-deploy.yaml
- fix OOMKilled bug for ETL job
> fix(etl): OOMKilled issue

- kube/services/revproxy/nginx.conf
Proper error page for workspaces
> Update for sad dogz

- kube/services/jupyterhub/jupyterhub-deploy.yaml
- kube/services/jupyterhub/jupyterhub-prepuller.yaml
- kube/services/jupyterhub/jupyterhub_config.py
- kube/services/jupyterhub/test-jupyterhub_config.py
Cleans up JupyterHub config to use new non-deprecated settings
Fixes auth refresh
> feat(jh): Updates for new versions, bug fixes

- kube/services/jobs/etl-cronjob.yaml
- kube/services/jobs/etl-job.yaml
- kube/services/spark/spark-deploy.yaml
- Increase limit of RAM for Spark to 3G
- Prod envs is running in 4G vm, it may not be able to bring up 3G pod
> feat(spark-3g): increase spark to use 3g

- gen3/bin/kube-setup-roles.sh
- kube/services/jenkins/clusterrolebinding-devops.yaml
- kube/services/jobs/healthcheck-cronjob.yaml
Give jenkins-service full cluster-admin privileges
make the gen3 healthcheck cronjob hourly
> fix(bindings): update clusterrolebindings and healthcheck

- flavors/squid_nlb_central/updatewhitelist.sh
Updating the destination folder 'updatewhitelist.sh' file
> chore(squid_nlb): fix the destination inthe update script

- files/squid_whitelist/web_whitelist
> add(k8s.gcr.io): to the whitelist

- files/squid_whitelist/web_whitelist
> add(gcr.io): to whitelist

- kube/services/jobs/gdcdb-create-job.yaml
try to get sheepdog to come up cleanly against after gen3 reset
> chore(gdcdb-create-job): init sheepdog redux

- gen3/bin/kube-setup-secrets.sh
- tf_files/aws/modules/squid_nlb_central_csoc/cloud.tf
First of a series of steps to increase automation of k8s secrets
Versioning applied to <vpc_name> directory
kube-setup-secrets:
- turns <vpc_name> directory into local git repo
- script exit with failure if either directory has unstaged or uncommitted files (force people to track secrets)
- creates a local backup directory of secrets for recovery if necessary
> Feat/secrets auto PXP-1078

- apis_configs/indexd_settings.py
- kube/services/indexd/indexd-deploy.yaml
- kube/services/netpolicy/networkpolicy_indexd_templ.yaml
Supports loading distributed indexd config from manifest
Indexd can egress to the world to support distributed resolution
> feat(indexd): Distributed Indexd config support

- gen3/bin/klock.sh
- gen3/bin/testsuite.sh
increase timeouts in klock testsuite
> fix(klock-tests): avoid some possible races

- kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
- kube/services/jobs/google-init-proxy-groups-cronjob.yaml
- kube/services/jobs/google-manage-account-access-cronjob.yaml
- kube/services/jobs/google-manage-keys-cronjob.yaml
- kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
- kube/services/jobs/usersync-cronjob.yaml
- This fixed the name resolution issue for pods running on the same worker as the kube-dns service. Forcing TCP over UDP in /etc/resolv.conf
> add(TCP traffic): for DNS

- files/scripts/updateAndRebootCron
- gen3/bin/kube-setup-workvm.sh
update and reboot the admin vm weekly
> chore(updateAndRebootCron): weekly admin vm reboot

- tf_files/aws/commons/kube.tf
> chore(fix db time):convert to UTC

- Docker/python-nginx/python2.7-alpine3.7/dockerrun.sh
general dockerrun.sh was missing the nginx call
> fix(pybase2-nginxfix): accidentally took out nginx call

- gen3/bin/kube-setup-revproxy.sh
- If your namespace is not default, then the revproxy config won't be added to point to prometheus/grafana
> add(conditional): checks

- kube/services/monitoring/grafana-values.yaml
- kube/services/monitoring/prometheus-values.yaml
- Persistence on grafana 
- Data lost when pod restarts
> fix(data persistance): grafana

- gen3/bin/kube-setup-wts.sh
minor fix that doesn't need to go to category below
> fix(wts): separate dbcreds setup

- kube/services/revproxy/gen3.nginx.conf/workspace-token-service.conf
- forward auth token to wts too
> fix(wts): add auth header

- Docker/python-nginx/python2.7-alpine3.7/uwsgi.conf
- updated uwsgi file for py2base to prepare for harakiri changes by fantix
> chore(update-uwsgi): updating uwsgi for peregrine changes later

- kube/services/jobs/etl-job.yaml
forced running etl
- Force running etl
> feat(etl-force): forced running etl

- flavors/nginx/es_revproxy.sh
- tf_files/aws/modules/utility-vm/cloud.tf
- New nginx configuration to proxy amazon ES
> add(new config); site-available/default

- kube/services/jobs/etl-job.yaml
- kube/services/tube/tube-deploy.yaml
> chore(bump up memory for etl)

- tf_files/aws/modules/commons-vpc-es/cloud.tf
- tf_files/aws/modules/commons-vpc-es/data.tf
- ElasticSeach clustering with multinode.
> Chore/es ha PXP-2554

- tf_files/aws/modules/commons-vpc-es/cloud.tf
- lifecycle for ignoring ES versions
> chore(lifecycle): for the module

- tf_files/aws/modules/commons-vpc-es/cloud.tf
> chore(logs): previous tests failed for this, but seems to be working now

- gen3/bin/kube-roll-jupyter.sh
- gen3/bin/roll.sh
- kube/services/jupyterhub/jupyterhub-deploy.yaml
- kube/services/jupyterhub/jupyterhub-prepuller.yaml
- kube/services/jupyterhub/jupyterhub_config.py
Allows for different containers to be enable in different commons via the manifest
- Configure JupyterHub profiles from the manifest
> feat(jupmanifest): Load jupyter profiles from manifest

- files/squid_whitelist/web_whitelist
> add(grafana.com): to squid whitelist

- gen3/bin/kube-setup-prometheus.sh
- kube/services/monitoring/grafana-values.yaml
- Not replacing the domain for grafana deployment accordingly. It does after this patch
> fix(minor bug): tied to right domain now

- Jenkinsfile
- gen3/bin/api.sh
- gen3/bin/job.sh
- gen3/test/apiTest.sh
- kube/services/revproxy/gen3.nginx.conf/arborist-service.conf
- kube/services/revproxy/gen3.nginx.conf/grafana.conf
- kube/services/revproxy/gen3.nginx.conf/jupyterhub-service.conf
- kube/services/revproxy/gen3.nginx.conf/prometheus-server.conf
- kube/services/revproxy/revproxy-deploy.yaml
generalize revproxy /gen3-authz sub-request for arborist authz,
and apply to prometheus, grafana, and jpyterhub
> chore(prometheus-authz): generalize revproxy authz

- tf_files/aws/commons/cloud.tf
- tf_files/aws/commons/variables.tf
- tf_files/aws/modules/alarms-lambda/lambda.tf
- tf_files/aws/modules/alarms-lambda/lambda_function.rb
- tf_files/aws/modules/alarms-lambda/variables.tf
- tf_files/aws/modules/commons-alarms/variables.tf
- tf_files/aws/modules/commons-vpc-es/cloud.tf
- tf_files/aws/modules/commons-vpc-es/variables.tf
- tf_files/aws/modules/elasticsearch-alarms/es-alarms.tf
- tf_files/aws/modules/elasticsearch-alarms/variables.tf
added secondary slack webhook variable to allow for clients and us to get notified when alarms go off.
> feat(rds alarms): added secondary slack webhook for alarms

- Jenkinsfile
- files/squid_whitelist/web_whitelist
> fix(whitelist): add registry.terraform.io

- gen3/bin/kube-setup-fenceshib.sh
- gen3/bin/kube-setup-networkpolicy.sh
- kube/services/fenceshib/fenceshib-canary-deploy.yaml
- kube/services/fenceshib/fenceshib-canary-service.yaml
- kube/services/fenceshib/fenceshib-deploy.yaml
- kube/services/fenceshib/fenceshib-service.yaml
- kube/services/netpolicy/networkpolicy_fenceshib_templ.yaml
- kube/services/revproxy/gen3.nginx.conf/fenceshib-service.conf
- kube/services/revproxy/nginx.conf
- Add fenceshib deployment for deploying fence using shibboleth IdPs for login
> feat(fenceshib): add fenceshib service

- kube/services/guppy/guppy-deploy.yaml
Some minor changes in guppy deployment config to support multiple indices
- Pass guppy config block from manifest
> chore(guppy): change guppy config

- gen3/bin/kube-roll-all.sh
- fix gen3-roll-all to include wts if specified in manifest
> fix(wts): add to roll all

- kube/services/revproxy/gen3.nginx.conf/arranger-service.conf
- Tweaks the revproxy to allow large queries through to Arranger.
> fix(arranger): Allow large queries

- tf_files/gcp-bwg/create-project/main.tf
- tf_files/gcp-bwg/create-project/myvariables.tfvars
- tf_files/gcp-bwg/create-project/outputs.tf
- tf_files/gcp-bwg/create-project/vars.tf
- tf_files/gcp-bwg/folders/main.tf
- tf_files/gcp-bwg/folders/myvariables.tfvars
- tf_files/gcp-bwg/folders/vars.tf
- tf_files/gcp-bwg/modules/folders/main.tf
- tf_files/gcp-bwg/modules/folders/vars.tf
- tf_files/gcp-bwg/modules/project/main.tf
- tf_files/gcp-bwg/modules/project/outputs.tf
- tf_files/gcp-bwg/modules/project/readme.md
- tf_files/gcp-bwg/modules/project/vars.tf
- tf_files/gcp-bwg/setup-sa.sh
- Implemented new GCP from Burwood Group. Uploaded a setup script to create a service account with appropriate permissions. Also uploaded a terraform script to create folders and new project.
none
none
Script new service account creation.
Terraform module to create folders.
Terraform module to create new project.
none
none
> Uploaded setup script, folders and project module.

- kube/services/netpolicy/networkpolicy_sower_templ.yaml
- kube/services/sower/serviceaccount.yaml
- kube/services/sower/sower-deploy.yaml
Sower was out of date with current state of cloud automation, this fixes that.
> feat(sower): Update Sower for 2019.

- Docker/python-nginx/python2.7-alpine3.7/uwsgi.conf
- return valid JSON specified in uwsgi.conf
> fix(timeout): return valid JSON

- gen3/bin/db.sh
- gen3/test/dbTest.sh
fix bug in db server selection, add test case
> fix(db setup): bug in server selection

- kube/services/jupyterhub/jupyterhub-deploy.yaml
> fix(jupyterhub): nb size optional

- gen3/bin/kube-setup-wts.sh
- kube/services/wts/wts-deploy.yaml
- if workspace-token-service find a client in fence but can't get the secret, remove previous client and create a new one
> chore(wts): don't exist script if fail

- gen3/bin/kube-setup-wts.sh
- fixed typo for trying to get existing oidc client for wts
> fix(wts): grep dbcreds

- gen3/bin/kube-setup-manifestservice.sh
- kube/services/wts/wts-deploy.yaml
> chore(wts): should use liveness

- kube/services/jobs/etl-cronjob.yaml
- kube/services/jobs/etl-job.yaml
- kube/services/tube/tube-deploy.yaml
> chore(tube and etl):bump up memory

- gen3/bin/kube-roll-all.sh
> fix(guppy): add guppy to gen3 roll all

- tf_files/aws/commons_vpc_es/root.tf
- tf_files/aws/commons_vpc_es/variables.tf
- tf_files/aws/modules/elasticsearch-alarms/es-alarms.tf
fixed slack webhook variables and alarm logic.
> fix(es alarms): added slack webhook variables and fixed alarm logic

- kube/services/revproxy/gen3.nginx.conf/manifestservice-service.conf
- remove request size limitation for manifestservice
> fix(manifest): do not restrict body size for manifest service

- flavors/eks/bootstrap-2.0.0.sh
- flavors/eks/bootstrap-2.1.0.sh
- flavors/eks/bootstrap-2.1.1.sh
- flavors/eks/bootstrap-3.0.0.sh
- flavors/eks/bootstrap-3.1.0.sh
- tf_files/aws/modules/eks-nodepool/templates.tf
- tf_files/aws/modules/eks-nodepool/variables.tf
- tf_files/aws/modules/eks/cloud.tf
Added EC2 and ECR endpoint to allow for cluster autoscaling without squid.
> feat(add-vpc-endpoint): added vpc endpoint for ec2 and ecr

- doc/awsrole.md
- gen3/bin/awsrole.sh
- gen3/bin/testsuite.sh
- gen3/lib/aws.sh
- gen3/test/awsroleTest.sh
- tf_files/aws/role/README.md
- tf_files/aws/role/cloud.tf
- tf_files/aws/role/variables.tf
- tf_files/aws/role_policy_attachment/README.md
- tf_files/aws/role_policy_attachment/cloud.tf
- tf_files/aws/role_policy_attachment/variables.tf
Wrappers for managing aws roles
-  adds `gen3 awsrole` commands for managing aws roles and their policies
Note: Considering merging these functions with the branch for awsuser (#781 )
> feat(awsrole): add gen3 commands for managing roles

- kube/services/jupyterhub/jupyterhub_config.py
- kube/services/wts/wts-deploy.yaml
- symlink fusemounted data to user home directory
> chore(data): symlink data dir

- kube/services/guppy/README.md
- add example config to guppy's README
> fix(guppy-readme): add config example for guppy

- doc/dcf.md
- gen3/bin/dcf.sh
Use aws profile for data refresh gen3 cmd
> feat(profile): use profile

- apis_configs/peregrine_settings.py
- apis_configs/sheepdog_settings.py
- gen3/bin/kube-setup-secrets.sh
- gen3/lib/testData/default/expectedFenceResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
- kube/services/fence/fence-deploy.yaml
fixes for issues with new netpolicy
> fix(netpolicy): should have tested more

- gen3/bin/kube-setup-networkpolicy.sh
- kube/services/fence/fence-canary-deploy.yaml
- kube/services/fenceshib/fenceshib-canary-deploy.yaml
- kube/services/fenceshib/fenceshib-deploy.yaml
> fix(netpolicy): disable jupyter namespace rules

- kube/services/jupyterhub/jupyterhub_config.py
> fix(symlink): no recursive link

- doc/gitops.md
- kube/services/wts/wts-deploy.yaml
> Fix/wts - internet access

- gen3/bin/kube-setup-autoscaler.sh
- gen3/bin/kube-setup-coredns.sh
- gen3/bin/kube-setup-kube-dns-autoscaler.sh
- kube/services/kube-dns-autoscaler/dns-horizontal-autoscaler.yaml
- CoreDNS to replace kube-dns, basically for when we upgrade to k8s 1.11
> chore(coredns): install and swicht from kube-dns

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-secrets.sh
> fix(misc): broken stuff

- doc/kube-setup-networkpolicy.md
- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-aws-es-proxy.sh
- gen3/bin/kube-setup-networkpolicy.sh
- kube/services/arborist/arborist-deploy-2.yaml
- kube/services/arborist/arborist-deploy.yaml
kube-setup-aws-esproxy will try to update the
network policy even if endpoint info is not avialable
> fix(kube-setup-es): update netpolicy in cron

- kube/services/ssjdispatcher/ssjdispatcher-deploy.yaml
Move the quay image config from the secret to the manifest
> feat(config): get job configs from global manifest

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-aws-es-proxy.sh
- gen3/bin/kube-setup-jupyterhub.sh
- gen3/bin/kube-setup-workvm.sh
- gen3/bin/roll.sh
- kube/services/netpolicy/gen3/services/gen3job_netpolicy.yaml
> fix(netpolicy): gen3job can talk to everybody

- doc/csoc-free-commons-steps.md
- CSOC free documentation improvements, thanks @vzpgb
> chore(doc): thanks to vzpgb

- apis_configs/indexd_settings.py
- gen3/bin/kube-setup-indexd.sh
- gen3/bin/kube-setup-secrets.sh
- Now Indexd could talk to Arborist
> add Arborist base URL in indexd settings

- doc/csoc-free-commons-steps.md
> add(eks_version): option might not be that obvious

- gen3/bin/gitops.sh
For gitops sync, check portal configuration for changes
> patch(gen3_gitops): add portal checks in sync

- gen3/bin/gitops.sh
- disable checking for diff in portal config
> fix(gitops): rollback check for portal diff

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-wts.sh
> fix(setup-wts): race condition after reset

- gen3/bin/db.sh
- Make sure ltree module is installed after reset
> fix(ltree): make sure ltree gets created

- gen3/bin/cluster-description-helper.sh
- gen3/bin/kube-setup-coredns.sh
- loop break for kube-setup-coredns
> fix(loop break): was using a diferent laguage loop break type

- tf_files/aws/modules/upload-data-bucket/s3.tf
> fix(typo): removed

- doc/csoc-free-commons-steps.md
- tf_files/aws/eks/variables.tf
- tf_files/aws/modules/eks/variables.tf
- Default EKS version is now 1.11
> chore(eks upgrade): welcome 1.11

- gen3/bin/kube-setup-arborist.sh
- setup db for arborist when deployment_version is 2, not empty
> fix(arborist): change db setup logic to reverse

- apis_configs/indexd_settings.py
- gen3/bin/kube-setup-secrets.sh
- kube/services/indexd/indexd-deploy.yaml
- Indexd deployment will contain arborist service if manifest entry specifies indexd should run with arborist
> feat(indexd): pull arborist config from manifest

- tf_files/aws/modules/data-bucket-queue/cloud.tf
Improvements
set sqs visibility timeout to 5 min
> chore(sqs visibility timeout):set to 5 min

- files/squid_whitelist/web_whitelist
- whitelist orcid and microsoft login domains for squid
> whitelist orcid and microsoft as identity providers

- kube/services/sftp/sftp-config.yaml
> feat(users): add user with email that exists in user.yaml

- tf_files/aws/csoc_common_logging/variables.tf
- tf_files/aws/modules/common-logging/lambda_function.py
- tf_files/aws/modules/common-logging/variables.tf
- Avoid calling a lambda sub-function unnecessarily
> chore(defaults): values change

- gen3/bin/reset.sh
reset should not delete the wts-g3auto secret
> fix(reset): stop breaking stuff

- gen3/bin/kube-setup-manifestservice.sh
- gen3/bin/kube-setup-wts.sh
- gen3/bin/reset.sh
Fix handling of wts secret by `gen3 reset`
> fix(reset): Jenkins complexity with wts

- apis_configs/peregrine_settings.py
- apis_configs/sheepdog_settings.py
- gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
- kube/services/arranger/arranger-deploy.yaml
- kube/services/guppy/guppy-deploy.yaml
- kube/services/peregrine/peregrine-canary-deploy.yaml
- kube/services/peregrine/peregrine-deploy.yaml
- kube/services/portal/portal-deploy.yaml
- kube/services/sheepdog/sheepdog-canary-deploy.yaml
- kube/services/sheepdog/sheepdog-deploy.yaml
Refs uc-cdis/data-portal#542
- Set env `FENCE_HOSTNAME` for Windmill
> feat(unity): support Unity Portal

- doc/csoc-free-commons-steps.md
> fix(documentation): cleanup process

- kube/services/manifestservice/manifestservice-deploy.yaml
> fix(manserv): add liveness probe

- kube/services/fenceshib/fenceshib-canary-deploy.yaml
- kube/services/fenceshib/fenceshib-canary-service.yaml
- kube/services/revproxy/helpers.js
- Fix the name & app selector in the fence shibboleth canary service config.
- Add `fenceshib` to the list of canary-able services in the cookie for dev canaries.
> fix(fenceshib): patches for fenceshib canary

- kube/services/portal/portal-deploy.yaml
Deployed to https://qa-brain.planx-pla.net/
See https://github.com/uc-cdis/data-portal/pull/546 for details
> feat: workspace timeout setting in manifest

- README.md
- doc/csoc-free-commons-steps.md
- Referencing CSOC free setup in the main README for easy access.
> chore(README): reference to CSOC free

- gen3/bin/kube-setup-secrets.sh
- Increment sheepdog & peregrine secret versions to support the [signpost deprecation](https://github.com/uc-cdis/cloud-automation/pull/887)
> fix(sheepdog-secret): add new version

- doc/csoc-free-commons-steps.md
- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-autoscaler.sh
- tf_files/aws/commons/variables.tf
- tf_files/aws/modules/vpc/variables.tf
- Autoscaling wasn't deploying on new commons due to a line in the code commented out
> fix(autoscaling): had the wrong line commented out

- gen3/bin/gitops.sh
- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-metrics.sh
- tf_files/aws/modules/admin-vm/cloud.tf
- tf_files/aws/modules/eks-nodepool/cloud.tf
- tf_files/aws/modules/eks/cloud.tf
setup k8s metrics server - prerequisite for horizontal auto scaling
> chore(kube-setup-metrics): initial

- kube/services/revproxy/gen3.nginx.conf/sower-service.conf
Make revproxy use Arborist for Sower
> PXD-3247: feat(arborist): use arborist for sower job

- kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
- cluster autoscaler version bump
> chore(version bump): 1.12.3

- gen3/bin/kube-roll-all.sh
- kube/services/storageclass/aws-storageclass.yaml
Fixes Hatchery. Tested Hatchery on dev which has a default storage class, while the production environments do not. For Google this will need to be a different class
- Add a default storage class
> feat(sc): Add default storage class

- tf_files/aws/account_management-logs/root.tf
- tf_files/aws/account_management-logs/variables.tf
- tf_files/aws/modules/account-management-logs/cloud.tf
- tf_files/aws/modules/account-management-logs/variables.tf
- for the logging/metrics module, the alarm_actions variables were not working in config.tfvars.
> fix(variables): variables in config.tfvars were not working

- kube/services/ambassador/ambassador-deploy.yaml
- Support using ambassador for hatchery in non default namespace
> fix(namespace): use specific namespace

- gen3/bin/gitops.sh
- gitops tfplan would now check for the branch it is on
> add(branch look up): for gitopt tfplan

- files/scripts/tfplan-cronjob.sh
> fix(export): for the vpc_name var

- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
aws_db_instances now are backed up in multiple AWS availability zones
> feat(db_instance): add multiple AZs to back up DBs PXP-2462

- doc/csoc-free-commons-steps.md
kubconfig instead of kubeconfig
> missing letter in unix command

- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
Added variables allow the specification of size, instance, backup window, maintenance window, engine, and retention period.
> Feat/commons rds replication PXP 3156

- tf_files/aws/commons/variables.tf
- rds instances would go HA if explicitly specified.
> chore(*_ha): default value set to false

- tf_files/aws/commons/variables.tf
- most cases this feature is true, which makes no sense making the default value to false.
> chore(auto_minor_version_upgrade): default value set to false

- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
…of bucket
Allows the specification of buckets in iam_policy_document
> refactor(iam-buckets): add vars to iam policy PXP-3541

- gen3/bin/dcf.sh
> chore(update gs bucket)

- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
- allow_major_version_upgrade is not hardcoded anymore
> chore(variables): change default hardcoded value

- doc/csoc-free-commons-steps.md
- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
> chore(documentation): updates and corrections

- kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
- kube/services/jobs/google-init-proxy-groups-cronjob.yaml
- kube/services/jobs/google-manage-account-access-cronjob.yaml
- kube/services/jobs/google-manage-keys-cronjob.yaml
- kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
google jobs not to run at the same time
> chore(google job schedule):not to run at the same time

- gen3/bin/healthcheck.sh
> fix(healthcheck): small tweaks to gen3 script

- doc/kube-setup-ambassador.md
- gen3/bin/kube-setup-ambassador.sh
- gen3/bin/kube-setup-prometheus.sh
- gen3/lib/g3k.sh
- kube/services/ambassador-gen3/README.md
- kube/services/ambassador-gen3/ambassador-gen3-deploy.yaml
- kube/services/indexd/indexd-service.yaml
- kube/services/monitoring/prometheus-values.yaml
- kube/services/netpolicy/base/metrics_netpolicy.yaml
- kube/services/statsd-exporter/README.md
- kube/services/statsd-exporter/statsd-exporter-deploy.yaml
- kube/services/statsd-exporter/statsd-exporter-service.yaml
* add statsd-exporter to ambassador-api-gateway deployment
* add prometheus job to scrape statsd-exporter
> chore(statsd): ambassador-gen3-prometheus config

- tf_files/aws/commons_vpc_es/root.tf
- tf_files/aws/commons_vpc_es/variables.tf
- tf_files/aws/modules/commons-vpc-es/README.md
- tf_files/aws/modules/commons-vpc-es/cloud.tf
- tf_files/aws/modules/commons-vpc-es/variables.tf
- more variables added to the ES module, less hardcoded values
> chore(variables): added

- gen3/bin/gitops.sh
- when multiple profiles are in `.aws/config` workon won't properly work.
> fix(bug): when multiple profiles in .aws/config

- files/squid_whitelist/web_whitelist
Add docker-auth.elastic.co to white list
> feat(docker-auth): add docker-auth.elastic.co

- kube/services/tube/tube-deploy.yaml
- Mount user.yaml to tube service pod
> feat(useryaml): mount user yaml

- kube/services/jobs/etl-cronjob.yaml
- kube/services/jobs/etl-job.yaml
- mount user.yaml to etl job pods
> feat(user_sync): mount user.yaml to job pods

- doc/gitops.md
- files/scripts/tfplan-cronjob.sh
- gen3/bin/gitops.sh
- gen3/lib/_zsh-completions.sh
- gen3/lib/bash-completions.sh
- tfapply on the VPC module (use carefully)
> add(tfapply): to vpc module

- files/scripts/module-update.sh
> chore(update script): to work with the module passed as argument

- kube/services/peregrine/peregrine-deploy.yaml
> chore(GRAPHQL_TIMEOUT)

- tf_files/aws/modules/account-management-metrics/filters.tf
- tf_files/aws/modules/account-management-metrics/metrics.tf
- Added alarms for new IAM users and activity outside of AWS region.
> feat(add-alarms): added alarms

- gen3/bin/job.sh
- gen3/bin/kube-roll-all.sh
- gen3/lib/g3k_manifest.sh
- gen3/lib/utils.sh
- gen3/test/utilsTest.sh
* manifest filter fix for handling `false` in manifests
* introduce `gen3_log_debug` - logs a message if GEN3_DEBUG is set true
> fix(jobrun): issue with false in manifests

- tf_files/aws/publicvm/root.tf
- tf_files/aws/publicvm/sample.tfvars
- tf_files/aws/publicvm/variables.tf
Append devops and Ops SSH keys to the ubuntu user for new VMs
> chore(ssh keys): append devops and ops team keys to new vms

- doc/logs.md
- gen3/bin/kube-dev-namespace.sh
small tweaks - not able to reproduce issue with secrets corruption in parent namespae
> fix(dev-namespace): tweaks - avoid parent secrets

- gen3/bin/gitops.sh
> feat(etl-gitops): added etl roll to gitops change

- ansible/playbooks/cloud-automation.yaml
- files/scripts/module-update.sh
- cloud-automation update playbook for ansible
> add(playbook): to update cloud-automation on a remote host

- tf_files/aws/modules/account-management-logs/event-alerts.tf
- tf_files/aws/modules/cloudwatch-events/outputs.tf
- tf_files/aws/modules/lambda-function/output.tf
- CloudWatch Events permissions to trigger lambda were missing.
> fix(permissions): for events to call the function

- apis_configs/peregrine_settings.py
- apis_configs/sheepdog_settings.py
- gen3/bin/kube-setup-secrets.sh
- gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
- kube/services/peregrine/peregrine-deploy.yaml
- kube/services/sheepdog/sheepdog-deploy.yaml
- Sheepdog and Peregrine can be deployed with a custom ARBORIST_URL
> Get ARBORIST_URL from manifest

- tf_files/aws/modules/eks/init_cluster.sh
- Calico bumped to version 1.5 https://docs.aws.amazon.com/eks/latest/userguide/calico.html
> chore(calico): bumped to version 1.5

- doc/db.md
- gen3/bin/db.sh
- gen3/test/dbTest.sh
```
gen3 db snapshot take server1
gen3 db snapshot list server1
gen3 db backup indexd | tee indexd.backup.sql
gen3 db restore indexd indexd.backup.sql
```
> chore(db): snapshot and backup and restore

- Docker/Jenkins/Dockerfile
- Update to Jenkins 2.200: [Multiple security vulnerabilities in Jenkins 2.196 and earlier, and LTS 2.176.3 and earlier](https://jenkins.io/security/advisory/2019-09-25/)
> chore(jenkins): update to latest (2.200) version of Jenkins

- tf_files/gcp-bwg/roots/csoc_setup/app_setup/main.tf
- tf_files/gcp-bwg/roots/csoc_setup/project_setup/main.tf
> fix(minor bugs): variables names mistyped and missing

- files/openvpn_management_scripts/vpn_users_report_generator.sh
- The VPN users report file location can now be passed to the script when running it.
> chore(report location): can be set when running the script

- files/scripts/qa-cronjob.sh
- gen3/bin/kube-setup-jupyterhub.sh
do not setup jupyterhub in qa cronjob
> fix(qa-cronjob): remove setup-jupyter

- files/scripts/qa-cronjob.sh
- gen3/bin/kube-dev-namespace.sh
* kube-dev-namespace fix
* qa-cronjob fix
> fix(qaplanetv2): small tweaks for new qa cluster

- gen3/bin/dcf.sh
Rename `dcf_dataservice` to `dcf-dataservice`
> fix(secret_name): rename dcf_dataservice to dcf-dataservice

- kube/services/jobs/arborist-rm-expired-access-cronjob.yaml
- kube/services/jobs/arborist-rm-expired-access-job.yaml
Name resolution issues for the mostly for cronjobs. sending DNS over TCP have gave us good results before.
https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts
https://github.com/gliderlabs/docker-alpine/issues/255
https://github.com/pgbouncer/pgbouncer/issues/332
> fix(dns): name resolution issue with kubernetes

- files/scripts/dream-access-report-cronjob.sh
- files/scripts/dream-access-report.py
Add dream access report cronjob, a weekly job only for fulfilling Dream challenge request
- Add dream access report cronjob
> feat(dream report): add dream report cronjob

- files/scripts/dream-access-report-cronjob.sh
- files/scripts/dream-access-report.py
minor fix to the dream report script: get dream team id from fence config instead of hard code it
- getting dream team id from fence config
> fix(team_id): get DREAM team id from fence config

- gen3/bin/kube-setup-hatchery.sh
error on service acount setup that we can ignore in gitops-sync
> fix(kube-setup-hatchery): failing in gitops-sync

- doc/dashboard.md
- doc/gitops.md
- gen3/bin/gitops.sh
* automatically create manifests from files in sub-directories under `manifests/`
* better handling of values from `manifest.json` when creating configmaps
> chore(configmaps): manifests/ support

- .gitignore
- gen3/bin/gitops.sh
- gen3/bin/jupyter.sh
- gen3/bin/kube-roll-all.sh
- gen3/lib/testData/manifests/frickjack/frickjack.json
- gen3/test/gitopsTest.sh
- kube/services/jobs/etl-cronjob.yaml
create sub-keys from entries in folder/folder.json for backward compatability
> fix(manifests): handling of folders

- files/dashboard/qa-reports/dashboard/index.html
- files/dashboard/qa-reports/dashboard/js/script.js
> Added quarterly filtering and redirect to login

- doc/README.md
- gen3/lib/testData/default/expectedFenceResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
- kube/services/fence/fence-deploy.yaml
- kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
* disable db-migrate init container in fence-deploy when fence-config sets ENABLE_DB_MIGRATION false
> fix(fence-deploy): fence-confg disables migrate

- Docker/Jenkins/Dockerfile
- Update Jenkins to 2.219 with latest changes and [security](https://jenkins.io/changelog/#v2.219) updates
> sec: Jenkins with latest security updates

- gen3/lib/testData/default/expectedFenceResult.yaml
- gen3/lib/testData/default/expectedSheepdogResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
- kube/services/arborist/arborist-deploy-2.yaml
- kube/services/fence/fence-deploy.yaml
- kube/services/guppy/guppy-deploy.yaml
- kube/services/indexd/indexd-deploy.yaml
- kube/services/manifestservice/manifestservice-deploy.yaml
- kube/services/peregrine/peregrine-deploy.yaml
- kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
- kube/services/sheepdog/sheepdog-deploy.yaml
- kube/services/sower/sower-deploy.yaml
- kube/services/ssjdispatcher/ssjdispatcher-deploy.yaml
- kube/services/wts/wts-deploy.yaml
* update k8s scheduling resource requests and limits
> chore(resources): add reqs/limits to deployments

- files/squid_whitelist/web_whitelist
- files/squid_whitelist/web_wildcard_whitelist
> chore(qa): Whitelist the NewRelic domain to facilitate POC

- gen3/bin/kube-dev-namespace.sh
* kube-dev-namespace secrets folder fix
> fix(kube-dev-namespace): secrets folder handling

- doc/ha-squid-migration.md
> fix(variable): wrong naming

- gen3/bin/db.sh
* db restore create restore db as server owner and grant perms to service user
> fix(db restore): create restore db as root

- gen3/bin/kube-setup-fence.sh
* disable db-migrate job in kube-setup-fence
> chore(kube-setup-fence): disable migrate job

- gen3/bin/kube-setup-indexingjob.sh
- Setup sower job for indexd_utils
> feat(indexing): setup indexing job

- doc/secrets.md
- gen3/bin/db.sh
- gen3/bin/kube-dev-namespace.sh
- gen3/bin/kube-setup-sheepdog.sh
- gen3/bin/secrets.sh
- gen3/lib/secrets/rotate-postgres.sh
* gen3 secrets rotate postgres indexd|sheepdog|fence
* kube-dev-namespace sets up new db users for indexd, sheepdog, and fence db's
> chore(gen3 secrets): pg rotate

- kube/services/status-api/status-api-deploy.yaml
- kube/services/status-api/status-api-deploy.yamml
- kube/services/status-api/status-api-service.yaml
Adding kube yaml files for the new status-api service.
> task(status): Add kubbe yamls to new status-api service

- kube/services/revproxy/gen3.nginx.conf/status-api-service.conf
Adding new URL path to expose the status endpoint publicly.
> task(status): Add new revproxy rule for the status-api endpoint

- tf_files/aws/rds/sample.tfvars
> chore(variables): new ones addeded

- doc/csoc-free-commons-steps.md
- tf_files/aws/modules/rds/main.tf
- leftover option turning into invalid  when applying
> fix(option): remove option block

- tf_files/aws/modules/vpc/cloud.tf
- vpc module tag for the actual vpc changed a few ago, causing mayor issues when deploying new commons, bringing it back to  how it was before.
> fix(tag): the tag Name shouldn't have changed in the first place

- gen3/bin/kube-setup-sheepdog.sh
* fix regression creating peregrine postgres user in new commons
> fix(peregrine): create postgres user

- files/scripts/braincommons/brain-custom-reports.sh
change file names in brain report cronjob
> fix(brain-reports): file names

- doc/ebs.md
- gen3/bin/ebs.sh
Added script to update ebs volumes
> feat(ebs-script): made script to update ebs volumes

- kube/services/indexd/indexd-deploy.yaml
- get hostname to indexd for DRS field `self_uri`
> get hostname in indexd

- kube/services/hatchery/hatchery-deploy.yaml
- kube/services/metadata/metadata-deploy.yaml
- kube/services/revproxy/revproxy-deploy.yaml
* expand hatchery config for dockstore apps
* allow workspaces to communicate directly with manifest service and revproxy
> chore(hatchery): more configs and helpers

- Docker/Jenkins/Dockerfile
- Docker/Jenkins/install-python3.6.sh
```
wget https://bootstrap.pypa.io/get-pip.py && \
+       python3.6 get-pip.py
```
> chore(qa): Install pip for python 3.6 in Jenkins

- gen3/bin/kube-setup-prometheus.sh
- kube/services/jenkins/10storageclass.yaml
- kube/services/jupyterhub/jupyterhub-storage.yaml
- kube/services/monitoring/prometheus-storageclass.yaml
- kube/services/wts/storageclass.yaml
* enable encryption in all storage classes
> chore(storage): set encryption flag - PXP-5111

- files/scripts/covid19-etl-cronjob.sh
- kube/services/jobs/covid19-etl-job.yaml
- Add COVID-19 ETL job
For ETL to run new version entry is required:
```
"covid19-etl": "quay.io/cdis/covid19-etl:latest"
```
> feat: COVID19 ETL job (PXP-5719)

- files/scripts/covid19-etl-cronjob.sh
> chore: change comment for setting cronjob

- files/scripts/covid19-etl-cronjob.sh
- Fix deployment step for COVID-19 adminVM cronjob
> chore: covid-19 adminVM cronjob deployment

- kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
- kube/services/jobs/google-init-proxy-groups-cronjob.yaml
- kube/services/jobs/google-manage-account-access-cronjob.yaml
- kube/services/jobs/google-manage-keys-cronjob.yaml
- kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
* google cron jobs check webhook validity
> fix(google-crons): check slack hook validity

- doc/network-diagrams.md
> fix(typo):

- files/scripts/covid19-idph-etl-cronjob.sh
- kube/services/jobs/covid19-idph-etl-job.yaml
- ETL job for Illinois Department for Public Health data
> feat: ETL job for IDPH data

- files/squid_whitelist/web_whitelist
- Added www.dph.illinois.gov to Squid whitelist
> feat: idph website for covid-19 etl job

- kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml
- aws-es-proxy new release ready
> chore(aws-es-proxy): bump version

- files/scripts/covid19-etl-cronjob.sh
- kube/services/jobs/covid19-etl-job.yaml
- Restructure the ETL for COVID-19 Data Commons
- All ETL now have the same image and entrypoint, depend on the environmental variable
> feat: new structure for covid19 etl

- files/squid_whitelist/web_whitelist
Whitelisting a couple of chef.io domains
> add(chef.io): to the whitelist

- tf_files/aws/data_bucket_queue/cloud.tf
- tf_files/aws/data_bucket_queue/outputs.tf
- tf_files/aws/data_bucket_queue/sample.tfvars
- tf_files/aws/data_bucket_queue/variables.tf
- tf_files/aws/modules/data-bucket-queue/README.md
- tf_files/aws/modules/data-bucket-queue/cloud.tf
- tf_files/aws/modules/data-bucket-queue/outputs.tf
- tf_files/aws/modules/data-bucket-queue/variables.tf
- tf_files/aws/modules/upload-data-bucket/main.tf
* support `gen3 workon profile whatever__data_bucket_queue`
> fix(data-bucket-queue): bucket notifications hook

- doc/iam-serviceaccount.md
> chore: update gen3 iam-serviceaccount doc

- kube/services/jobs/nb-etl-cronjob.yaml
- kube/services/jobs/nb-etl-job.yaml
> Notebook ETL job

- files/squid_whitelist/web_wildcard_whitelist
- Describe what this pull request does.
add pandemicresponsecommons.org to whitelist
> chore(add pandemicresponsecommons.org to whitelist)

- tf_files/aws/commons/README.md
- Commons documentation updated. A few typos fixed.
> fix(typos):

- ansible/hosts.yaml
> fix(hostnames): and names

- kube/services/jobs/covid19-etl-job.yaml
- kube/services/jobs/covid19-idph-etl-job.yaml
- kube/services/jobs/covid19-jhu-etl-job.yaml
* slack message for covid19-etl-*-job
> chore(jobs/covid19-etl): add slack messaging

- Jenkinsfile
Introduce empty string to comply with the new method signature:
https://github.com/uc-cdis/cdis-jenkins-lib/blob/master/vars/testHelper.groovy#L135
> fix(qa): Comply with the checkPodHealth method signature

- Docker/Jenkins2/Dockerfile
- Docker/Jenkins2/README.md
- Docker/Jenkins2/jenkins-master-deployment.yaml
- Docker/Jenkins2/jenkins.values
- Docker/Jenkins2/jenkins2.sh
This is an experiment based on the Innovation Day project
> chore(qa): Creating Jenkins2 with Kubernetes plugin capabilities

- tf_files/aws/modules/eks/data.tf
- Nat gateway data resource look up sometimes fails if it finds another resource with the same search criteria. For example you made a mistake applying a plan and have to rebuild again, the gateway might get deleted but not removed. Adding an additional filter solves this problem.
> chore(filter): nat gatway status

- files/scripts/qa-cronjob.sh
qa-cronjob works with Gen3Secrets
> fix(qa-cron): work with Gen3Secrets

- files/squid_whitelist/web_wildcard_whitelist
add occ-pla.net to squid whitelist
> add occ-pla.net to squid

- apis_configs/user.yaml
> chore(remove-abby): removed abby from user yamls

- tf_files/azure/cloud.tf
- tf_files/azure/variables.template
- tf_files/azure/variables.tf
> feat(azure): Now outdated azure beginnings

- ansible/hosts.yaml
> add(fitbir): new commons

- tf_files/aws/csoc_common_logging/variables.tf
- tf_files/aws/modules/common-logging/variables.tf
- Lambda function for logging parsing would fail if a variable has no value. To fix this, we have set a default value to avoid having to set that up manually on every environment.
> add(default) value for a required variable

- gen3/bin/kube-setup-fluentd.sh
- When fluentd was set to use the latest version, the configmap created off the configuration file would have the wrong name which ultimately resulted in crashed pods. 
The file name is created temporarily prior the application with the right name to avoid this issue.
> fix(bug): configmap creation issues

- files/squid_whitelist/web_whitelist
- added mran.microsoft.com to the whitelist
> add(domain):

- files/scripts/braincommons/brain-custom-reports.sh
Extend brain report cron job to run till June
> chore(brain-report): extend date range

- files/squid_whitelist/web_wildcard_whitelist
- .adfs.federation.va.gov whitelisted
> add(.adfs.federation.va.gov): to the wildcard list

- gen3/bin/kube-dev-namespace.sh
- gen3/lib/secrets/rotate-postgres.sh
fix kube-dev-namespace issues setting up databases and bashrc
> fix(kube-dev-namespace): db setup

- doc/bucket-manifest.md
- gen3/bin/bucket-manifest.sh
- kube/services/jobs/bucket-manifest-job.yaml
- tf_files/aws/batch/root.tf
- tf_files/aws/batch/variables.tf
- tf_files/aws/bucket_manifest/root.tf
- tf_files/aws/bucket_manifest/variables.tf
- tf_files/aws/modules/account-management-logs/cloud.tf
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-5880)
aws batch job for bucket manifest generating tool
> feat(aws_batch): aws batch setup

- gen3/bin/klock.sh
- gen3/test/klockTest.sh
* klock handles strange lock owners better
> fix(klock): k8s label value rules, exit codes

- gen3/bin/bucket-manifest.sh
> fix(typos): fix typos

- files/squid_whitelist/web_wildcard_whitelist
> add rstudio.com to whitelist

- doc/prometheus.md
- doc/shutdown.md
- gen3/bin/kube-roll-all.sh
- gen3/bin/prometheus.sh
- gen3/lib/utils.sh
* add `kube-setup-metadata` to `gen3 roll all`
* add `kube-setup-metadata` to `gen3 roll all`
> fix(roll-all): call kube-setup-metadata

- tf_files/aws/eks/root.tf
- tf_files/aws/eks/variables.tf
- tf_files/aws/role/README.md
> chore(eks terraform): oidc-thumbprint variable

- gen3/bin/bucket-manifest.sh
use empty string instead of null
> fix(authz): use empty string instead of null

- files/squid_whitelist/web_wildcard_whitelist
- gen3/bin/netpolicy.sh
to support explicit proxy
* fix handling of squid IP lookup for external network policy on admin vm
* fix handling of squid IP lookup for external network policy on admin vm
> fix(netpolicy-external): fix egress to squid

- files/squid_whitelist/web_wildcard_whitelist
> feat: whitelist census.org

- doc/gcp-bucket-manifest.md
- gen3/bin/gcp-bucket-manifest.sh
- kube/services/jobs/google-bucket-manifest-job.yaml
Refactor the gen3 gcp-bucket-manifest command to pickup the change in the https://github.com/uc-cdis/google-bucket-manifest/pull/1
> chore(code): refactor

- kube/services/selenium/selenium-hub-deployment.yaml
- kube/services/selenium/selenium-node-chrome-deployment.yaml
> chore(qa): Adjusting the Selenium config

- files/scripts/qa-restart-selenium.sh
Performing a restart to avoid any "resource leakage".
> chore(qa): Restart Selenium Hub + Nodes every night

- kube/services/jobs/nb-etl-cronjob.yaml
* Runs notebook etl in the morning (10am Chicago time, server time is in UTC), instead of running it every 3 hours
> feat: run notebook etl in the morning

- kube/services/jobs/nb-etl-cronjob.yaml
- kube/services/jobs/nb-etl-job.yaml
- run bayes model for IL-by-county twice as fast
> up nb-etl cpu to 4

- doc/bucket-replicate.md
- gen3/bin/bucket-replicate.sh
- kube/services/jobs/bucket-replication-job.yaml
Added bucket replication job that uses aws batch
> feat(bucket-replication-job): Added aws batch bucket replication job

- files/squid_whitelist/web_whitelist
- files/squid_whitelist/web_wildcard_whitelist
Added wildcard *.chef.io to squid whitelist
> chore(chef-whitelist): added wildcard *.chef.io to whitelist

- Docker/Jenkins-Worker/Dockerfile
> fix(qa): Fix Gen3-QA-Worker Dockerfile

- doc/gen3OnK8s.md
(No applicable Jira ticket)
DOCS: Make template ssjdispatcher block in creds.json example generic (give dummy values)
> docs(creds-ssjd): make template ssjd creds block generic

- Docker/Jenkins-Worker/Dockerfile
- gen3/test/dbTest.sh
Reverts uc-cdis/cloud-automation#1299
> Revert "fix(qa): Fix Gen3-QA-Worker Dockerfile"

- doc/ec2.md
- gen3/bin/ec2.sh
- gen3/test/dbTest.sh
- gen3/test/ec2Test.sh
Jira Ticket: [PXP-6323](https://ctds-planx.atlassian.net/browse/PXP-6323)
Couple new helpers to simplify scaling a node pool.
* `gen3 ec2 asg-describe`
* `gen3 ec2 asg-set-capacity`
> chore(ec2): asg-describe, asg-set-capacity helpers

- Docker/Jenkins-Worker/Dockerfile
> fix(qa): Fix Dockerfile instructions for Gen3-QA-Worker

- kube/services/jobs/nb-etl-cronjob.yaml
- kube/services/jobs/nb-etl-job.yaml
- increase memory allocation for nb-etl job so it doesn't get killed OOM by k8s
> up nb-etl mem to 16

- kube/services/indexd/indexd-deploy.yaml
Modify network ingress policy for indexd to allow metadataservice to talk to it.
> Allow mds to talk to indexd

- doc/csoc-free-commons-steps.md
- tf_files/aws/modules/eks/endpoints.tf
> fix(typo): endpoint description

- gen3/bin/kube-setup-workvm.sh
* configure aws ntp on ec2 admin vm's: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
* configure aws ntp on ec2 admin vm's: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
> chore(setup-workvm): configure aws ntp

- gen3/bin/kube-setup-auspice.sh
- kube/services/auspice/README.md
- kube/services/auspice/auspice-deploy.yaml
- kube/services/auspice/auspice-service-elb.yaml
- kube/services/auspice/auspice-service.yaml
- kube/services/netpolicy/gen3/services/revproxy_netpolicy.yaml
- kube/services/revproxy/gen3.nginx.conf/auspice-service.conf
Add deployment and service file of auspice
Add auspice service's .yaml file
> feat(auspice): add auspice

- kube/services/fenceshib/fenceshib-deploy.yaml
* increase resources allocated to fenceshib deployment
* increase resources allocated to fenceshib deployment
> chore(fenceshib): up resources

- files/squid_whitelist/web_wildcard_whitelist
- add gstatic.com to squid_wildcard_whitelist to allow fetch google mobility data
> add gstatic.com to squid_wildcard_whitelist

- tf_files/aws/modules/upload-data-bucket/s3.tf
- Ignore changes if the data-upload-bucket has cors_rules,
> chore(lifecycle): ignore changes

- kube/services/jobs/aws-bucket-replicate-job.yaml
- kube/services/jobs/google-bucket-replicate-job.yaml
- kube/services/jobs/remove-objects-from-clouds-job.yaml
- kube/services/jobs/replicate-validation-job.yaml
> fix(image): fix image names

- gen3/bin/bucket-manifest.sh
> fix(dir): fix directory

- gen3/bin/bucket-manifest.sh
> fix(bucket-manifest): Fix batch_clean_all_function declaration

- gen3/bin/bucket-manifest.sh
- tf_files/aws/batch/root.tf
Fixed terraform and updated bucket-manifest script
> fix(batch-tf): fixed terraform for batch job and updated script

- files/squid_whitelist/web_wildcard_whitelist
* Added wildcard `.southsideweekly.com` to allow grabbing the CHI-NBHD dataset for PRC
> feat: add southsideweekly for PRC access

- Docker/python-nginx/python3.6-alpine3.7/Dockerfile
Adding `logrotate` to `fence`'s base image.
> chore(qa): Add logrotate to python-nginx img

- doc/db.md
- gen3/bin/db.sh
- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
- tf_files/aws/encrypted-rds/kube.tf
- tf_files/aws/encrypted-rds/variables.tf
Added default encryption to rds databases. Also changed default size to t2.small because encryption is not available for t2.micro instances.
> feat(encrypted-rds): Added default encryption to rds

- kube/services/mariner/mariner-deploy.yaml
- apply cloud-automation filter for image tag for mariner deployment
> use cloud-auto filter for mariner image tag

- Docker/python-nginx/python3.6-alpine3.7/uwsgi.conf
This is a requirement for https://github.com/uc-cdis/cloud-automation/pull/1348
> chore(qa): enable nginx status endpoint

- doc/csoc-free-commons-steps.md
> fix(doc): fix doc

- tf_files/aws/commons/README.md
- tf_files/aws/commons/kube.tf
- tf_files/aws/commons/variables.tf
- RDS cluster autoscaling can now be enabled in terraform by just setting the variables to their desired value
> chore(autoscaling): enabled the feature

- gen3/bin/kube-setup-metadata.sh
Small bug in `kube-setup-metadata`
> fix(kube-setup-metadata): bang handling

- gen3/bin/gcp-bucket-manifest.sh
Truncate long gs resource names
> fix(names): truncate long names

- gen3/lib/bootstrap/templates/Gen3Secrets/00configmap.yaml
- kube/services/jobs/usersync-job.yaml
* fix ADD_DBGAP flag handling in usersync job
> fix(usersync): ADD_DBGAP flag handling

- gen3/bin/gcp-bucket-manifest.sh
Only count the bucket blobs not directories
> chore(blobs): count bucket blobs

- kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
Enable monitoring for presigned url fence.
- New side cars for the PreSigned URL Fence deployment.
> chore(observability): Enable monitoring for presigned url fence

- Chef/repo/cookbooks/cdis_admin_vm/attributes/default.rb
- Chef/repo/cookbooks/cdis_admin_vm/kitchen.yml
- Chef/repo/cookbooks/cdis_admin_vm/recipes/workvm.rb
- Chef/repo/cookbooks/cdis_admin_vm/test/integration/data_bags/users/qa.json
Updated cookbook to allow for jenkins to run kitchen tests
> feat(chef-tests): Updated cookbook to allow for chef tests

- files/squid_whitelist/web_wildcard_whitelist
Add caninedc.org  to squid to resolve wts error
> add caninedc.org to squid whitelist

- gen3/bin/db.sh
- gen3/bin/ecr.sh
- gen3/bin/gitops.sh
- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-arranger.sh
- gen3/bin/kube-setup-auspice.sh
- gen3/bin/kube-setup-guppy.sh
- gen3/bin/kube-setup-requestor.sh
- gen3/lib/bootstrap/templates/cdis-manifest/manifest.json
- kube/services/requestor/requestor-deploy.yaml
- kube/services/requestor/requestor-service.yaml
- kube/services/revproxy/gen3.nginx.conf/requestor-service.conf
Jira Ticket: [PXP-6485](https://ctds-planx.atlassian.net/browse/PXP-6485)
deployment files for [Requestor service](https://github.com/uc-cdis/requestor)
- Requestor deployment
> PXP-6485 Requestor deployment

- gen3/lib/manifestDefaults/modsec/modsecurity.conf
Deploying WAF as the default to the envs
> chore : deploying WAF as default

- kube/services/fluentd/fluentd.yaml
* add `selector:` to fluentd daemonset yaml
> fix(fluentd): daemonset needs selector

- gen3/bin/db.sh
- tf_files/aws/encrypted-rds/kube.tf
Fixed minor bugs
actually encrypt fence/sheepdog
./ didn't work with db restore so I changed var to be the users home directory instead
> fix(db-encryption): fixed some minor bugs in db encryption script

- files/scripts/braincommons/brain-custom-reports.sh
- gen3/bin/kube-setup-dashboard.sh
- gen3/bin/kube-setup-mariner.sh
- gen3/bin/kube-setup-roles.sh
- kube/services/mariner/mariner-deploy.yaml
Jira Ticket: [PXP-6753](https://ctds-planx.atlassian.net/browse/PXP-6753)
* add more automation to kube-setup-mariner
* add more automation to kube-setup-mariner
> chore(mariner): setup AWS creds, bucket

- tf_files/aws/account-policies/enable_cloudtrail.tf
- tf_files/aws/account-policies/iam_policies.tf
- tf_files/aws/account-policies/main.tf
Fix various issues with the account-policies tf module
> Fix various issues with account-policies module

- files/scripts/covid19-etl-job.sh
- gen3/bin/api.sh
Jira Ticket: COV-431
- Add "exp" and "skip_cache" arguments to "gen3 api access-token" command
> Add args to access-token command

- .secrets.baseline
- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-mariner.sh
- gen3/bin/kube-setup-sower-jobs.sh
- kube/services/portal/portal-deploy.yaml
- tf_files/aws/account-policies/sample.tfvars
* mariner read-write bucket fix
* sower-jobs indexd user fix
* portal max-surge to 2
* account-policies `sample.tfvars`
* mariner read-write bucket fix
* sower-jobs indexd user fix
* portal max-surge to 2
* account-policies `sample.tfvars`
> chore(small): prometheus, sower, mariner, portal

- gen3/bin/gcp-bucket-manifest.sh
> fix(path): use gen3 home path

- files/squid_whitelist/web_whitelist
Add docs.google.com to squid_proxy
> chore(squid_proxy): add docs.google.com

- files/squid_whitelist/web_whitelist
Add biorender.com to the proxy's whitelist
> feat(biorender): add biorender.com to whitelist

- .secrets.baseline
- gen3/lib/aws.sh
- tf_files/aws/modules/utility-vm/README.md
- tf_files/aws/modules/utility-vm/cloud.tf
- tf_files/aws/modules/utility-vm/variables.tf
- tf_files/aws/utility_vm/root.tf
- tf_files/aws/utility_vm/variables.tf
Jira Ticket: [PXP-6668](https://ctds-planx.atlassian.net/browse/PXP-6668)
* add `user_policy` to `tf_files/.../utilityvm` to support IAM role setup
* add `user_policy` to `tf_files/.../utilityvm` to support IAM role setup
> chore(utilityvm): add user_policy variable

- doc/kube-setup-access-frontend.md
- gen3/bin/kube-setup-access-frontend.sh
- tf_files/aws/access/cloud.tf
- tf_files/aws/access/variables.tf
Added access frontend setup script
> feat(access-fronted): Added access frontend setup script

- doc/bucket-size-report.md
- files/scripts/bucket-size-report.py
- kube/services/jobs/bucket-size-report-job.yaml
Added automation for creating a bucket size report
> feat(bucket-size-report): Added job to create a bucket size report

- gen3/bin/kube-roll-all.sh
Added access backend to kube-roll-all
> feat(access-roll): Added access-backend to kube-roll-all

- kube/services/jenkins/00pvc.yaml
Increased pv size for jenkins to match manually increases ebs size
> fix(jenkinx-pv-size): Updated the size of Jenkins persistent volume.

- .secrets.baseline
- doc/slurm_cluster.md
- gen3/bin/kube-setup-system-services.sh
- tf_files/aws/modules/eks/init_cluster.sh
* calico updates to the latest version
* `gen3 kube-setup-system-services` should update any already deployed cluster
> Chore/update calico 1.7

- files/dashboard/open-links/README.md
- files/dashboard/open-links/app.css
- files/dashboard/open-links/download-helper.js
- files/dashboard/open-links/index.html
- files/dashboard/usage-reports/README.md
- files/dashboard/usage-reports/src/base.css
* add new `open-links` dashboard app to demo download of open-access data
* add new `open-links` dashboard app to demo download of open-access data
> chore(dashboard/open-links): new dash app

- gen3/bin/kube-setup-workvm.sh
The gen3 config-env command has a new dependency pygit2. This dependency requires libgit2. 
pylib2 added
> add new dependency

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-mariner.sh
- gen3/bin/kube-setup-secrets.sh
- gen3/bin/kube-setup-ws-storage.sh
- kube/services/revproxy/gen3.nginx.conf/ws-storage.conf
- kube/services/ws-storage/README.md
- kube/services/ws-storage/ws-storage-deploy.yaml
- kube/services/ws-storage/ws-storage-service.yaml
Jira Ticket: [PXP-7013](https://ctds-planx.atlassian.net/browse/PXP-7013)
* automation for ws-storage service
* automation for ws-storage service
> chore(ws-storage): automation for new service

- doc/ecr.md
- gen3/bin/ecr.sh
Add ability to sync docker images from docker hub to quay.io
> Add ability to sync images from docker hub to quay.io

- files/squid_whitelist/web_whitelist
* add conda.anaconda.org to the whitelist
> chore(squid): add conda to whitelist

- files/squid_whitelist/web_wildcard_whitelist
add  anaconda.com to whitelist
> add  anaconda.com

- kube/services/jobs/covid19-etl-job.yaml
Google cloud setup for covid19
Put google cloud credential into Gen3Secrets/g3auto/covid19-etl/default.json
> feat(gcp): google cloud configuration for covid19

- Docker/awshelper/Dockerfile
- README.md
- files/squid_whitelist/web_whitelist
- gen3/bin/kube-setup-workvm.sh
> fix(helm): Updated repo to non-deprecated one

- Docker/Jenkins2/Dockerfile
Bumping up version of the parent img for Jenkins 2
> chore(qa): Upgrade Jenkins2

- gen3/bin/gen3qa-run.sh
- kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Jira Ticket: [PXP-7308](https://ctds-planx.atlassian.net/browse/PXP-7308)
Creating Gen3 CLI command to run a gen3-qa test in PROD-tier environments.
This first test is focused on an automated access check against all the acl's or authz's associated with a given user, i.e., to make sure google buckets associated with an indexd record from each project (access context) is accessible.
- New Gen3 CLI command (`gen3 gen3qa-run <test_job>`)
> task(qa): Create gen3 cli command to run gen3-qa tests (automated access checks)

- Jenkinsfile
Introducing new labels to facilitate the PR checks on this repo.
> chore(ci): Introduce new labels to skip unnecessary pipeline stages

- gen3/bin/gen3qa-run.sh
- kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Use Selenium 4 and apply a better readiness probe config.
> chore(qa): Improve gen3qa-check-bucket-access k8s job

- Docker/Jenkins-Worker/Dockerfile
Installing Ruby on Jenkins Worker to run more automation scripts.
> chore(qa): Install Ruby on Jenkins Worker

- files/squid_whitelist/web_whitelist
For covid19 Com-Mobility project
> chore(gstatic): add  gstatic.com to the whitelist

- Jenkinsfile
> fix(qa): Skip network policy deletion for doc-only PRs

- files/squid_whitelist/web_whitelist
Reverts uc-cdis/cloud-automation#1472
> Revert "chore(gstatic): add  gstatic.com to the whitelist"

- tf_files/aws/cognito/README.md
No directly related Jira but relevant for https://ctds-planx.atlassian.net/browse/PXP-7183 
- Clarify metadata exchange instructions for cognito-adfs integration
> docs(cognito): Clarify metadata exchange instructions

- Jenkinsfile
Quantify failures in our CI Pipeline to prioritize efforts around the investigation / mitigation / resolution of intermittent issues.
> chore(metrics): Write metrics for every pipeline stage

- gen3/bin/reset.sh
Adding AWS_SQS purge-queue for cleaning pending messages before each PR check (CI flow)
> chore: add aws_sqs

- files/squid_whitelist/web_wildcard_whitelist
> chore(jenkins): Whitelist jenkins.io to support plugins / security maintenance

- kube/services/indexd/indexd-deploy.yaml
Jira Ticket: [PXP-7422](https://ctds-planx.atlassian.net/browse/PXP-7422)
Enabling metrics for Indexd.
- Enabling Nginx and USGI metrics for Indexd.
> task(observability): Enable prometheus metrics scraping for indexd

- Jenkinsfile
> fix(qa): Fix the call to the CleanS3 function

- gen3/bin/kube-setup-fluentd.sh
* fix bug in kube-setup-fluentd
* fix bug in kube-setup-fluentd
> fix(setup-fluentd): namespace handling

- gen3/bin/kube-setup-system-services.sh
- tf_files/aws/eks/variables.tf
- tf_files/aws/modules/eks/variables.tf
Upgrading to K8's version 1.16
> Updated EKS version

- files/squid_whitelist/web_whitelist
* squid github-releases.githubusercontent
* squid github-releases.githubusercontent
> chore(squid): github-releases.githubusercontent

- Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
Only start scraping metrics in the service's `/metrics` endpoint if this url path is responsive.
> chore(observability): Enable scraping from the service /metrics endpoint if it exists

- kube/services/revproxy/gen3.nginx.conf/ambassador-service.conf
- kube/services/revproxy/gen3.nginx.conf/hatchery-service.conf
- kube/services/revproxy/revproxy-service-elb.yaml
Jira Ticket: [PXP-7220](https://ctds-planx.atlassian.net/browse/PXP-7220)
- Add timeout for ELB as well as hatchery and ambassador endpoints to prevent the noVNC firefox lost connection with client every minutes
> PXP-7220 Fix/novnc timeout

- kube/services/jobs/google-bucket-manifest-job.yaml
Use poetry for the google-bucket-manifest-job.
> chore(ci): Adopt poetry for google-bucket-manifest-job

- Jenkinsfile
- doc/cogwheel-setup.md
- kube/services/cogwheel/cogwheel-deploy.yaml
- kube/services/cogwheel/cogwheel-service.yaml
- kube/services/jobs/cogwheel-register-client-job.yaml
- kube/services/revproxy/gen3.nginx.conf/cogwheel-service.conf
Jira Ticket: [PXP-5703](https://ctds-planx.atlassian.net/browse/PXP-5703)
[Cogwheel](https://github.com/uc-cdis/cogwheel) is a new service that translates between two authN protocols, SAML and OIDC. It can, for example, act as an IdP for Fence and authenticate users via InCommon. 
- Add k8s service, revproxy, other setup, and documentation for new Cogwheel service
> (PXP-5703): Feat/cogwheel

- Jenkinsfile
- kube/services/jobs/fence-visa-update-cronjob.yaml
- Slack webhook for visa-update-cronjob
> (PXP-7758): Add Slack Webhook for Visa Update Cronjob

- kube/services/jobs/etl-cronjob.yaml
- kube/services/jobs/etl-job.yaml
- Slack notification for ETL job or cronjob in case of both success or failure
> ETL job slack notification

- files/squid_whitelist/web_whitelist
- files/squid_whitelist/web_wildcard_whitelist
https://ctds-planx.atlassian.net/browse/DEVOPS-6
adding Qualys cloud agent to the squid whitelist
> chore(VA):adding qualys to whitelist

- kube/services/jobs/nb-etl-cronjob.yaml
- kube/services/jobs/nb-etl-job.yaml
Jira Ticket: [COV-379](https://ctds-planx.atlassian.net/browse/COV-379)
Add slack webhook to nb-etl job.
> Add slack webhook to nb-etl

- gen3/bin/reset.sh
Fail reset if any error happens.
> Fail on error

- gen3/bin/reset.sh
Reverts uc-cdis/cloud-automation#1547
needs more testing.
> Revert "Fail on error"

- .secrets.baseline
- Docker/Jenkins2/jenkins-master-deployment.yaml
- gen3/bin/kube-setup-autoscaler.sh
- gen3/bin/kube-setup-metrics.sh
- gen3/bin/kube-setup-system-services.sh
- gen3/bin/scaling.sh
- kube/README.md
- kube/services/ambassador-gen3/ambassador-gen3-hpa.yaml
- kube/services/ambassador/ambassador-hpa.yaml
- kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
- kube/services/jupyterhub/jupyterhub-deploy.yaml
- kube/services/kube-proxy/kube-proxy-daemonset.yaml
- kube/services/metrics-server/components.yaml
- kube/services/qabot/qabot-deploy.yaml
Jira Ticket: [PXP-7381](https://ctds-planx.atlassian.net/browse/PXP-7381)
- https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prerequisites
- Take control over our kube-proxy daemonset and configure it with CM instead (See link above)
- Update ClusterAutoscaler
- Update kubernetes metrics-server 
- Update manifests/documentation that uses deprecated k8s api versions.
> Automate manual stuff for k8s upgrade

- kube/services/jobs/covid19-bayes-model-cronjob.yaml
- kube/services/jobs/covid19-bayes-model-job.yaml
- kube/services/jobs/covid19-notebook-etl-cronjob.yaml
- kube/services/jobs/covid19-notebook-etl-job.yaml
Jira Ticket: COV-807
- Add covid19-bayes-model job
> Add covid19-bayes-model job

- kube/services/jobs/covid19-notebook-etl-cronjob.yaml
- kube/services/jobs/covid19-notebook-etl-job.yaml
Jira Ticket: COV-801
Add Google bigquery creds to covid19-notebook-etl job (same creds as covid19-etl job)
> covid19-notebook-etl Google bigquery creds

- tf_files/aws/modules/eks/cloud.tf
Reverts uc-cdis/cloud-automation#1558
Needs more testing.
> Revert "restrict jupyter nodes to a single az"

- gen3/bin/gen3qa-run.sh
The k8s job that runs this Gen3-QA test in PROD requires a `selenium` sidecar due to the nature of CodeceptJS.
```
cloud-automation/kube/services/jobs/gen3qa-check-bucket-access-job.yaml
```
But, unfortunately, the selenium / JVM runs in a sidecar container perpetually (not an ephemeral process).
Therefore we need to kill it otherwise this will break `gitops-sync` and `kube-wait4-pods`.
NOTE: I have also experimented with k8s lifecycle `preStop` hooks but, unfortunately, even when we kill the processes inside the container, it is auto-restarting (ignoring the `restartPolicy: Never`).
- Prevent hung `gen3qa-check-bucket-access` pods.
> choore(test-in-prod): Introduce kill switch for gen3qa-run due to Selenium side car

- files/dashboard/usage-reports/src/dataHelper.js
- files/dashboard/usage-reports/src/index.html
- files/dashboard/usage-reports/src/reportsMain.js
- files/scripts/reports-cronjob.sh
- gen3/bin/logs.sh
- gen3/lib/logs/daily.sh
https://ctds-planx.atlassian.net/browse/PXP-7861
> Add Fence OIDC login metrics to dashboard

- kube/services/auspice/auspice-deploy.yaml
Updated hostname so the connection to auspice works
> fix(auspice-deploy): Updated hostname so auspice could be reached

- kube/services/jobs/covid19-bayes-model-cronjob.yaml
- kube/services/jobs/covid19-bayes-model-job.yaml
Jira Ticket: COV-719
relates to https://github.com/uc-cdis/covid19model/pull/27
- PRC covid19-bayes-model job: add configurable state list
> PRC covid19-bayes-model job: add state list

- kube/services/influxdb/influxdb-policy.yaml
We need to document this here in case we need to re-provision qaplanetv2.
> chore(ci-metrics): Network policy for InfluxDB

- kube/services/jobs/covid19-bayes-model-cronjob.yaml
- kube/services/jobs/covid19-bayes-model-job.yaml
- covid19-bayes-model-(cron)job 20Gi memory
> covid19-bayes-model-job 20Gi memory

- files/scripts/jenkins-cronjob.sh
Adding Debugging line to the cronjob script
> adding debug lines

- kube/services/auspice/auspice-deploy.yaml
Jira Ticket: [COV-852](https://occ-data.atlassian.net/browse/COV-852)
> feat(token): add mapbox token

- kube/services/selenium/selenium-hub-nodes-policy.yaml
- kube/services/selenium/selenium-nodes-hub-policy.yaml
Let us document this in case qaplanetv2 is obliterated.
> chore(selenium): Document networkpolicies for selenium-hub and nodes.

- gen3/lib/logs/utils.sh
* Change domain to correct one
> feat: change vadc domain to current one

- Docker/squid/Dockerfile
- flavors/squid_auto/squid_running_on_docker.sh
https://ctds-planx.atlassian.net/browse/PXP-7599
> chore(squid):version upgrade to 4.14

- files/squid_whitelist/web_whitelist
Add repo.continuum.io to whitelist
> Add repo.continuum.io to whitelist

- .github/workflows/build.yaml
Added gh action to push images to ECR
> feat(ECR-push): Added github action to push images to ECR

- gen3/bin/save-failed-pod-logs.sh
> chore(k8sReset-debug): Capture logs and events for Evicted pods

- files/squid_whitelist/web_wildcard_whitelist
> add midrc to squid whitelist

- Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
> Fix ENABLE_SVC_METRICS_SCRAPING logic

- gen3/bin/ecr.sh
Adding ECR `describe-image` to `ecr.sh`
> chore(ecr): add describe-image command

- Jenkinsfile
> fix(ci): New fetchCIEnvs method signature

- Docker/Jenkins2/Dockerfile
Bump jenkins 2 version to 2.298
> bump version

- .secrets.baseline
- Docker/Jenkins/Dockerfile
update jenkins version to 2.298
> update jenkins version.

- tf_files/aws/commons/kube.tf
Added bucket permissions to EKS worker node policy
> fix(qualys-agent): added qualys s3 repo to bucketreader policy

- .secrets.baseline
- gen3/bin/kube-setup-guppy.sh
- gen3/bin/kube-setup-metadata.sh
- gen3/bin/secrets.sh
- gen3/lib/utils.sh
- kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml
- kube/services/metadata/metadata-deploy.yaml
Jira Ticket: [PXP-8190](https://ctds-planx.atlassian.net/browse/PXP-8190)
* Common code to wait for Elasticsearch to be ready
* Metadata service now uses Elasticsearch for the sake of aggregated metadata APIs
> feat(ecosystems): elasticsearch for MDS

- files/scripts/reports-cronjob.sh
Reverts uc-cdis/cloud-automation#1644
> Revert "Chore/reports cron parametrize date"

- files/squid_whitelist/web_whitelist
Jira Ticket: [PXP-223](https://ctds-planx.atlassian.net/browse/HP-223)
* Enable web access to the ICPSR repository
> chore(squid): allow ICPSR repository

- tf_files/aws/datadog/sample.tfvars
- tf_files/aws/datadog/variables.tf
Added missing datadog permissions
> fix(dd-permissions): Added missing datadog permissions

- gen3/bin/kube-setup-metadata.sh
* Only try to allocate ES proxy on metadata setup if the feature that needs it is enabled
> fix(mds): only try to allocate ES if needed

- files/squid_whitelist/web_whitelist
Jira Ticket: [HP-235](https://ctds-planx.atlassian.net/browse/HP-235)
* Squid update to allow clinicaltrials.gov
> chore(squid): allow clinicaltrials.gov

- Docker/Jenkins-Worker/Dockerfile
> fix: installing git in Jenkins slave image

- files/squid_whitelist/web_whitelist
Jira Ticket: [HP-234](https://ctds-planx.atlassian.net/browse/HP-234)
* Allow connecting to the monqcle API for PDAPS data
> HP-234 chore(heal): allow PDAPS API connectivity

- kube/services/mariner/mariner-deploy.yaml
> feat(mariner-netpolicy): Added netpolicy for mariner

- kube/services/jobs/etl-job.yaml
Added slack webhook alerts to standard ETL jobs
> feat(ETL-slack-alerts): Added slack alerts to regular ETL jobs

- kube/services/jenkins-ci-worker/jenkins-worker-ci-deployment.yaml
- kube/services/jenkins-worker/jenkins-worker-deployment.yaml
- kube/services/jenkins/jenkins-deploy.yaml
- kube/services/selenium/selenium-hub-deployment.yaml
- kube/services/selenium/selenium-node-chrome-deployment.yaml
> fix(ci-infra): Set correct safe-to-evict config

- kube/services/jenkins-ci-worker/jenkins-worker-ci-deployment.yaml
> chore(ci-infra): Tweak specs for ci-worker pod

- gen3/bin/mutate-guppy-config-for-guppy-test.sh
- gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
> fix(ci): Tweak guppy config mutation for bloodpac-like envs

- gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
The guppy config pods are failing due to this error:
```
$ kc logs guppy-deployment-6674b75c66-nxd7v
undefined:12
"config_index": "3270.cdis-manifest.gen3.theanvil.io_array-config,
```
It's missing a closing double-quotation mark 🤦🏼
> fix(pfb-export-test): Process double-quotes correctly for array-config in guppy config

- gen3/bin/kube-setup-portal.sh
- kube/services/portal/portal-deploy.yaml
Jira Ticket: [PXP-8364](https://ctds-planx.atlassian.net/browse/PXP-8364)
- Pass the data upload bucket name in fence-config into portal as `DATA_UPLOAD_BUCKET` when doing `kube-setup-portal`
> PXP-8364 Fix/portal csp

- kube/services/devbot/devbot-deploy.yaml
- kube/services/devbot/devbot-service.yaml
- kube/services/revproxy/gen3.nginx.conf/devbot-service.conf
Introduce dev-bot to Slack to automate routine tasks / increase productivity.
This new bot utilizes SLACK EVENTS instead of the deprecated RTM Client. 🎉
> chore(productivity): Introduce dev bot

- gen3/bin/sqs.sh
- gen3/lib/g3k_manifest.sh
- tf_files/aws/modules/sqs/cloud.tf
- tf_files/aws/modules/sqs/variables.tf
- tf_files/aws/sqs/cloud.tf
- tf_files/aws/sqs/variables.tf
> feat(sqs-monitoring): Added sqs monitoring

- Docker/Jenkins-Worker/Dockerfile
- Docker/Jenkins-Worker/install-python3.6.sh
- Docker/Jenkins-Worker/install-python3.8.sh
To allow new pieces of automation that require newer py versions.
> chore(productivity): Upgrade python to 3.8 on gen3-qa-worker

- kube/services/revproxy/gen3.nginx.conf/metadata-service.conf
- MDS: Do not restrict body size for mds
> fix: do not restrict body size for mds

- files/squid_whitelist/web_wildcard_whitelist
* Adding `.data-commons.org` and `.va.data-commons.org` to squid proxy whitelist.
> feat: adding data-commons.org to squid

- gen3/bin/save-failed-pod-logs.sh
* `save-failed-pod-logs` now will save both `initContainer` and `container` logs for specific pod
> feat(save-logs): save logs of all containers in pod

- files/scripts/jenkins-cronjob.sh
Added jenkins-ci cleanup to jenkins cronjob
> feat(jenkins-ci-cronjob): Added jenkins-ci cleanup to cronjob

- gen3/bin/save-failed-pod-logs.sh
> fix(save-logs): fix variable in loop

- Docker/Jenkins-CI-Worker/Dockerfile
> fix(jenkins-ci-worker): Fix py3 symlink

- Jenkinsfile
- gen3/lib/g3k.sh
- gen3/test/bootstrapTest.sh
- gen3/test/ec2Test.sh
- gen3/test/fenceStuffTest.sh
Migrating to proper Jenkins Pipeline DSL syntax and adding Kubernetes agent to run PR checks in ephemeral ci pods.
> chore(better-ci): Adopt gen3-qa-in-a-box

- kube/services/revproxy/gen3.nginx.conf/fence-service.conf
This is similar to [PR](https://github.com/uc-cdis/cloud-automation/pull/1580/files)
Updated endpoint from /register-user to /register
> Exclude Fence register blueprint from CSRF check

- kube/services/jobs/README.md
- kube/services/jobs/metadata-aggregate-sync-job.yaml
Jira Ticket: [HP-287](https://ctds-planx.atlassian.net/browse/HP-287)
* gen3 job for syncing aggregate metadata to a metadata service
> feat(agg-mds-job): add new agg mds job

- kube/services/thor/thor-deploy.yaml
Mounting .env file containing the database credentials.
> chore(thor): Load Thor database credentials into thor pod

- gen3/bin/gen3qa-run.sh
> fix(gen3qa-check-bucket-access): Increase number of attempts and wait longer for pod to come up

- kube/services/qabot/qabot-deploy.yaml
> chore(qa-bot): Add jira token to secrets

- kube/services/netpolicy/gen3/services/revproxy_netpolicy.yaml
Updated revproxy_netpolicy.yaml to allow ingress traffic for ohdsi-atlas
> added ingress for ohdsi-atlas

- gen3/bin/save-failed-pod-logs.sh
* All Kubernetes events will be sorted now
> chore(better-k8s-reset-debug): order kubernetes events by time

- Docker/python-nginx/python3.6-buster/dockerrun.sh
Bug Fix: python nginx buster; change `echo -e` to `printf` for portability
> Replace echo -e with printf

- kube/services/revproxy/gen3.nginx.conf/arborist-service.conf
- More documentation around Arborist nginx configuration for access to its API
> docs(arborist): important clarification/warning about expose more of Arborist's API

- kube/services/mariner/mariner-nfs-pv.yaml
Jira Ticket: [PXP-9049](https://ctds-planx.atlassian.net/browse/PXP-9049)
Using new manifest values for aws gateway
> using prod manifest values aws gateway

- flavors/squid_auto/healthcheck.sh
- flavors/squid_auto/squid_running_on_docker.sh
- flavors/squid_auto/squid_running_on_instance.sh
- flavors/squid_auto/squidvm.sh
- tf_files/aws/commons/cloud.tf
- tf_files/aws/modules/squid_auto/cloud.tf
- tf_files/aws/modules/squid_auto/variables.tf
- tf_files/aws/modules/vpc/cloud.tf
- tf_files/aws/modules/vpc/variables.tf
- tf_files/aws/squid_auto/root.tf
- tf_files/aws/squid_auto/variables.tf
Added healthcheck script/cronjob for squid autohealing
> feat(squid-autohealing): Added healthcheck script/cronjob for squid

- files/squid_whitelist/web_whitelist
adding charts.bitnami.com to whitelist
> whitelist charts.bitnami.com

- tf_files/aws/modules/eks/cloud.tf
- tf_files/aws/modules/eks/variables.tf
- tf_files/aws/modules/squid/cloud.tf
- tf_files/aws/modules/squid/variables.tf
A couple of external PR's related to generalizing our terraform and availability zones.
> Address external PR's

- kube/services/revproxy/gen3.nginx.conf/arborist-service.conf
Jira Ticket: [PXP-9024](https://ctds-planx.atlassian.net/browse/PXP-9024)
- Expose Arborist's "/policy" endpoint for users with access
> PXP-9024 Expose Arborist /policy endpoint

- kube/services/jobs/replicate-validation-job.yaml
Jira Ticket: [PXP-5168](https://ctds-planx.atlassian.net/browse/PXP-5168)
Add FORCE_CREATE_MANIFEST var to env section of yaml file, additional pr to finish task from https://github.com/uc-cdis/cloud-automation/pull/1793
> (PXP-5168): Add FORCE_CREATE_MANIFEST param to env

- gen3/bin/gitops.sh
Jira Ticket: [COV-1047](https://occ-data.atlassian.net/browse/COV-1047)
Adding cronjob version check to the `gitops-sync` function
> chore: adding cronjob version check to gitops-sync

- kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
- kube/services/revproxy/gen3.nginx.conf/fence-service-ga4gh.conf
- kube/services/revproxy/gen3.nginx.conf/fence-service.conf
Increase timeouts for Presigned URL Fence pod to 60s.
> Increase timeouts for Presigned URL Fence pod to 60s.

- files/squid_whitelist/web_wildcard_whitelist
Add data commons listed below to whitelist to allow dataguid.org to access
https://github.com/uc-cdis/cdis-manifest/blob/master/dataguids.org/manifest.json#L89-#L104
> Add 3 data commons to whitelist

- Docker/Jenkins-CI-Worker/Dockerfile
invalidated the quay build cache
> invalidated the quay build cache

- kube/services/wts/wts-deploy.yaml
- add necessary deployment env vars for datadog to WTS
> feat(datadog): add necessary deployment env vars for datadog to WTS

- gen3/bin/db.sh
- tf_files/aws/encrypted-rds/kube.tf
- tf_files/aws/encrypted-rds/variables.tf
> fix(psql13-script): Updated the psql upgrade script

- gen3/bin/db.sh
> fix(psqlupgrade-script): Updated the psql upgrade script

- gen3/bin/gitops.sh
Jira Ticket: [GPE-60](https://ctds-planx.atlassian.net/browse/GPE-60)
Automate rolling after public Fence config update
> feat: Automate rolling after public Fence config update

- gen3/bin/kube-setup-argo-wrapper.sh
- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
- kube/services/argo-wrapper/argo-wrapper-service.yaml
- kube/services/revproxy/gen3.nginx.conf/argo-wrapper-service.conf
Jira Ticket: [PXP-9193](https://ctds-planx.atlassian.net/browse/PXP-9193)
- add argo-wrapper deployment as part of cloud automation
we will now be deploying a new service called argo-wrapper
> feat add argo-wrapper deployment

- kube/services/frontend-framework/frontend-framework-deploy.yaml
related https://github.com/uc-cdis/gen3-frontend-framework/pull/13
- Update `gen3ff` deployment script
> fix gen3ff deploy

- gen3/bin/kube-roll-all.sh
- Add `frontend-framework` to `roll all` cmd
> fix: add gen3ff to roll all

- tf_files/aws/modules/eks-nodepool/cloud.tf
Add IAM policy for amazon SSM agent.
> Add SSM agent IAM policies

- files/scripts/jenkins-cronjob.sh
not the entire workspace directory
> delete only folders more than 5 days old

- gen3/bin/kube-setup-datadog.sh
- kube/services/datadog/values.yaml
Fixed orchestration monitoring
> fix(datadog-config): Enabled orchestration monitoring

- apis_configs/indexd_settings.py
- gen3/bin/kube-setup-wts.sh
- kube/services/wts/wts-deploy.yaml
Jira Ticket: [PXP-9499](https://ctds-planx.atlassian.net/browse/PXP-9499)
for https://github.com/uc-cdis/workspace-token-service/pull/40
- WTS init container: add SECRET_CONFIG so the DB migrations have access to the configuration
> PXP-9499 WTS init container: add SECRET_CONFIG

- flavors/eks/bootstrap-with-security-updates.sh
Fixed syntax error preventing sshd from starting.
> fix(bootstrap-sshconfig): Fixed syntax error preventing sshd startup

- kube/services/jobs/covid19-notebook-etl-job.yaml
- covid19-notebok-etl job: do not overwrite the startup commands
> covid19-notebok-etl job: do not overwrite the startup commands

- kube/services/argo-wrapper/argo-wrapper-service.yaml
Jira Ticket: [PXP-9539](https://ctds-planx.atlassian.net/browse/PXP-9539)]
change service app from argo to argo-wrapper
> fix argo wrapper service app selector

- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
update argo wrapper deployment to have netnolimit
> add netnolimits to argo wrapper

- kube/services/influxdb/influxdb-deployment.yaml
> influxdb - fix max_series_per_database limitation

- tf_files/aws/commons/cloud.tf
- tf_files/aws/modules/s3-bucket/cloud.tf
- tf_files/aws/modules/s3-logs/cloud.tf
- tf_files/aws/sftp/cloud.tf
> fix(tf-dependencies): Pinned provider version

- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
- kube/services/revproxy/revproxy-deploy.yaml
- GPE-293
- Expose argo-wrapper via revproxy
> Fix revproxy to argo-wrapper (GPE-293)

- files/scripts/fips-enable.sh
- files/scripts/psql-fips-fix.sh
- kube/services/jobs/psql-fix-job.yaml
- tf_files/aws/commons/kube.tf
- tf_files/aws/encrypted-rds/kube.tf
Added scripts for enabling FIPs on adminvms
> feat(fips-script): Added scripts for enabling FIPs on adminvms

- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
Jira Ticket: [PXP-9566](https://ctds-planx.atlassian.net/browse/PXP-9566)
add new config.json for argo-wrapper
> add argo-config

- kube/services/datadog/values.yaml
Enable DataDog network monitoring
> Enable DataDog network monitoring

- files/squid_whitelist/web_whitelist
- files/squid_whitelist/web_wildcard_whitelist
Add `.immport.org` to Squid whitelist
> Add .immport.org to Squid whitelist

- flavors/eks/bootstrap-explicit-proxy-docker.sh
- flavors/eks/bootstrap-with-security-updates.sh
- flavors/eks/bootstrap.sh
Added taints to workflow nodes
> fix(workflow-taints): Added taints to workflow nodes

- files/squid_whitelist/web_whitelist
- files/squid_whitelist/web_wildcard_whitelist
- us-central1-docker.pkg.dev
- *.paloaltonetworks.com
> Update squid whitelist

- kube/services/cohort-middleware/cohort-middleware-deploy.yaml
* Increase memory resources for cohort-middleware to 4Gi
> feat(cohort-middleware): increase resources

- kube/services/jenkins-worker/jenkins-worker-deployment.yaml
> Add DD_AGENT_HOST env var

- gen3/bin/kube-setup-dicom-server.sh
Updated IndexConnectionsCount in dicom-server
> updated indexConnectionsCount in dicom-server

- kube/services/cohort-middleware/cohort-middleware-deploy.yaml
- kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
* networkpolicies for cohort-middleware
* networkpolicies for Atlas/WebAPI
> feat: VA's networkpolicies

- files/squid_whitelist/web_whitelist
Jira Ticket: [PXP-9812](https://ctds-planx.atlassian.net/browse/PXP-9812)
* allows apache.github.io in squid
> feat: allows apache.github.io in squid proxy

- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
Jira Ticket:  none 
spacing issues in argo deploy yaml
> fix spacing issues in argo-wrapper deploy

- kube/services/argo/values.yaml
add label selector and days to persist record to argo engine archive
> fix add missing configs to argo archieve db

- files/squid_whitelist/web_whitelist
> feat(whitelist-kubecost): Whitelisted kubecost repo

- .secrets.baseline
- Docker/Jenkins-Worker/Dockerfile
- kube/services/jenkins2-worker/jenkins2-agent-service.yaml
- kube/services/jenkins2-worker/jenkins2-worker-deploy.yaml
Add xk6-browser to jenkins2 worker
Add deployment file for jenkins-worker on jenkins2
> install xk6-browser and add jenkins2 deployment

- files/scripts/ci-env-pool-reset.sh
> add jenkins-perf to CI pool

- gen3/bin/db.sh
- gen3/bin/reset.sh
Drop connections to DB before dropping it
> Drop connections to DB before dropping it

- kube/services/dicom-server/dicom-server-deploy.yaml
- DICOM server: add readinessProbe and livenessProbe
> dicom-server readinessProbe and livenessProbe

- kube/services/dicom-server/dicom-server-deploy.yaml
relates to https://github.com/uc-cdis/OrthancDocker/pull/6
> Fix DICOM server probes

- gen3/bin/kube-setup-workvm.sh
Reverts uc-cdis/cloud-automation#1874
> Revert "fix: install kubectl"

- kube/services/dicom-viewer/dicom-viewer-deploy.yaml
- DICOM viewer: add readinessProbe and livenessProbe
> dicom-viewer readinessProbe and livenessProbe

- gen3/bin/kube-setup-fluentd.sh
- kube/services/fluentd/fluentd.yaml
Allow deployment of fluentd outside of us-east-1
depends on: https://github.com/uc-cdis/cloud-automation/pull/1966
> Allow deployment of fluentd outside of us-east-1

- kube/services/jobs/metadata-aggregate-sync-job.yaml
> fix command

- kube/services/jobs/metadata-aggregate-sync-job.yaml
> switch from bash to sh

- kube/services/kayako-wrapper/kayako-wrapper-deploy.yaml
- fix secret mounts for kayako
> fix: secret mount

- doc/kube-setup-cedar-wrapper.md
- doc/kube-setup-kayako-wrapper.md
- gen3/bin/kube-setup-cedar-wrapper.sh
- gen3/bin/kube-setup-kayako-wrapper.sh
- kube/services/cedar-wrapper/cedar-wrapper-deploy.yaml
- kube/services/kayako-wrapper/kayako-wrapper-deploy.yaml
- use `g3auto` to handle secrets mount for cedar and kayako wrapper services
> use g3auto secrets for cedar and kayako wrapper

- tf_files/aws/eks/root.tf
- tf_files/aws/eks/variables.tf
- tf_files/aws/modules/eks/cloud.tf
- tf_files/aws/modules/eks/variables.tf
Split the secondary subnet /16 into 4 /18 subnets
> feat(split-secondary-subnet): Split secondary subnet into 4 /18 subnets

- kube/services/jenkins/rolebinding-devops.yaml
Added a role binding to grant argo-gitops-sa permissions in the argo namespace.
> PXP-GPE-480

- kube/services/thor/thor-deploy.yaml
> pull branch in initContainer

- kube/services/thor/thor-deploy.yaml
> add env var to thor deploy

- tf_files/aws/commons/cloud.tf
- tf_files/aws/commons/variables.tf
- tf_files/aws/csoc_common_logging/root.tf
- tf_files/aws/csoc_common_logging/variables.tf
- tf_files/aws/modules/common-logging/README.md
- tf_files/aws/modules/common-logging/lambda_function.py
- tf_files/aws/modules/common-logging/logging.tf
- tf_files/aws/modules/common-logging/variables.tf
- tf_files/aws/modules/management-logs/logging.tf
- tf_files/aws/modules/vpc/cloud.tf
- tf_files/aws/modules/vpc/variables.tf
- Remove LogDNA 
- Make csoc logging optional
> GPE-475 - Remove or hide deprecated logging features

- Docker/awshelper/Dockerfile
- kube/services/jobs/cogwheel-register-client-job.yaml
- tf_files/aws/utility_vm/variables.tf
Updated the Dockerfile for awshelper to use Ubuntu 22.04 as the base image. We're going to let the automated tests run as a sanity check, then go from there.
> Updated Dockerfile

- files/scripts/tf-cleanup.sh
Added script to cleanup tf plugin dirs
> feat(tf-cleanup-script): Added script to clean up tf plugin dirs

- gen3/bin/netpolicy.sh
Jira Ticket: [GPE-569](https://ctds-planx.atlassian.net/browse/GPE-569)
Extract the IP address from dig command output from CNAME records and IP address.
> chore: filter IP adderss from dig output

- kube/services/revproxy/gen3.nginx.conf/arborist-service.conf
Jira Ticket: [PXP-10229](https://ctds-planx.atlassian.net/browse/PXP-10229)
> PXP-10229 Update comment in Arborist nginx conf

- files/squid_whitelist/web_whitelist
> update squid web whitelist

- Docker/Jenkins-CI-Worker/Dockerfile
- Docker/Jenkins-Worker/Dockerfile
- Docker/Jenkins/Dockerfile
- Docker/Jenkins2/Dockerfile
Jira Ticket: [QAT-671](https://ctds-planx.atlassian.net/browse/QAT-671)
Update Jenkins versions
https://hub.docker.com/layers/jenkins/jenkins/2.375
https://hub.docker.com/layers/jenkins/jnlp-slave/4.13.3-1
> update jenkins versions

- Docker/Jenkins-CI-Worker/Dockerfile
- Docker/Jenkins-Worker/Dockerfile
- Docker/Jenkins/Dockerfile
Jira Ticket: [QAT-671](https://ctds-planx.atlassian.net/browse/QAT-671)
> use jdk11 images for jenkins workers

- .secrets.baseline
- kube/services/datadog/values.yaml
Please reference: https://docs.datadoghq.com/tracing/universal_service_monitoring/?tab=helm
> enabling USM for datadog

- kube/services/jobs/opencost-report-argo-job.yaml
Jira Ticket: [VADC-328](https://ctds-planx.atlassian.net/browse/VADC-328)
- Add addtional label to opencost report for workflows
> Add addtional label to opencost report

- Docker/jenkins/Jenkins-CI-Worker/Dockerfile
> use node 14 for CI

- gen3/bin/kube-roll-all.sh
* adding argo-wrapper, cohort-middleware and OHDSI tools (ohdsi-atlas and ohdsi-webapi) to roll all
> feat: add argo-wrapper, cohort-middleware and OHDSI tools to roll all

- gen3/lib/aws.sh
- tf_files/aws/eks/sample.tfvars
- tf_files/aws/eks/variables.tf
- tf_files/aws/modules/eks/variables.tf
Update the FIPS enabled AMI to the latest
> updating the fips AMI

- .secrets.baseline
- gen3/bin/kube-setup-workvm.sh
- package-lock.json
Jira Ticket: [GPE-684](https://ctds-planx.atlassian.net/browse/GPE-684)
- Simplify and fix bugs in kube-setup-workvm
- Add more logging, and make commands less verbose for easier troubleshooting
- Upgrade node.js on adminvms to v16
> Add fixes to kube-setup-workvm, and simplify the setup

- gen3/bin/reset.sh
> chore(fail-fast): Update gen3 reset to exit on error

- gen3/bin/reset.sh
Reverts uc-cdis/cloud-automation#2088
> Revert "chore(fail-fast): Update gen3 reset to exit on error"

- gen3/bin/kube-setup-argocd.sh
I was adding an annotation to the argocd namespace and I need it to be a label
> changing from an annotation to a label

- gen3/bin/kube-setup-datadog.sh
update datadog chart version to 3.6.4
> update datadog chart version to 3.6.4

- kube/services/jobs/opencost-report-argo-job.yaml
> chore(daily-reports): Updated reports to run daily

- kube/services/ohdsi-atlas/ohdsi-atlas-deploy.yaml
- kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
* improving resource management for OHDSI Atlas and WebAPI
* decreasing requests for nginx containers
* increasing limits for WebAPI container
> feat(ohdsi): update requests/limits for Atlas/WebAPI (descreasing requests and increasing limits due to OOM errors)

- gen3/bin/kube-setup-ingress.sh
- gen3/bin/waf-rules-GPE-312.json
Needed to update the file path for the waf-rules json file. 
I also needed to change the vpc_name to a variable so waf can be deployed in production environments.
> needed to update the file path for the waf-rules.

- gen3/bin/healthcheck.sh
Updated health check script to clear Evicted pods
> feat(healthcheck-clear-evicted): Updated health check script to clear Evicted pods

- gen3/bin/kube-setup-metrics.sh
- kube/services/metrics-server/components.yaml
Update metrics-server to version 0.6.2
> Update kubernetes metrics-server

- flavors/eks/bootstrap-explicit-proxy-docker.sh
- flavors/eks/bootstrap-with-security-updates.sh
- flavors/eks/bootstrap.sh
> Feat(cloud-init-fips): Set FIPs through cloud-init

- .github/workflows/image_build_push_squid.yaml
Added gh action for squid build so that squid could be built on arm
> feat(squid-on-arm): Added gh action for squid build so that squid could be built on arm

- gen3/bin/kube-setup-autoscaler.sh
- gen3/bin/kube-setup-system-services.sh
- kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
- kube/services/metrics-server/components.yaml
Updating the scripts, images, and clusterroles for Kubernetes system services to be compatible with EKS version 1.22
> Feat/eks 1.22

- .secrets.baseline
- gen3/bin/kube-setup-argo.sh
Setup argo buckets in every ns
> feat(argo-multi-ns): Setup argo buckets in every ns

- doc/karpenter.md
Added documentation for karpenter
> feat(karpenter-doc): Added documentation for karpenter

- files/scripts/ci-env-pool-reset.sh
> Updating the reset pool for jenkins-envs

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-autoscaler.sh
- gen3/bin/kube-setup-karpenter.sh
adding logic to only setup autoscaler/karpenter if it is run in the default namespace.
> default namespace logic

- gen3/bin/kube-setup-autoscaler.sh
- gen3/bin/kube-setup-karpenter.sh
Fixed a couple of bugs in kube-setup-karpenter
Added more logging to kube-setup-karpenter
> Add more logging to kube-setup-karpenter

- gen3/bin/kube-setup-prometheus.sh
- gen3/bin/kube-setup-revproxy.sh
- kube/services/revproxy/gen3.nginx.conf/grafana.conf
removing the logic to only grab the prometheus nginx config if in the default namespaces so we can access the prometheus endpoint in staging environments
> Prometheus Endpoint

- kube/services/argo/values.yaml
https://github.com/argoproj/argo-workflows/issues/10498 
Added connection pool with limits on connections as a workaround for now.
> Add connection pool to argo

- files/scripts/ci-env-pool-reset.sh
> Use jenkins-niaid for service PRs

- kube/services/portal/portal-deploy.yaml
- kube/services/portal/portal-root-deploy.yaml
> change resources for portal-deploy

- kube/services/datadog/values.yaml
- kube/services/jobs/usersync-job.yaml
Excluded some namespaces/containers from being ingested
> chore(datadog-exclusions): Excluded some namespaces/containers from being ingested

- files/scripts/ci-env-pool-reset.sh
Reverts uc-cdis/cloud-automation#2162
> Revert "Use jenkins-niaid for service PRs"

- kube/services/jobs/metadata-aggregate-sync-job.yaml
Jira Ticket: [HP-1062](https://ctds-planx.atlassian.net/browse/HP-1062)
* Add slack status messages to mds-agg-sync
[HP-1062]: https://ctds-planx.atlassian.net/browse/HP-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore/add slack status messages to mds-agg-sync

- files/scripts/healdata/heal-cedar-data-ingest.py
Jira Ticket: [HP-1077](https://ctds-planx.atlassian.net/browse/HP-1077)
updating cedar ingestion script to use the revproxy for getting information
[HP-1077]: https://ctds-planx.atlassian.net/browse/HP-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> cedar ingestion revproxy

- gen3/bin/kube-setup-karpenter.sh
> fix(karpenter): Removed hardcoded values

- kube/services/portal/portal-deploy.yaml
- kube/services/portal/portal-root-deploy.yaml
Increased portal requests to allow it to have enough resources to build and start
> chore(portal-requests): Upped portal requests to get around crashloops

- kube/services/jenkins-ci-worker/jenkins-ci-worker-deploy.yaml
> Set ephemeral-storage for jenkins-ci-worker

- kube/services/jenkins-ci-worker/jenkins-ci-worker-deploy.yaml
> increase ephemeral storage on jenkins-ci-worker

- kube/services/jobs/hatchery-reaper-job.yaml
- Add in more features to hatchery-reaper to reap workspaces
- Reap workspaces that are in paymodels that are above limit
> Update hatchery-reaper job

- gen3/lib/testData/default/expectedFenceResult.yaml
- gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
- kube/services/fence/fence-deploy.yaml
Fence pod requires more resources.
> increasing the requets and limits for Fence

- kube/services/spark/spark-deploy.yaml
[GPE-939](https://ctds-planx.atlassian.net/browse/GPE-939)
[GPE-939]: https://ctds-planx.atlassian.net/browse/GPE-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set resources for spark deployment

- kube/services/revproxy/gen3.nginx.conf/portal-as-root/portal-service.conf
Jira Ticket: [PPS-212](https://ctds-planx.atlassian.net/browse/PPS-212)
- add header to portal to prevent clickjacking
[PPS-212]: https://ctds-planx.atlassian.net/browse/PPS-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PPS-212): add header to portal to prevent clickjacking

- kube/services/datadog/values.yaml
re-enabling this container so I can test applying this with argocd per GPE-935
> enabling the system probe container for testing

- files/squid_whitelist/web_whitelist
- files/squid_whitelist/web_wildcard_whitelist
- Whitelist *.gen3.org (for helm and docs)
> Jawadqur patch 1

- gen3/bin/ecr.sh
Added containerd support for ECR commands
> fix(ecr-containerd): Added containerd support for ECR commands

- kube/services/netpolicy/gen3/services/datadog_netpolicy.yaml
adding datadog networkpolicy to fix Datadog tracer for cohort middleware
> adding datadog networkpolicy to fix Datadog tracer for cohort middleware

- files/scripts/ci-env-pool-reset.sh
> Add jenkins-new-1 to CI pool

- kube/services/jenkins-worker/jenkins-worker-deploy.yaml
[GQE-78](https://ctds-planx.atlassian.net/browse/GQE-78)
[GQE-78]: https://ctds-planx.atlassian.net/browse/GQE-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add containerd support for jenkins worker

- kube/services/kubecost/values.yaml
> chore(kubecost-prometheus): Lowered prometheus requests

- tf_files-1.0/aws/modules/aurora/main.tf
update aws_rds_cluster_parameter_group
> update rds cluster parameter_group

- kube/services/thor/thor-deploy.yaml
> Set AWS default region in Thor deployment

- kube/services/netpolicy/gen3/services/revproxy_netpolicy.yaml
- kube/services/revproxy/gen3.nginx.conf/kubecost-service.conf
Updated networkpolicy to work with kubecost
> fix(kubecost-netpolicy): Updated networkpolicy to work with kubecost

- gen3/bin/kube-setup-roles.sh
- kube/services/jenkins/rolebinding-devops.yaml
Added cluster role to gitops sync to let it view namespaces/services
> fix(gitops-clusterrole): Added cluster role to gitops sync to let it view namespaces/services

- gen3/bin/kube-setup-karpenter.sh
- kube/services/karpenter/provisionerWorkflow.yaml
Fixed security group tag and added label for workflow nodes
> fix(karpenter): Added a couple karpenter fixes for workflows

- gen3/bin/jupyter.sh
Jira Ticket: [BRH-519](https://ctds-planx.atlassian.net/browse/BRH-519)
After changing hatchery reaper job to run every 5 minutes, we noticed that the reaper job would sometimes reap workspaces that were in the process of being launched. 
Adding a grace period of 60m before reaping inactive workspaces. 
[BRH-519]: https://ctds-planx.atlassian.net/browse/BRH-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add a grace period for hatchery-reaper

- kube/services/jobs/distribute-licenses-job.yaml
Jira Ticket: [HP-1106](https://ctds-planx.atlassian.net/browse/HP-1106)
* Update name of secret for licenses for Gen3-licensed Stata workspace
[HP-1106]: https://ctds-planx.atlassian.net/browse/HP-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update stata license secret name.

- kube/services/argo/values.yaml
> Update values.yaml to fix a typo

- kube/services/manifestservice/manifestservice-deploy.yaml
added netpolicy to allow manifestservice to work
> fix(manifestservice-netpolicy): added netpolicy to allow manifestservice to work

- kube/services/datadog/values.yaml
> fix(pelican-log-ingestion): Remove pelican export log ingestion

- files/scripts/ci-env-pool-reset.sh
Jira Ticket: [GQE-38](https://ctds-planx.atlassian.net/browse/GQE-38)
[GQE-38]: https://ctds-planx.atlassian.net/browse/GQE-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add new new envs to CI pool

- .github/workflows/image_build_push_jenkins.yaml
- .secrets.baseline
- Docker/jenkins/Jenkins-CI-Worker/Dockerfile
- Docker/jenkins/Jenkins-Worker/Dockerfile
- Docker/jenkins/Jenkins/Dockerfile
- Docker/jenkins/Jenkins2/Dockerfile
Jira Ticket: [GQE-96](https://ctds-planx.atlassian.net/browse/GQE-96)
[GQE-96]: https://ctds-planx.atlassian.net/browse/GQE-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update jenkins to latest versions

- .secrets.baseline
- Docker/jenkins/Jenkins-CI-Worker/Dockerfile
- Docker/jenkins/Jenkins-Worker/Dockerfile
- Docker/jenkins/Jenkins/Dockerfile
- Docker/jenkins/Jenkins2/Dockerfile
> Add missing jenkins dependencies

- kube/services/revproxy/gen3.nginx.conf/gen3ff-as-root/frontend-framework-service.conf
- kube/services/revproxy/gen3.nginx.conf/gen3ff-as-root/portal-service.conf
- kube/services/revproxy/gen3.nginx.conf/portal-as-root/frontend-framework-service.conf
Covering a few extra files to prevent clickjacking attacks and make pages non-frameable.
> Covering a few extra cases for preventing clickjacking attacks.

- .secrets.baseline
- Docker/jenkins/Jenkins-CI-Worker/Dockerfile
Jira Ticket: [GQE-102](https://ctds-planx.atlassian.net/browse/GQE-102)
[GQE-102]: https://ctds-planx.atlassian.net/browse/GQE-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> install go binary in jenkins CI worker

- gen3/bin/kube-setup-wts.sh
Updated kube-setup-wts to include new field
> chore(wts-script): Updated kube-setup script to include new field

- kube/services/argo/values.yaml
Jira Ticket: [VADC-584](https://ctds-planx.atlassian.net/browse/VADC-584)
* Increase argo workflow parallelism to 5
[VADC-584]: https://ctds-planx.atlassian.net/browse/VADC-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VADC-584: Increase argo worflow parallelism to 5

- kube/services/argo-events/workflows/configmap.yaml
* Reverting kubelet config change
> Revert kubelet config change

- Docker/jenkins/Jenkins-Worker/Dockerfile
Jira Ticket: [GQE-118](https://ctds-planx.atlassian.net/browse/GQE-118)
[GQE-118]: https://ctds-planx.atlassian.net/browse/GQE-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add k6 to jenkins-worker

- gen3/bin/kube-roll-all.sh
Updated kube-roll-all to not deploy cohort middleware twice and swapped order to fix dependency issues
> fix(cohort-deploy-logic): Updated kube-roll-all to not deploy cohort middleware twice and swapped order to fix dependency issues

- kube/services/argo-events/workflows/configmap.yaml
- kube/services/karpenter/nodeTemplateDefault.yaml
- kube/services/karpenter/nodeTemplateGPU.yaml
- kube/services/karpenter/nodeTemplateJupyter.yaml
- kube/services/karpenter/nodeTemplateWorkflow.yaml
Removed the -xe flag, and unauthorized calls to set tags. Also removed registryPullQPS limits for karpenter templates
> Karpenter userdata cleanup

- files/scripts/healdata/heal-cedar-data-ingest.py
Updating filters to pull in research program to `advSearchFilters`
> [HP-1170] updating heal cedar filter for research programs

- kube/services/ingress/ingress.yaml
GPE-1051 
GPE-1050
- Update sslpolicy to only allow tls1.3 in alb
> Update sslpolicy to tls 1.3 in ingress/alb

- .secrets.baseline
- kube/services/datadog/datadog-application.yaml
- kube/services/datadog/values.yaml
- Moving datadog to govcloud site.
> Move DD to govcloud

- gen3/bin/kube-setup-fluentd.sh
- kube/services/fluentd/gen3-1.15.3.conf
Updated fluentd to work with cri parser plugin
> fix(fluentd): Fixed fluentd logging to work with new cri parser format

- files/squid_whitelist/web_wildcard_whitelist
update squid whitelist for chordshealth
> update squid whitelist for chordshealth

- kube/services/argo-events/workflows/configmap.yaml
> Added node emptiness timer

- kube/services/argo-events/workflows/configmap.yaml
Updated instance types to latest/greatest and removed consolidation
> Updated instance types to latest/greatest and removed consolidation

- files/scripts/healdata/heal-cedar-data-ingest.py
- kube/services/jobs/cedar-ingestion-job.yaml
Jira Ticket: [HP-1244](https://ctds-planx.atlassian.net/browse/HP-1244)
* CEDAR ingest job will get parameters from g3auto secrets so that it can be run as cron job.
* update CEDAR ingest script to use client-credentials instead of `username`.
[HP-1244]: https://ctds-planx.atlassian.net/browse/HP-1244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HP-1244 Chore/create cron job for cedar

- Docker/jenkins/Jenkins-CI-Worker/Dockerfile
Relevant code: https://github.com/uc-cdis/data-simulator/blob/ee70e70/datasimulator/generator.py#L23-L30
> Jenkins add "/usr/share/dict/words"

- gen3/bin/kube-setup-dicom.sh
- kube/services/ohif-viewer/app-config.js
* add app-config.js needed for OHIF Viewer with backward compatible configuration to support old and new Orthanc server based on if new Orthanc is deployed in the manifest
> feat: add app-config.js for ohif-viewer

- gen3/bin/gitops.sh
- Add a log to Slack when the `gitops-sync` job initially detects changes and is about to deploy them
> Add log when gitops-sync initially detects changes

- files/scripts/ci-env-pool-reset.sh
> Quarantine jenkins-dcp until migration to ES7

- gen3/bin/kube-setup-jenkins2.sh
- kube/services/jenkins2/jenkins2-deploy.yaml
> add kube-setup-jenkins2 script

- kube/services/karpenter-reconciler/application.yaml
> Update application.yaml to change some instances of 'argo-events' to 'default'

- files/scripts/healdata/heal-cedar-data-ingest.py
- Skip `Gender` tags for HEAL Cedar ingestion script
> skip gender tags

- kube/services/revproxy/gen3.nginx.conf/guppy-service.conf
This patch was causing some issues the explorer page loading properly. Reverting the change for now!
> reverting guppy nginx config change

- Docker/jenkins/Jenkins/Dockerfile
> Upgrade jenkins

- files/squid_whitelist/web_whitelist
add elastic.co so we can use elasticsearch helm chart
> Update web_whitelist (add elastic.co)

- kube/services/argo/values.yaml
> This was still set to 5 for some reason

- Docker/jenkins/Jenkins/Dockerfile
- Docker/jenkins/Jenkins2/Dockerfile
Jira Ticket: [GPE-1221](https://ctds-planx.atlassian.net/browse/GPE-1221)
[GPE-1221]: https://ctds-planx.atlassian.net/browse/GPE-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update jenkins version

- files/scripts/healdata/heal-cedar-data-ingest.py
Jira Ticket: [HP-1333](https://ctds-planx.atlassian.net/browse/HP-1333)
- Update HEAL CEDAR ingestion script to adapt for CEDAR schema v0.05
[HP-1333]: https://ctds-planx.atlassian.net/browse/HP-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HP-1333 update script

- flavors/squid_auto/squid_running_on_docker.sh
Check and restart squid more often to ensure it comes up healthy at startup
> chore(squid-al23): Updated squid bootstrap script to work with al23

- files/squid_whitelist/web_wildcard_whitelist
> chore(tigera-helm): Updated squid to support calico chart repo

- gen3/bin/kube-setup-ingress.sh
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692
> fix(alb-policy): policy fix

- gen3/bin/kube-roll-all.sh
- gen3/bin/kube-setup-system-services.sh
Removed dns autoscaler deployment
> chore(remove-coredns-autoscaler): Removed dns autoscaler deployment

- flavors/squid_auto/squid_running_on_docker.sh
> fix(squid-cron): Added crontab to al23 squid

- flavors/squid_auto/squid_running_on_docker.sh
> fix syntax

- flavors/squid_auto/squid_running_on_docker.sh
> prevent reboot

- gen3/bin/kube-setup-argo.sh
- kube/services/argo/values.yaml
> Lowering parallelism to 1 for VA workflows

- kube/services/argo/values.yaml
* Increases VA prod parallel workflows to 3
> Increases VA prod parallel workflows to 3

- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
* fix mountpath, new argo-wrapper Docker images uses `/argowrapper` folder, not `/src`
> feat(argo-wrapper): update mountpath

- kube/services/argo-wrapper/config.ini
> fix(argo-wrapper): fix typo

- kube/services/jobs/etl-job.yaml
> Prevent eviction of ETL job pod while running

- kube/services/jenkins/jenkins-deploy.yaml
> fix(jenkins-zone): Added zone

- .secrets.baseline
- files/scripts/healdata/heal-cedar-data-ingest.py
just another fix for cedar ingestion
> fix missed import

- files/scripts/ci-env-pool-reset.sh
> Add jenkins-dcp to the env pool reset script

- .secrets.baseline
- Jenkinsfile
> Raising requests for Jenkins pods

- gen3/bin/dbbackup.sh
- kube/services/jobs/psql-db-dump-va-testing-job.yaml
> Creating a new type of DB dump that grabs stuff for va-testing

- files/squid_whitelist/web_whitelist
Adding External QDR Repository for HEAL project to whitelist
> add whitelist for qdr staging

- files/squid_whitelist/web_whitelist
> Adding awslabs.github.io to the squid whitelist

- kube/services/node-monitors/fenceshib-jenkins-test.yaml
adding a cron to check qaplanetv1 for the fenceshib service since it can break revproxy/automation
> Adding in a cronjob to check if fenceshib service exists in jenkins environments

- kube/services/argo-events/workflows/configmap.yaml
Link to JIRA ticket if there is one: [VADC-1083](https://ctds-planx.atlassian.net/browse/VADC-1083)
* add 7th generation instances for workflows
* add 24xlarge for compute steps
[VADC-1083]: https://ctds-planx.atlassian.net/browse/VADC-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update instance types with newer generation

- kube/services/karpenter-reconciler/karpenter-reconciler-cronjob-va-testing.yaml
> Let's get the va-testing reconciler onto master

- files/scripts/healdata/heal-cedar-data-ingest.py
JIRA ticket: [HP-1470](https://ctds-planx.atlassian.net/browse/HP-1470)
* CEDAR ingest job will query mds and match CEDAR data on instance_id instead of nih_application_id
[HP-1470]: https://ctds-planx.atlassian.net/browse/HP-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HP-1470 Use cedar instance id for mds

- kube/services/jobs/metadata-aggregate-sync-job.yaml
- kube/services/metadata/metadata-deploy.yaml
- pass `AGG_MDS_DEFAULT_DATA_DICT_FIELD` to MDS as env var
> pass AGG_MDS_DEFAULT_DATA_DICT_FIELD to mds

- gen3/bin/kube-setup-karpenter.sh
Upgraded karpenter version support in kube-setup-karpenter
> feat(karpenter-upgrade): Upgraded karpenter version support in kube-setup-karpenter

- files/openvpn_management_scripts/create_ovpn.sh
- files/openvpn_management_scripts/create_seperated_vpn_zip.sh
- files/openvpn_management_scripts/create_vpn_user.sh
- files/openvpn_management_scripts/install_ovpn.sh
- files/openvpn_management_scripts/reset_totp_token.sh
- files/openvpn_management_scripts/revoke_user.sh
- files/openvpn_management_scripts/send_email.sh
- files/openvpn_management_scripts/templates/network_tweaks.sh.template
- files/openvpn_management_scripts/templates/openvpn.conf.template
- files/openvpn_management_scripts/templates/settings.sh.template
- files/openvpn_management_scripts/templates/vars.template
- flavors/vpn_nlb_central/vpnvm_new.sh
- flavors/vpn_nlb_central/vpnvm_ubuntu20.sh
- Upgrade OpenVPN to latest
- Edit scripts with the ability to run on FIPS'd Amazon Linux 2 nodes
- Use easyrsa3 to build certificates
-
> OpenVPN Updates

- tf_files/aws/nextflow_ami_pipeline/data.tf
- tf_files/aws/nextflow_ami_pipeline/iam.tf
- tf_files/aws/nextflow_ami_pipeline/imagebuilder.tf
- tf_files/aws/nextflow_ami_pipeline/manifest.json
- tf_files/aws/nextflow_ami_pipeline/root.tf
- tf_files/aws/nextflow_ami_pipeline/sample.tfvars
- tf_files/aws/nextflow_ami_pipeline/variables.tf
Jira Ticket: [BRH-652](https://ctds-planx.atlassian.net/browse/BRH-562)
- Image Builder Pipeline for Nextflow FIPS enabled AMI's
[BRH-652]: https://ctds-planx.atlassian.net/browse/BRH-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Nextflow AMI pipeline

- gen3/bin/kube-setup-access-backend.sh
- better default user.yaml for access-backend
> fix(access-backend): better default user.yaml

- gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
> fix(tests): Fixed jenkins tests

- gen3/bin/ecr.sh
> Add csoc to ECR

- kube/services/argo-events/workflows/configmap.yaml
Link to JIRA ticket if there is one: N/A
* adding [r7iz](https://aws.amazon.com/ec2/instance-types/r7iz/) nodes to workflows for GWAS, related to https://github.com/uc-cdis/vadc-genesis-cwl/pull/77.
> feat: adding r7iz nodes to workflows

- gen3/bin/kube-setup-argo.sh
- https://ctds-planx.atlassian.net/browse/GPE-1284
Updated kube-setup-argo.sh to create a ClusterRole with specific permissions for Argo resources and bind it across multiple namespaces for enhanced security.
> update argo role

- files/scripts/healdata/heal-cedar-data-ingest.py
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-1562
- HEAL CEDAR ingestion: fixed a bug causing platform citation texts disappear
- HEAL CEDAR ingestion: fixed a bug causing some repository citation texts to be incorrect
> HP-1562 Fix/citation

- kube/services/argo-events/workflows/configmap.yaml
> Raising workflow provisioner limits

- files/scripts/ecr-access-job.md
- gen3/bin/kube-setup-hatchery.sh
- Add access Hatchery was missing to launch Nextflow workspaces in blanket billing mode
> Add hatchery access

- .pre-commit-config.yaml
- .secrets.baseline
- Docker/jenkins/Jenkins-CI-Worker/Dockerfile
- Docker/jenkins/Jenkins-CI-Worker/install-python3.8.sh
- Docker/jenkins/Jenkins-CI-Worker/install-python3.9.sh
- Docker/jenkins/Jenkins/Dockerfile
- Docker/jenkins/Jenkins/install-python3.8.sh
- Docker/jenkins/Jenkins/install-python3.9.sh
- Docker/jenkins/Jenkins2/Dockerfile
- Docker/jenkins/Jenkins2/install-python3.8.sh
- Docker/jenkins/Jenkins2/install-python3.9.sh
> Update python to 3.9 in jenkins pods

- gen3/bin/kube-setup-aws-es-proxy.sh
Updated es-proxy script to allow for setting es domain
> feat(set-es-domain): Updated es-proxy script to allow for setting es domain

- kube/services/cedar-wrapper/cedar-wrapper-deploy.yaml
JIRA ticket: [HP-1598](https://ctds-planx.atlassian.net/browse/HP-1598)
* enable datadog logging for cedar-wrapper-service
[HP-1598]: https://ctds-planx.atlassian.net/browse/HP-1598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (HP-1598): enable datadog in cedar-wrapper deployment

- files/openvpn_management_scripts/install_ovpn.sh
- flavors/vpn_nlb_central/vpnvm.sh
- flavors/vpn_nlb_central/vpnvm_new.sh
- flavors/vpn_nlb_central/vpnvm_ubuntu18.sh
update all support emails from <whatever-support>@datacommons.io to <whatever-support>@gen3.org
--do not merge until gen3.org emails are active.-- the emails are active now, so it can be merged whenever ready
> Update support emails from @datacommons.io to @gen3.org

- .secrets.baseline
- gen3/lib/g3k_manifest.sh
- kube/services/ambassador/ambassador-deploy.yaml
- kube/services/arborist/arborist-deploy.yaml
- kube/services/argo-wrapper/argo-wrapper-deploy.yaml
- kube/services/audit-service/audit-service-deploy.yaml
- kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml
- kube/services/dicom-server/dicom-server-deploy.yaml
- kube/services/dicom-viewer/dicom-viewer-deploy.yaml
- kube/services/fence/fence-deploy.yaml
- kube/services/frontend-framework/frontend-framework-deploy.yaml
- kube/services/guppy/guppy-deploy.yaml
- kube/services/hatchery/hatchery-deploy.yaml
- kube/services/indexd/indexd-deploy.yaml
- kube/services/manifestservice/manifestservice-deploy.yaml
- kube/services/metadata/metadata-deploy.yaml
- kube/services/peregrine/peregrine-deploy.yaml
- kube/services/portal/portal-deploy.yaml
- kube/services/requestor/requestor-deploy.yaml
- kube/services/revproxy/revproxy-deploy.yaml
- kube/services/sheepdog/sheepdog-deploy.yaml
- kube/services/sower/sower-deploy.yaml
- kube/services/ssjdispatcher/ssjdispatcher-deploy.yaml
- kube/services/wts/wts-deploy.yaml
adding a "hostname" label to help with monitoring organization.
> adding "hostname" label to our services

- files/squid_whitelist/web_whitelist
> update web whitelist

- kube/services/portal/portal-deploy.yaml
- kube/services/portal/portal-root-deploy.yaml
- Remove DD RUM related values from deployment
> disable dd rum

- kube/services/jobs/psql-db-backup-encrypt-job.yaml
Add alerts to postgresql backup job
> add alerts to psql encrypted backup job

- kube/services/jobs/psql-db-backup-encrypt-job.yaml
Add an option to skip a database from backup
> add skip database option

- kube/services/jobs/graph-create-job.yaml
- kube/services/jobs/indexd-authz-job.yaml
- kube/services/jobs/indexd-single-table-migration-job.yaml
- kube/services/jobs/metadata-aggregate-sync-job.yaml
adding updates so these jobs will work with our new AL based environments that use poetry to manage their virtual environments.
> Adding "poetry run" 

- gen3/bin/kube-setup-gen3-user-data-library.sh
- Allow gen3-user-data-library to setup database in jenkins environment.
> Allow setup in jenkins

- .pre-commit-config.yaml
- kube/services/spark/spark-deploy.yaml
Remove unused lines in `spark-deploy.yaml`
> Remove unused lines in `spark-deploy.yaml`

- files/squid_whitelist/web_whitelist
> Adding fluent helm repo to Squid whitelist

- files/squid_whitelist/web_wildcard_whitelist
> add cancerimagingarchive.net to squid

- kube/services/portal/portal-deploy.yaml
- kube/services/portal/portal-root-deploy.yaml
Reverts uc-cdis/cloud-automation#2632
> Revert "disable dd rum"

- .secrets.baseline
- kube/services/access-backend/access-backend-deploy.yaml
> Add health probes to access-backend

- kube/services/arborist/arborist-deploy-2.yaml
> Add hostname label to arborist

- gen3/bin/kube-roll-all.sh
We need to conditionally roll Spark during "roll all" to ensure the image is updated.
> adding logic to roll spark during kube-roll-all

- gen3/bin/gitops.sh
Gitops sync currently does not reset all cronjobs causing cronjobs to utilize outdated images.
> modifying gitops sync to reset cronjobs

- .github/workflows/integration_tests.yaml
Link to JIRA ticket if there is one: [GQE-387](https://ctds-planx.atlassian.net/browse/GQE-387)
[GQE-387]: https://ctds-planx.atlassian.net/browse/GQE-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use CLOUD_AUTO_BRANCH for integration tests

- gen3/bin/mutate-guppy-config-for-ci-env.sh
Link to JIRA ticket if there is one: [GQE-403](https://ctds-planx.atlassian.net/browse/GQE-403)
[GQE-403]: https://ctds-planx.atlassian.net/browse/GQE-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Guppy Config Updater for CI Envs

- files/squid_whitelist/web_wildcard_whitelist
> Add wriwindber.org to squid whitelist

- .github/workflows/squid_whitelist_verify.yaml
- files/squid_whitelist/web_wildcard_whitelist
- Add a github action that quickly verifies squid rule changes using `quay.io/cdis/squid:master` image
> Add github action to verify squid whitelist changes. 

- gen3/bin/kube-setup-cluster-level-resources.sh
- kube/services/cluster-level-resources/app.yaml
> Modify script to use cluster-level-resources from gen3-helm

- kube/services/revproxy/nginx.conf
> Suppress health-check logging in Nginx access logs

- gen3/bin/kube-setup-aws-es-proxy.sh
- gen3/lib/utils.sh
updates the kube-setup-aws-es-proxy & lib/utils.sh to fix a jenkins job
[GPE-1935](https://ctds-planx.atlassian.net/browse/GPE-1935)
[GPE-1935]: https://ctds-planx.atlassian.net/browse/GPE-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update aws-es-proxy IRSA setup to fix Jenkins job

- .secrets.baseline
- kube/services/gen3-workflow/gen3-workflow-deploy.yaml
Link to JIRA ticket if there is one: [MIDRC-857](https://ctds-planx.atlassian.net/browse/MIDRC-857)
* Add prometheus metrics support to gen3-workflow
[MIDRC-857]: https://ctds-planx.atlassian.net/browse/MIDRC-857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add prometheus metrics support to gen3-workflow

- kube/services/indexd/indexd-deploy.yaml
- kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
- kube/services/portal/portal-deploy.yaml
- kube/services/portal/portal-root-deploy.yaml
- kube/services/requestor/requestor-deploy.yaml
- kube/services/wts/wts-deploy.yaml
> Removed cpu requests

- helm-migration-script/migrate-to-helm.py
> Enable sower-job g3auto secret in migration script

- helm-migration-script/migrate-to-helm.py
> Add mutatingWebhook configuration to output

- helm-migration-script/migrate-to-helm.py
> Of course the first time the script is run, we come across an error

- files/squid_whitelist/web_whitelist
- gen3/bin/kube-setup-argo-events.sh
> Add Cilium helm repo to squid whitelist
