uc-cdis/cloud-automation

kube/kubes.sh, kube/services/revproxy/00cert-config.yaml, kube/services/revproxy/10nginx-config.yaml, kube/services/revproxy/READMD.md, kube/services/revproxy/apply_cert, kube/services/revproxy/apply_service, kube/services/revproxy/revproxy-deploy.yaml, kube/services/revproxy/revproxy-service.yaml, tf_files/cloud.tf, tf_files/configs/kube-services.sh
resolve https://github.com/uc-cdis/cloud-automation/issues/8
- a revproxy service is created to substitute the external reverse proxy
- a public_kube subnet is added to put ELB in it, this is created to make sure that this subnet use the same availability zone as the private subnet that kubernete is using, otherwise it can't reach kubernete cluster
- this pr doesn't remove the deprecated external reverse proxy
- created a kubes.sh for some shortcuts
I spent sometime to try to figure out how to automate fixing ELB after kubernete set it up, but apparently I can't do most of what I want through awscli or python client, so I gave up and hope kubernete will fix them later.
r? @uc-cdis/planx-devs
=> Feat/loadbalancer - use ELB for exposing services

pack_and_terraform.bash, setup_kube.bash, tf_files/cloud.tf, tf_files/configs/cluster.yaml, tf_files/configs/kube-up.sh, tf_files/variables.template
resolve #55 
- removed NAT gateway
- moved tf_variables and tfstate to `~/.creds/{vpc_name}` so that I can use cloud-automation with different vpcs locally
- used envsubst instead of sed for tf_variables templating
- some minor fixes
tested in OCC with `pr65` vpc name :p
r? @zflamig
=> feat(proxy): use squid as NAT instance

Jenkins/Pipelines/Terraform/Jenkinsfile
Reset Jenkins 'Terraform' job to just checkout Jenkinsfile
from the same repo/branch that the Jenkins job is configured
to point at
I had the Pipeline script inline in the Jenkins script before ... show you what I mean next week
=> fix(Jenkinsfile): Terraform pipeline checkout scm

pack_and_terraform_aws.bash
Just a few things I noticed running through this if it's useful:
The template vars were uppercase and the script was lowercase,
changed all to uppercase.
Exited right after if didn't say y to cert instead of puzzling
over why asked to put in domainname.
=> fix(automate): capitalization and order

kube/services/revproxy/00nginx-config.yaml, tf_files/aws/variables.tf
Patch revproxy nginx config to:
* copy access_token head to Authorization header
* CSRF check on POST requests
Note - this is currently based on the feat/sheepdog_deployment branch - will rebase after PR #134 is merged.
Note - the CSRF check kicks in on all POST requests, so non-web clients (Francisco's python library, whatever) will have to fake it by adding an x-csrf-token header and a csrftoken cookie that equal each other ...
Or ... we could disable the check if:
* user-agent header is set to something like 'script'
* csrftoken cookie is not set
resolves #132
=> WIP: Chore/cookies

kube/services/revproxy/00nginx-config.yaml
add another conditional to nginx to disable csrf check
when not required - deal with case where
empty cookie equals empty header
=> fix(csrf): add another csrf check to nginx

kube/services/jenkins/apply_service.sh, kube/services/revproxy/apply_service, tf_files/aws/kube.tf, tf_files/aws/outputs.tf
should be able to bootstrap a VPC without
specifying the TLS ARN
=> fix(tls-arn): do not require tls arn for VPC

gen3/bin/kube-roll-all.sh
netpolices applied while deploying the cluster impede them from coming up. On hold for further testing.
=> fix(kube-roll-all.sh): net policies on hold as for now

kube/services/fluentd/fluentd.yaml
This should solve the issue we've been experiencing lately about a few logs being missing for unknown reasons.
=> fix(fluentd.yaml): new and updated image to be used

gen3/bin/kube-roll-all.sh
sometimes kube-wait4-pods times out - don't fail
=> fix(kube-roll-all): do not fail on kube-wait4-pods

files/openvpn_management_scripts/templates/network_tweaks.sh.template, tf_files/aws/modules/vpn_nlb_central_csoc/README.md, tf_files/aws/modules/vpn_nlb_central_csoc/cloud.tf
After changing the flavor of the openvpn server  from `t2.medium` to `m5.xlarge` ,  vpn broke.  In the openvpn config files the VM interface were hardcoded, which led to the creation of wrong iptables rules. Generalising the Vm interface fixed the issue.
=> Changing the vpn server VM ; break the vpn set-up

gen3/bin/gitops.sh
Fixes a quoted value in the manifest-to-configmap setup which allows for whitespace (or generally, more sophisticated types) in the manifest, for supporting arrays etc.
Example command executed by `g3k_gitops_configmaps`:
```
g3kubectl create configmap manifest-arranger --from-literal auth_filter_field='gen3_resource_path' --from-literal auth_filter_node_types='[ "subject" ]' --from-literal project_id='dev' --from-literal json='{ "project_id": "dev", "auth_filter_field": "gen3_resource_path", "auth_filter_node_types": [ "subject" ] }'
```
(note how the values now have single-quotes)
=> fix/configmap-quoting: allow space in configmap values

kube/services/revproxy/00nginx-config.yaml
Patched the reverse proxy to allocate larger memory buffers - especially for header handling
=> fix(revproxy): double some buffer sizes

doc/logs.md, gen3/bin/kube-dev-namespace.sh, gen3/bin/logs.sh, gen3/lib/kube-setup-init.sh
- add `statsmin` and `statsmax` filters to `gen3 logs` - ex:
```
gen3 logs raw statsmin=400
```
* add `kibana.planx-pla.net` to `no_proxy` environment variable
=> fix(gen3 logs): no_proxy kibana, statsmin/max

gen3/bin/g3k_testsuite.sh, gen3/bin/gitops.sh, gen3/bin/testsuite.sh
* `gen3 gitops dotag` was not pulling the latest revision from github
* fix issue where the `klock` testsuite could fail if multiple jobs run simultaneously
=> fix(gen3 gitops dotag): forgot to git pull

gen3/bin/kube-setup-cronjobs.sh, kube/services/google-sa-validation/google-sa-validation-deploy.yaml, kube/services/google-sa-validation/google-sa-validation-service.yaml, kube/services/revproxy/gen3.nginx.conf/google-sa-validation-service.conf
add google sa validation service to replace the previous cronjob
- add google sa validation service to replace the previous cronjob
- remove previous cronjob in dcf prod and run `gen3 kube-setup-cronjob` to setup new service, then `gen3 kube-setup-revproxy` to update revproxy with new endpoint
=> Feat/google sa - add google sa validation service

files/squid_whitelist/web_whitelist
- ifconfig.io is now whitelisted, easy to check which public IP you are using to go out to the Interntet.
=> add(ifconfig.io): to squid whitelist

tf_files/aws/commons/cloud.tf
This basically creates a DNS entry for csoc-cloud-proxy.internal.io to point to the endpoint in the VPC which is pointing to the endpoint service in CSOC (corresponding to the squid NLB set-up).
Commons VPC will be able to use the squid NLB set-up in the CSOC.
=> chore(squidnlb): enabling csoc squid for commons

kube/services/jobs/usersync-cronjob.yaml
Improves dbgap output to slack webhook. The output is now gated by a variable in the manifest, and reduced to twice a weekday.
=> fix(slack): Update output settings for dbgap read -> slack

kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml
fix(aws-es-proxy): pin image to version 0.8
=> fix(aws-es-proxy): pin image to version 0.8

kube/services/fluentd/fluentd.yaml, tf_files/aws/modules/common-logging/logging.tf
-  Fluentd allocations were too low crashing the pods while sending logs to Cloudwatch
=> fix(allocations): for the fluentd daemonset PXP-1040

gen3/bin/reset.sh
Moved delete and create fence configmap above roll all.
Fixes bug in Jenkins where killing a build waiting for pods to roll, and build was stopped, the command for deleting the fence configmap was still executed, causing problems for pods to roll in the next build in the same namespace.
=> refactor(reset): move delete configmap above roll

kube/services/jobs/etl-cronjob.yaml, kube/services/jobs/etl-job.yaml
- Change to run ETL job in one command with new branch of ETL in master. Use with etl 0.1.9
- cdis-manifest will fail if still use the version smaller than 0.1.9 because `run_etl.py` is not there
- timestamp checking. Only run ETL if there is a new transaction after previous running etl.
=> feat(etl): running etl job 1 command

kube/services/revproxy/helpers.js
- do not set user to raw access token
=> fix(nginx-helper): do not expose auth token

kube/services/jobs/gentestdata-job.yaml
- gentestdata needs to tail output of fence-create to get access token
=> fix(gentestdata): fence-create output cleaning

doc/canary.md, kube/services/revproxy/helpers.js, kube/services/revproxy/helpersTest.js
Adds support for `dev_canaries` override cookie.
* Adds support for `dev_canaries` override cookie.
=> fix(canaries): support dev-canaries cookie

kube/services/arborist/arborist-deploy.yaml
Change the way an arborist deployment responds when `fence-create` fails ...
* retry fence-create
* bail out if fence-create never succeeds
=> chore(arborist): rework fence sidecar

files/squid_whitelist/web_whitelist
To facilitate the go-getting of packages. For example:
go get -u golang.org/x/crypto/ssh/terminal
go get -u golang.org/x/sys/unix
go get -u golang.org/x/net/context
go get -u gopkg.in/yaml.v2
=> chore: add gopkg and golang to whitelist

gen3/bin/reset.sh, kube/services/jobs/gdcdb-create-job.yaml
tweak `gen3 reset` again to accomodate changes in sheepdog startup -
run jobs before and after service roll -
avoid race conditions with fence,
arborist, and sheepdog
=> fix(gen3 reset): run jobs twice

gen3/lib/testData/default/expectedSheepdogResult.yaml, gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml, kube/services/sheepdog/sheepdog-canary-deploy.yaml, kube/services/sheepdog/sheepdog-deploy.yaml
chore(sheepdog): Now that both reverse proxy and uWSGI worker of sheepdog will timeout in 45 seconds, it shall be safe to terminate the Docker container after 50 seconds.
* Sheepdog shutdown wait time is now 50 seconds
=> PXP-2441: make sheepdog termination shorter

gen3/lib/g3k.sh
Previously `gen3 pod <name>` was returning the canary deployment if it existed. Should fix that problem
=> fix(g3k): don't return canary if not specified

kube/services/peregrine/peregrine-canary-deploy.yaml, kube/services/peregrine/peregrine-deploy.yaml, kube/services/sheepdog/sheepdog-canary-deploy.yaml, kube/services/sheepdog/sheepdog-deploy.yaml
* fix noise of `/_status`
* Reduced peregrine startup waiting time (`livenessProbe.initialDelaySeconds`) refs uc-cdis/peregrine#104
=> PXD-2561: fix noise of /_status

kube/services/google-sa-validation/google-sa-validation-deploy.yaml
- add k8s probe for google sa validation, if the google sa validator haven't had a successful run in last 30 min, the pod will be recycled
=> fix(google): check last validation time

kube/services/peregrine/peregrine-deploy.yaml, kube/services/revproxy/gen3.nginx.conf/peregrine-service.conf
Add a new optional variable to peregrine deployment for setting datasets endpoint to public.
If this variable is set to true in gitops, the datasets endpoint will allow anonymous access
- add a new optional variable to peregrine deployment for setting datasets endpoint to public
=> feat(peregrine): add datasets config

gen3/bin/s3.sh, tf_files/aws/modules/s3-bucket/cloud.tf
`gen3 s3 info`: fetch aws account id before checking for the policy
=> fix(s3): fetch aws account id and warn when unable to find policy

files/squid_whitelist/web_whitelist, flavors/squid_auto/healthcheck_status.sh, flavors/squid_auto/squidvm.sh, tf_files/aws/modules/squid_auto/cloud.tf
Introduced an active-standby squid set-up for commons; where if the active VM goes down the standby VM takes the active role. Reducing the downtime greatly.
=> Active-Standby setup for squid in commons

gen3/bin/kube-setup-jupyterhub.sh, kube/services/jupyterhub/rolebinding-jupyter.yaml
This allows doing parallel QA in jupyterhub in our QA environments sharing the same jupyter namespace.
It doesn't allow a test user in both QA envs to use jupyter at the same time
- namespace the rolebinding name for service account used by jupyterhub in gen3 services' namespace
=> fix(jupyter): namespace role binding

Docker/Jenkins/Dockerfile, kube/services/jenkins/jenkins-deploy.yaml
The new DCF tests need to use a different service account
- Use a new secret (manually set up in `qaplanetv1` with `gen3 secrets`)
- Bump docker jenkins version
=> chore(jenkins): new GOOGLE_APP_CREDS_JSON secret

kube/services/jobs/usersync-cronjob.yaml
Sometimes the credentials need to be refreshed on the nodes leading to initial awscli command failures. This retries the usersync user.yaml download up to 5 times.
Example of this working:
```
awshelper downloading s3://cdis-gen3-users/dcfstaging/user.yaml to /mnt/shared/useryaml
Download attempt 0
download failed: s3://cdis-gen3-users/dcfstaging/user.yaml to ../../mnt/shared/user.yaml Unable to locate credentials
Download attempt 1
download: s3://cdis-gen3-users/dcfstaging/user.yaml to ../../mnt/shared/user.yaml
awshelper container user.yaml diff ...
no difference found
```
- Retry user.yaml download in usersync cronjob
=> feat(retry): Retry S3 downloads for usersync cronjob

gen3/bin/es.sh
npx elasticdump is resource intensive and kills adminvm 
- do not install elasticdump for every index export/import
=> fix(esimport): install elasticdump

tf_files/aws/modules/commons-vpc-es/cloud.tf
- Elastic search not able to write to cloudwatchlogs
=> chore(permission): to allow ES write on the loggroup PXP-2554

kube/services/guppy/guppy-deploy.yaml, kube/services/guppy/guppy-service.yaml, kube/services/revproxy/gen3.nginx.conf/guppy-service.conf
- Remove unused env var from guppy config, and allow large size queries
=> fix(guppy): remove unused env var, and allow large size queries

kube/services/guppy/README.md, kube/services/guppy/guppy-deploy.yaml, kube/services/portal/README.md, kube/services/portal/portal-deploy.yaml
- A new global arg `tier_access_level` will be added to `manifest.json` to be used by both portal and guppy for tiered access
- `tier_access_level` includs `libre`, `regular` and `private`, for default commons will be using `private`
=> feat/add 'secure-level' args for guppy and portal

kube/services/jupyterhub/jupyterhub-deploy.yaml, kube/services/jupyterhub/jupyterhub_config.py
* jupyter notebook disk size configurable in manifest
* small tweak in `jupyter_config.py` to get rid of `KubeSpawner.singleuser_image_spec deprecated ...` warning
ex:
```
"jupyterhub": {
"enabled": "yes",
"nb_storage_size": "20Gi"
},
```
=> chore(jupyterhub): disk size from manifest

doc/db.md, gen3/bin/db.sh, gen3/test/dbTest.sh
Can do this kind of thing:
```
serverName="$(gen3 db creds "$serviceName" | jq -r .g3FarmServer)"
dbName="$(gen3 db creds "$serviceName" | jq -r .db_database)"
gen3 db psql "$serverName" -d "$dbName" -c 'CREATE EXTENSION ltree;'
```
=> chore(gen3 db): 'server info' and 'g3FarmServer'

kube/services/guppy/README.md, kube/services/guppy/guppy-deploy.yaml, kube/services/portal/README.md, kube/services/portal/portal-deploy.yaml
For `regular` tier-access-level data commons, add `tier_access_limit` to portal and guppy, for minimum visible count for aggregation results.
- For `regular` tier-access-level data commons, add `tier_access_limit` to portal and guppy, for minimum visible count for aggregation results.
=> chore(limit): add tier_access_limit for minimum visible aggs count

flavors/squid_auto/default_ip_route_and_instance_check_config.sh, flavors/squid_auto/squid_auto_user_variable, tf_files/aws/modules/squid_auto/cloud.tf
Description about what this pull request does:
Getting rid of the route updates for private_user route table; as this route table has been removed in commons now.
=> Removing the private_user route table for updates

flavors/squid_auto/healthcheck_status.sh, flavors/squid_auto/squid_auto_user_variable, flavors/squid_auto/squidvm.sh, gen3/lib/aws.sh, tf_files/aws/modules/squid_auto/cloud.tf, tf_files/aws/modules/squid_auto/variables.tf, tf_files/aws/squid_auto/variables.tf
The roles on the VMs were sharing the same role name; which have created issues for accounts which have more than 1 commons. Moved a static variable as user variable to take care of it.
=> Squid_auto commons role change for the squidVMs as per the commons name

kube/services/guppy/README.md
In guppy readme there's a typo, camelCase should be underscore style
=> fix(typo): guppy readme has a typo, camelCase should be underscore style

tf_files/aws/modules/s3-bucket/cloud.tf
Add bucket lifecycle to remove incomplete multipart parts
Incomplete Multipart Uploads – S3’s multipart upload feature accelerates the uploading of large objects by allowing you to split them up into logical parts that can be uploaded in parallel.  If you initiate a multipart upload but never finish it, the in-progress upload occupies some storage space and will incur storage charges. However, these uploads are not visible when you list the contents of a bucket and had to be explicitly removed
=> feat(lifecycle_rule): add bucket lifecycle_rule

kube/services/revproxy/gen3.nginx.conf/arborist-service.conf, kube/services/revproxy/gen3.nginx.conf/arranger-service.conf, kube/services/revproxy/gen3.nginx.conf/google-sa-validation-service.conf, kube/services/revproxy/gen3.nginx.conf/guppy-service.conf, kube/services/revproxy/gen3.nginx.conf/jupyterhub-service.conf, kube/services/revproxy/gen3.nginx.conf/pidgin-service.conf, kube/services/revproxy/gen3.nginx.conf/portal-service.conf, kube/services/revproxy/gen3.nginx.conf/shiny-nb2-service.conf, kube/services/revproxy/gen3.nginx.conf/shiny-service.conf, kube/services/revproxy/gen3.nginx.conf/sower-service.conf, kube/services/revproxy/gen3.nginx.conf/workspace-token-service.conf
The $upstream variable was not being set correctly in many cases, so revproxy logs were missing that useful data
=> fix(revproxy): track $upstream in logs

kube/services/jobs/indexd-authz-job.yaml
- Add `indexd-authz` job to set the `authz` fields in index records according to their existing ACLs.
=> chore(authz-migration): add job to set authz fields

kube/services/revproxy/helpers.js, kube/services/revproxy/nginx.conf, kube/services/revproxy/revproxy-deploy.yaml
Fixed TODO about setting `Access-Control-Allow-Credentials: true` which is required for NIAID `tb` and `charlie` sub-commons.
- Added `origins_allow_credentials` in `global-manifest` to support sending cookies to trusted origins
=> Allow credentials origin white list

apis_configs/peregrine_settings.py, apis_configs/sheepdog_settings.py, gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml, kube/services/peregrine/peregrine-canary-deploy.yaml, kube/services/peregrine/peregrine-deploy.yaml, kube/services/sheepdog/sheepdog-canary-deploy.yaml, kube/services/sheepdog/sheepdog-deploy.yaml
We are removing signpost from sheepdog and peregrine. Sheepdog > 1.1.11 and Peregrine >1.2.1 will look for `INDEX_CLIENT` in config dict and `INDEX_CLIENT_HOST` env var. So add those here but retain the signpost settings for backwards compatibility.
=> chore(deprecate-signpost): add indexclient env vars/config

doc/csoc-free-commons-steps.md
Without it, deployments of arborist will fail to come up due to not having secrets.
kube-setup-arborist expect a version in the manifest to come up properly
- csoc free documentation
=> add(arborist): in manifest template

gen3/bin/kube-dev-namespace.sh
- kube-dev-namespaces should now work on every environment, not just dev
=> chore(cert copy): admin certs are not needed after EKS

gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml, kube/services/sheepdog/sheepdog-deploy.yaml
- Add `AUTH_NAMESPACE` env to sheepdog from `auth_namespace` in the manifest. Supports [this PR](https://github.com/uc-cdis/sheepdog/pull/288) so we can actually add resource paths to metadata entries on submission.
=> feat(consent-codes): add auth namespace var to sheepdog

files/scripts/es-cronjob.sh
Run cronjob to re-create ES indices for Kibana
- Add bash script to automate es indices creation
=> feat(indices): recreate all indices

gen3/bin/kube-setup-secrets.sh, gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml, kube/services/fence/fence-canary-deploy.yaml, kube/services/fence/fence-deploy.yaml, kube/services/portal/portal-deploy.yaml
TODO:
- add support for fence serving privacy policy
- add `PRIVACY_POLICY_URL` env for fence which defines redirect
- add volume mount for static `.md` file to put the policy in
In terms of deployment changes, be sure to run `kube-setup-secrets` before using these changes, otherwise the fence and data-portal pods will fail to come up because of the missing volume.
=> feat/privacy policy: support for fence & windmill serving privacy policy

gen3/bin/kube-roll-all.sh
need to apply the "disable" rule before we start bringing up services,
because rolling a service updates that service networkpolicy,
and networkpolicy does not work if only some of the rules are applied ...
=> fix(roll-all): disable netpolicy earlier

kube/services/monitoring/grafana-values.yaml
* Updates the Grafana to latest (6.3.5) version: improved filtering for Prometheus, better provisioning setup, Loki improvements.
=> chore(grafana): update the Grafana to latest (6.3.5) version

kube/services/sower/sower-deploy.yaml
Sower 0.3.0 and up doesn't use additional Pelican or Peregrine secrets therefore they are not needed.
- No
- No, just use 0.3.0 and above. No changes for VPODC, it has pinned sower version which doesn't use secrets at all.
=> chore(sower): sower 0.3.0 doesn't need any additional secrets

files/squid_whitelist/web_whitelist
* Allow gist.githubusercontent.com in Squid whitelist
=> chore(gist): allow gist in Squid

apis_configs/peregrine_settings.py, apis_configs/sheepdog_settings.py
Add "ARBORIST" parameter to Peregrine and Sheepdog configs to specify arborist URL
[Default is "http://arborist-service/"](https://github.com/uc-cdis/gen3authz/blob/0.2.2/python/gen3authz/client/arborist/client.py#L124)
=> chore(arborist-param): peregrine and sheepdog apis_configs

kube/services/revproxy/gen3.nginx.conf/mariner-service.conf
Remove mariner conf. Mariner API not supposed to be publicly exposed.
- remove mariner from revproxy
=> Remove mariner revproxy conf.

gen3/bin/kube-roll-all.sh
Don't deploy mariner in "gen3 roll all", since mariner is not a core service for every commons.
- Don't deploy mariner in "gen3 roll all", since mariner is not a core service for every commons.
=> Remove mariner from gen3-roll-all

files/scripts/jupyter_migration.sh
- When volumes were created off snapshots taken from existing jupyter volumes, naming prefix were hardcoded instead of using the variable assigned for that purpose
=> chore(volumes): naming after deploying from snapshot

files/squid_whitelist/web_whitelist
Add login.bionimbus.org/Shibboleth.sso/DiscoFeed to squid whitelist to fetch list of available shibboleth IDPs from data-portal for incommon
=> squid whitelist += login.bionimbus.org

kube/services/revproxy/gen3.nginx.conf/arborist-service.conf
related Arborist PR here https://github.com/uc-cdis/arborist/pull/110 
expose arborist's /auth/mapping endpoint (to GET requests only, and without passing the username query param)
=> feat(authz-mapping): expose authz mapping endpoint

kube/services/jobs/useryaml-job.yaml
1. useryaml job shouldn't have been checking /mnt/shared for the useryaml--that path is only relevant for the usersync job, where the pod has a shared mount with the aws helper pod, and the useryaml from s3 ends up in the shared mount. 
2. but also useryaml job should just always get the useryaml from the configmap (which gets mounted to /var/www/fence) and pass it in the --yaml arg. So change the if/else accordingly. 
3. (If dev wants to run just dbgap with no useryaml, use usersync job with ONLY_DBGAP set)
fix useryaml job so it always gets useryaml from configmap instead of checking /mnt/shared, which is relevant only in user_sync_ job
=> fix(yaml-mount): don't check mount for useryaml

gen3/lib/testData/default/expectedSheepdogResult.yaml, kube/services/jobs/README.md, kube/services/jobs/google-delete-expired-service-account-cronjob.yaml, kube/services/jobs/google-init-proxy-groups-cronjob.yaml, kube/services/jobs/google-manage-account-access-cronjob.yaml, kube/services/jobs/google-manage-keys-cronjob.yaml, kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
put hostname in slack messages from google cron jobs instead of environment name - we can run multiple commons in the same environment under different namespaces
=> fix(google-cron): slack hostname, not env name

kube/services/ambassador-gen3/ambassador-gen3-deploy.yaml, kube/services/ambassador/ambassador-deploy.yaml
fix for: gen3 roll ambassador
the ambassador deployment did not have an explicit selector specified - which breaks under weird circumstances
=> fix(ambassador): deployment selector

doc/csoc-free-commons-steps.md
If the commons-name is kept as the default here (i.e. "commons-test"), the suggested vpc_name also becomes "commons-test". However, this vpc_name results in terraform apply failing because several bucket names are derived from the vpc_name, and bucket names must be unique.
=> Added vpc_name to list of variables to pay attention to

gen3/bin/kube-setup-networkpolicy.sh, gen3/lib/testData/default/expectedFenceResult.yaml, gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml, kube/services/fence/fence-deploy.yaml, kube/services/netpolicy/user/notebook_netpolicy.yaml
* enable network policies in jupyter-* namespace (kubernetes is at 1.13+ now)
* allow jupyter ingress from ambassador
* mark fence as a `userhelper` service, so hatchery apps can get signed url's
=> fix(netpolicy): fuse+ambassador rules

files/squid_whitelist/web_whitelist
The load testing exercise is triggering a behavior where a new inbound request pointing to the environment's external address is produced against the reverse proxy.
Trying this new configuration to observe the load test results.
=> whitelisting internalstaging datastage for load testing purposes

files/squid_whitelist/web_whitelist
This produces misleading HTTP 200 requests with an HTML payload (as opposed to PreSigned URLs).
Reverts uc-cdis/cloud-automation#1050
=> Revert "whitelisting internalstaging datastage for load testing purposes"

Docker/python-nginx/python3.6-alpine3.7/entrypoint.sh
The load testing exercises revealed certain RPS thresholds in which fence would struggle to produce responses with a reasonable latency. In order to avoid a scenario where fence would still receive a surge of requests while being overwhelmed, this Nginx config should prevent the unnecessary workload from reaching the underlying service.
This approach allows the cluster admin to leverage this feature through a parameterized mechanism, i.e., managed through an optional variable added to the `env` block of the k8s deployment descriptor:
https://github.com/uc-cdis/cloud-automation/blob/master/kube/services/fence/fence-deploy.yaml
**Results:**
Example of `nginx.conf` when the `NGINX_RATE_LIMIT ` environment variable is not set:
```
kc exec -it fence-deployment-679d6958df-gswht -- grep -A2 …
```
=> Chore(load_test): Add Nginx rate limit to help Fence with its RPS throughput

Docker/python-nginx/python3.6-alpine3.7/entrypoint.sh
The load testing exercises revealed certain RPS thresholds in which fence would struggle to produce responses with a reasonable latency. In order to avoid a scenario where fence would still receive a surge of requests while being overwhelmed, this Nginx config should prevent the unnecessary workload from reaching the underlying service.
This approach allows the cluster admin to leverage this feature through a parameterized mechanism, i.e., managed through an optional variable added to the env block of the k8s deployment descriptor:
https://github.com/uc-cdis/cloud-automation/blob/master/kube/services/fence/fence-deploy.yaml
This change is a complement of the PR below:
https://github.com/uc-cdis/cloud-automation/pull/1052
This code injects some missing configuration that must be added to …
=> chore(load_test): Add optional nginx config to handle wsgi/fence throughput

Docker/python-nginx/python3.6-alpine3.7/entrypoint.sh
Lessons learned:
Do not add any configuration to `/etc/nginx/conf.d/uwsgi.conf`.
Add them to `/etc/nginx/sites-available/uwsgi.conf` instead so the symbolic link can be created successfully:
`ln -s /etc/nginx/sites-available/uwsgi.conf /etc/nginx/conf.d/uwsgi
.conf`
This is a bug fix to the changes introduced in:
https://github.com/uc-cdis/cloud-automation/pull/1052
and
https://github.com/uc-cdis/cloud-automation/pull/1053
TESTING
--
```
$ kc get pods | grep fence
fence-deployment-8474db57cb-tkblq                        1/1     Running             0          2m18s
$ kc exec -it fence-deployment-8474db57cb-tkblq -- curl http://localhost/_status
Healthy
$ kc get pod fence-deployment-8474db57cb-tkblq -o yaml | grep image
image: quay.io/cdis/fence:chore_rate_limit_test
```
Configuration in …
=> fix(load_test): Fix nginx config by adding instructions to the correct file

files/squid_whitelist/web_whitelist, files/squid_whitelist/web_wildcard_whitelist
The NodeJS module [`wcag`](https://github.com/cfpb/node-wcag)  leverages a web service (https://achecker.ca/) to perform Section 508 checks.
Jenkins must be able to talk to this web service.
=> chore(section508): Whitelist achecker.ca domain to check section 508 compliance

files/squid_whitelist/web_wildcard_whitelist
This is required to verify compliance of our new BCat gen3 commons with Section 508.
The wild card should cover both preprod and prod.
=> chore(QA): Run section 508 compliance against .biodatacatalyst.nhlbi.nih.gov domain

files/squid_whitelist/web_wildcard_whitelist
Reverts uc-cdis/cloud-automation#1070
=> Revert "chore(QA): Run section 508 compliance against .biodatacatalyst.nhlbi.nih.gov domain"

files/squid_whitelist/web_whitelist, files/squid_whitelist/web_wildcard_whitelist
We need the gen3-fuse sidecar to be able to talk to external Data Commons
Removing the `*.bionimbus.org` entries from the `web_whitelist` because they conflict with the `.bionimbus.org` entry in the `web_wildcard_whitelist`
=> chore(whitelist): add data commons domains to squid whitelist

Jenkinsfile
The signature of the runIntegrationTests method changed due to:
https://github.com/uc-cdis/cdis-jenkins-lib/pull/68/commits/11b32b02a05b32acf553a852b170dc61c8c8fcac
and since `cloud-automation` has its own Jenkinsfile , it is not calling the function with all the expected parameters.
=> Fix(QA): Fix runIntegrationTests call

tf_files/aws/commons/cloud.tf, tf_files/aws/commons/kube.tf, tf_files/aws/commons/variables.tf, tf_files/aws/modules/squid/cloud.tf, tf_files/aws/modules/squid/variables.tf, tf_files/aws/modules/vpc/cloud.tf, tf_files/aws/modules/vpc/variables.tf, tf_files/aws/squid_vm/root.tf, tf_files/aws/squid_vm/variables.tf
- Single squid instance type is a variable.
- The instance product of this module has now `deploy_before_destroy` enabled.
=> chore(instance type): made it a variable

gen3/bin/job.sh, gen3/bin/kube-setup-fence.sh, kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
* kube-setup-fence runs migrate job, so we can disable db migration in fence-config-public.yaml in all our commons if we want to ...
* disable migration in presigned-url deployment
=> chore(fence-migrate): setup-fence runs migrate job

files/squid_whitelist/web_whitelist
Whitelisting this endpoint to facilitate the POC involving Fence's APM monitoring.
=> chore(qa): Whitelist the NewRelic Collector endpoint to facilitate POC

tf_files/aws/eks/variables.tf, tf_files/aws/modules/eks/variables.tf
- Switched the domain used to check for internet access from the VPC where commons' kubernetes workers live. The previous default one returned 302 (redirection) codes forcing the check to switch the active instances every minute. www.google.com return 200 which is acceptable as a working internet connection.
=> chore(domain): switched to www.google.com

kube/services/revproxy/nginx.conf
setting upstream at top level screws up authz callouts
=> fix(revproxy): authz

files/squid_whitelist/web_wildcard_whitelist
Add .amazoncognito.com to squid web_wildcard_whitelist, so that Fence can use Cognito as an IdP
=> chore(whitelist-cognito): add .amazoncognito.com to squid whitelist

gen3/bin/kube-setup-wts.sh, kube/services/wts/wts-deploy.yaml
Jira Ticket: [PXP-4931](https://ctds-planx.atlassian.net/browse/PXP-4931)
- Run WTS DB migration during "kube-setup-wts"
- Add empty "external_oidc" field to WTS configuration file
=> PXP-4931 WTS DB migration

Docker/Jenkins/Dockerfile, Docker/Jenkins/install-python3.6.sh
Python3.6 is required to run some QA automation that depends on `gen3sdk-python`.
=> chore(QA): python36 in jenkins

tf_files/aws/modules/eks/init_cluster.sh
- eks workers init script had a duplicated `kubectl apply -f` on the same line, breaking the application of the file that deploys calico.
=> fix(script): duplicated call to kubectl apply

Docker/python-nginx/python2.7-alpine3.7/nginx.conf, Docker/sidecar/nginx.conf, kube/services/netpolicy/gen3/services/revproxy_netpolicy.yaml, kube/services/revproxy/nginx.conf
* handling of external requests to port 80 by the reverse proxy and network policy
* disable TLSv1 in old docker images
* service_releases cookie http-only, secure
=> fix(nginx.conf): security tweaks PXP-5723

files/squid_whitelist/web_whitelist
Whitelisting as this is blocking some automation:
```
WARNING:root:Got ConnectionError [('Connection aborted.', OSError(0, 'Error'))] errno:None on GET https://ctds-planx.atlassian.net/rest/api/2/serverInfo
```
=> chore(qa): Whitelist JIRA Cloud endpoint to facilitate automatic jira-creation jobs

gen3/bin/db.sh
- When creating databases, the script uses the current user name. When the user has hyphens in the name, like iam-anuser, postgres doesn't like it and the script bails.
This patch would replace hyphens for underscores before creating databases when  `db_restore`ing.
=> fix(bug): replace - for _ when creating databases

gen3/bin/workers-cycle.sh
- by using `aws autoscaling terminate-instance-in-auto-scaling-group` instead of `aws ec2 stop-instances` we are letting the ASG that we want to keep the desired state so it tries to spin up a new instance right away.
=> chore(code): optimization

gen3/bin/workers-cycle.sh
- `kubectl node drain` commands now have the `--force` flag for draining deleting "Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet"  like hatchery pods.
=> add(force): for node drain

gen3/bin/iam-serviceaccount.sh
- Using `gen3 iam-serviceaccount` results in `null` in service-account annotation. This is a fix for the issue.
- `gen3 iam-serviceaccount` produces wrong link (contains `https` part) in Federated part of trust policy. Fixed now.
=> fix: gen3 iam-serviceaccount fixes

kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
The rate limit config had been accidentally disabled when the `command` override was introduced to this deployment (which suppresses the parent image's `entrypoint.sh` execution). Adding an extra call to this script to make sure the NGINX_RATE_LIMIT check is executed.
=> fix(presigned-url-fence): Enabling Rate Limiting again

files/squid_whitelist/web_wildcard_whitelist
update squid whitelist with quay.io wildcard - they'll change their cdn domain soon
=> chore(whitelist): quay.io wildcard

doc/csoc-free-commons-steps.md
When I tried to follow the steps in this file I ended up with:
```
Error from server (NotFound): configmaps "global" not found
ERROR: 21:06:18 - g3k_manifest_path could not establish commons hostname
dirname: missing operand
Try 'dirname --help' for more information.
```
Adding this step (borrowed from the directions in csoc-attached-commons-steps.md) fixed this issue.
- documentation
=> docs: Include direction to apply the global manifest.

gen3/bin/report-tool.sh
- Report tool would fail if kubeconfig file is located at a different folder than `${HOME}/${vpc_name}/kubeconfig`. It is now loaded from the location returned by gen3.
=> fix(kubeconfig): export the file on its respective location

files/squid_whitelist/web_whitelist, files/squid_whitelist/web_wildcard_whitelist
squid wildcard for `.opensciencedatacloud.org`
=> chore(squid): wildcard opensciencedatacloud

gen3/bin/kube-setup-revproxy.sh, kube/services/revproxy/revproxy-service-elb.yaml, tf_files/aws/modules/eks/cloud.tf
deploy internal ELB like this:
* delete the existing lb if necessary - `g3kubectl delete service revproxy-service-elb`
* tag the `eks_private*` subnets with `key: kubernetes.io/role/internal-elb, value: 1`
* set `lb_type: "internal"` in the `global` section of the manifest
* `gen3 kube-setup-revproxy`
* now you have a load balancer with private IP addresses - update DNS
=> chore(elb-internal): support for lb_type:internal

kube/services/revproxy/gen3.nginx.conf/fence-service.conf, kube/services/revproxy/gen3.nginx.conf/indexd-service.conf
- Based on [RFC5785](https://tools.ietf.org/html/rfc5785), Fence's OIDC Discovery Endpoints should be exposed under `hostname/.well-known/openid-configuration` and `hostname/.well-known/jwks`
- At the same time, since we have users depending on these endpoints, we still want them to be accessible under `hostname/user/.well-known/openid-configuration` and `hostname/user/.well-known/jwks`
- Minor edit to comment in indexd endpoints
=> open-id discovery endpoints

Docker/awshelper/Dockerfile
Revert awshelper image to unbreak jobs
=> fix(revert-awshelper): reverting awshelper image to unbreak jobs

gen3/bin/kube-setup-sower-jobs.sh
- don't error when aws role names are above 64 char limit (slice to limit)
=> fix(rolename): aws role names have 64 char limit

kube/services/selenium/README.md, kube/services/selenium/selenium-hub-deployment.yaml, kube/services/selenium/selenium-node-chrome-deployment.yaml
We have reached our 10 slot threshold today. Let us bump this up to 20.
```
$ kc exec -it jenkins-deployment-cbfd8dd5b-pgssf  -c jenkins -- curl -vv http://selenium-hub:4444/wd/hub/status | grep message
"message": "Hub has capacity",
$ kc exec -it jenkins-deployment-cbfd8dd5b-pgssf -c jenkins -- curl -vv http://selenium-hub:4444/grid/api/hub/status | grep -A4 slotCounts
"slotCounts": {
"free": 12,
"total": 20
},
"success": true,
```
=> chore(qa): Tuning selenium grid (bump up slots/sessions across nodes)

kube/services/jobs/covid19-etl-job.yaml
- COVID19 ETL: add ETL name to slack notification
=> COVID19 ETL: add ETL name to slack notification

files/squid_whitelist/web_whitelist, files/squid_whitelist/web_wildcard_whitelist
- Added .dph.illinois.gov to Squid whitelist, removed www.dph.illinois.gov
=> Whitelist idph website for covid-19 etl job

kube/services/selenium/selenium-hub-deployment.yaml, kube/services/selenium/selenium-node-chrome-deployment.yaml
Applying changes due to the following errors:
```
$ kc apply -f selenium-hub-deployment.yaml
error: unable to recognize "selenium-hub-deployment.yaml": no matches for kind "Deployment" in version "v1"
--
$ kc apply -f selenium-hub-deployment.yaml
apiVersion: v1
The Deployment "selenium-hub" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "always": supported values: "Always", "IfNotPresent", "Never"
```
=> fix(qa): Fix Selenium k8s descriptors

kube/services/jobs/arborist-rm-expired-access-cronjob.yaml, kube/services/jobs/etl-cronjob.yaml, kube/services/jobs/gitops-sync-cronjob.yaml, kube/services/jobs/google-delete-expired-service-account-cronjob.yaml, kube/services/jobs/google-init-proxy-groups-cronjob.yaml, kube/services/jobs/google-manage-account-access-cronjob.yaml, kube/services/jobs/google-manage-keys-cronjob.yaml, kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml, kube/services/jobs/hatchery-reaper-cronjob.yaml, kube/services/jobs/healthcheck-cronjob.yaml, kube/services/jobs/nb-etl-cronjob.yaml, kube/services/jobs/usersync-cronjob.yaml
guard against overlapping cronjob runs: 
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
=> fix(cronjob-concurrency): prevent job run overlap

files/scripts/qa-cronjob.sh
Improve the qa-cronjob:
* either `roll all` or `shutdown` - not both
* support for `$GEN3_SHUTDOWN` environment variable toggle
=> chore(qa-cronjob): roll or shutdown - not both

kube/services/jobs/nb-etl-cronjob.yaml, kube/services/jobs/nb-etl-job.yaml
- COVID19 "nb-etl": do not overwrite "command" and "args" from Dockerfile
=> COVID19 "nb-etl" no "command" overwrite

files/scripts/qa-restart-selenium.sh
The script is still failing due to one `kubectl` cmd that was left in the script by mistake 🤦 
```
qaplanetv1@cdistest_dev_admin:~$ cat qa-restart-selenium.log
error: You must be logged in to the server (Unauthorized)
error: resource(s) were provided, but no name, label selector, or --all flag specified
```
Replacing `kubectl` with `g3kubectl`,
=> fix(qa): Use g3kubectl instead of kubectl for qa-restart-selenium script

gen3/bin/kube-setup-guppy.sh
- Increase Guppy wait time for ES proxy to 250s (50 cycles)
=> chore: increase guppy wait time for es proxy

Jenkinsfile
Avoid lingering artifacts from previous PR check runs.
=> chore(clean-ws): Clean Workspace before fetching new code and running tests

kube/services/jenkins-worker/jenkins-worker-deployment.yaml
That should issues like the one below (gen3 CLI features that need to instrument the underlying Docker daemon running at the ec / kube node level):
```
pushing arborist img to AWS ECR...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied
pushing gen3-statics img to AWS ECR...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=quay.io%2Fcdis%2Fgen3-statics&tag=2020.07: dial unix /var/run/docker.sock: connect: permission denied
```
=> fix(qa): chmod docker.sock in gen3-qa-worker init container

kube/services/metadata/metadata-deploy.yaml
Fixes issues with network egress observed in metadataservice.
=> Add network policy netnolimit to metadataservice deployment

files/squid_whitelist/web_whitelist
Must whitelist the following domain:
`https://biodata-integration-tests.net`
=> chore(qa): Whitelist biodata integration tests domain

gen3/bin/bucket-manifest.sh
Minor fix to lay down a paramFile.json containing some key data to be used by the Jenkins CI tests while executing the bucket-manifest CLI command.
Testing:
```
jenkins-dcp@cdistest_dev_admin:~$ gen3 bucket-manifest create-jenkins cdistest-public-test-bucket
jenkins-dcp-planx-pla-net-bucket-manifest-3g3w
ERROR: 18:13:41 - No fence_bot aws credential block in fence_config.yaml
jenkins-dcp@cdistest_dev_admin:~$ cat paramFile.json
{
"job_id": "3g3w",
"bucket_name": "jenkins-dcp-planx-pla-net-bucket-manifest-3g3w-temp-bucket"
}
```
=> fix(qa): Minor fix for bucket-manifest create-jenkins function

gen3/bin/kube-setup-workvm.sh, gen3/lib/g3k_manifest.sh, tf_files/aws/modules/eks/kubeconfig.tpl
* switch from old `heptio-authenticator-aws` to recent `aws-iam-authenticator`
* switch from old `heptio-authenticator-aws` to recent `aws-iam-authenticator`
=> chore(eks): switch heptio- to aws-iam-authent..

doc/csoc-free-commons-steps.md
gen3 roll all bailed out, stating that all comonents do not have a defined version and will therefor not be deployed.
Removing the additional , fixed this behaviour.
=> csoc-free commons issue in manifest.json template

Docker/Jenkins-Worker/Dockerfile, Docker/Jenkins/Dockerfile
Quick test within the container:
```
Installing collected packages: lxml
Successfully installed lxml-4.5.2
```
```
jenkins@jenkins-deployment-755c6b9dfc-p7wvz:~/workspace/test-xml-read/output$ python -c "import lxml.etree; print(lxml.etree.fromstring(\"\"\"$(cat 90ff652b-dd6f-487c-9cb6-c06177fcbb6c-testsuite.xml)\"\"\").xpath('//ns2:test-suite/test-cases/test-case/@status', namespaces={'ns2': 'urn:model.allure.qatools.yandex.ru'}))"
['failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed']
```
=> chore(qa): Install xml parser for Jenkins

kube/services/influxdb/README.md, kube/services/influxdb/influxdb-deployment.yaml, kube/services/influxdb/influxdb-pvc.yaml, kube/services/influxdb/influxdb-service.yaml
This should address task PXP-5818 (Track number of retries and failures in the CI pipeline help prioritize the work around flaky tests)
=> chore(qa): Introduce InfluxDB to store CI Metrics.

.secrets.baseline, gen3/bin/kube-setup-dashboard.sh, kube/services/dashboard/dashboard-deploy.yaml
Jira Ticket: [PXP-6336](https://ctds-planx.atlassian.net/browse/PXP-6336)
* kube-setup-dashboard no longer creates an IAM user - new dashboard deployments must run 2020.08 or newer docker image, existing deployments should continue to work fine with user IAM creds
=> chore(dashboard): deprecate user setup

gen3/lib/g3k_manifest.sh
Fix `g3kubectl` to call `return 1` instead of `exit 1` to avoid upgrade problems by the community and weird behavior on a new admin vm
=> fix(gen3-setup): no exit on aws-iam-auth install

gen3/bin/kube-setup-workvm.sh
Make sure to follow the DEV guidelines (https://gen3.org/resources/developer/dev-introduction/) before asking for review.
Add the python package python-venv to be installed when setting up kube work vm.
=> add pythonvenv to kubeworkvm setup

kube/services/acronymbot/acronymbot-deploy.yaml
Adopt new secret to be able to fetch acronyms.txt (JSON) from private repo.
=> chore(qa): Update acronymbot to be compatible with private repos

kube/services/ambassador-gen3/ambassador-gen3-admin-service.yaml, kube/services/ambassador/ambassador-rbac.yaml, kube/services/arborist/arborist-service.yaml, kube/services/arranger/arranger-service.yaml, kube/services/aws-es-proxy/aws-es-proxy-service.yaml, kube/services/fence/fence-service.yaml, kube/services/fenceshib/fenceshib-service.yaml, kube/services/gdcapi/gdcapi-service.yaml, kube/services/guppy/guppy-deploy.yaml, kube/services/guppy/guppy-service.yaml, kube/services/indexd/indexd-service.yaml, kube/services/jupyterhub/jupyterhub-service.yaml, kube/services/mariner/mariner-service.yaml, kube/services/portal/portal-service.yaml, kube/services/presigned-url-fence/presigned-url-fence-service.yaml, kube/services/qa-dashboard/qa-dashboard-service.yaml, kube/services/sheepdog/sheepdog-service.yaml, kube/services/spark/spark-service.yaml, kube/services/userapi/userapi-service.yaml
Jira Ticket: [PXP-6506](https://ctds-planx.atlassian.net/browse/PXP-PXP-6506)
Change guppy deployment to listen on port  8000 in the container to avoid privilege escalation. This is important so guppy deployments will still work after we enforce PodSecurityPolicies that prevents privilege escalations.
=> Configure guppy to listen to port 8000 in anticipation of PSP

kube/services/qabot/qabot-deploy.yaml
Augment `qa-bot`'s capabilities so it can invoke Jenkins jobs as part of some basic ChatOps initiative.
=> chore(qa): Add k8s deployment descriptor for qa-bot

Jenkinsfile
To improve the testing coverage for all cloud-automation changes, we are enabling the full set of test suites for every PR.
=> chore(qa): Enable ALL tests for cloud-automation PRs

Docker/Jenkins/Dockerfile
Jenkins crashed and it couldn't come back up due to:
2020-08-19 04:59:00.802+0000 [id=26]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Step API v2.22 (workflow-step-api)
java.io.IOException: Failed to load: Pipeline: Step API (2.22)
- Update required: Structs Plugin (1.19) to be updated to 1.20 or higher
According to some research, upgrading to the latest Jenkins image fixes the issue.
=> chore(qa): Jenkins img 2.253

Docker/Jenkins-Worker/Dockerfile
We need jq 1.6 to support some gen3 release automation tasks.
=> chore(qa): Upgrade jq to 1.6 on gen3-qa-worker / jenkins agent

files/squid_whitelist/web_whitelist
Jira Ticket: [PXP-6612](https://ctds-planx.atlassian.net/browse/PXP-6612)
Preparing to update helm to helm3, we need to add the new helm download url in squid
=> Add get.helm.sh to squid whitelist

.secrets.baseline, kube/services/revproxy/README.md, kube/services/revproxy/gen3.nginx.conf/portal-workspace-parent.conf, kube/services/revproxy/helpers.js, kube/services/revproxy/helpersTest.js
Jira Ticket: [PXP-6630](https://ctds-planx.atlassian.net/browse/PXP-6630)
* introduce `/workspace-authorize/` endpoint when running in `GEN3-WORKSPACE-PARENT` mode - enabled via the `global.portal_app` manifest property.  Endpoint supports a multi-account apps deployment, by allowing multiple workspace accounts (all sub-domains of the parent account - which deploys the `/workspace-authorize/` endpoint) to share the same redirect endpoint for OIDC authorize flows with data commons.
* introduce `/workspace-authorize/` endpoint when running in `GEN3-WORKSPACE-PARENT` mode - enabled via the `global.portal_app` manifest property.  Endpoint supports a multi-account apps deployment, by allowing multiple workspace accounts (all sub-domains of the parent account - which deploys the …
=> chore(revproxy): /workspace-authorize/ endpoint

kube/services/jobs/covid19-etl-job.yaml
Increase the covid19-etl-job max memory to unblock the JHU_TO_S3 job until ticket COV-463 is fixed.
=> COVID19 ETL memory 512Mi -> 1024Mi

gen3/bin/kube-setup-tiller.sh
Fix of a bug when helm 2to3 plugin is not being installed properly and thus `kube-setup-tiller` will fail
=> Fix installation of 2to3 plugin for tiller cleanups

gen3/bin/kube-wait4-pods.sh
data portal is taking too long to come up, e.g.,
```
portal-deployment-5f8b855448-dscnz                0/1     Running     0          4m14s
portal-deployment-5f8b855448-hqqmj                1/1     Running     1          15m
...
[32mINFO: 14:33:36 -[39m ------------
[32mINFO: 14:33:36 -[39m Waiting for pods to exit Pending state
[31mERROR: 14:33:36 - pods still not ready after 900 seconds - bailing out[39m
[31mERROR: 14:33:36 - containers are still waiting in this namespace[39m
[31mERROR: 14:33:36 - looks like not everything is healthy[39m
[31mERROR: 14:33:36 - the cluster does not look healthy[39m
```
so let us increase the timeout until that can be improved.
=> chore(ci): Wait a bit longer for data-portal pods to come up

kube/services/influxdb/influxdb-deployment.yaml
Recent load testing operations are failing due to the following error:
```
time="2020-10-05T18:54:40Z" level=error 
msg="InfluxDB: Couldn't write stats" error="{\"error\":\"partial write: max-values-per-tag limit exceeded (100021/100000): 
measurement=\\\"http_reqs\\\" tag=\\\"name\\\" 
value=\\\"https://qa-niaid.planx-pla.net/study-viewer/clinical_trials\\\" dropped=240\"}\n"
```
- Resolve Influx DB limit based on measurement tag (`max-values-per-tag limit exceeded `)
=> fix(qa): Max values per tag limit exceeded in InfluxDB

gen3/bin/kube-wait4-pods.sh
We're still facing failures due to some `data-portal` pods that arise kinda later in the gen3 reset all stage.
=> chore(ci): Wait a bit longer (again) for data-portal pods to come up

kube/services/jobs/gentestdata-job.yaml
Adding submission order command to existing `gentestdata` k8s job's sequence of commands.
=> fix(qa): Define submission order for gentestdata

.secrets.baseline, doc/kube-setup-ssjdispatcher.md, gen3/bin/kube-roll-all.sh, gen3/bin/kube-setup-ssjdispatcher.sh
Jira Ticket: [PXP-6861](https://ctds-planx.atlassian.net/browse/PXP-6861)
This PR extends `kube-setup-ssjdispatcher` so that if the Metadata Service is deployed and MDS basic auth creds are present, add those MDS creds to SSJDispatcher's secret. See related [indexs3client PR ](https://github.com/uc-cdis/indexs3client/pull/29) requiring SSJDispatcher to pass it MDS creds. Going forward, the [SSJDispatcher service will require MDS creds to start](https://ctds-planx.atlassian.net/browse/PXP-6977).
Note that the addition of MDS creds will not break the "old" SSJDispatcher/indexs3client combination (i.e. versions of SSJDispatcher/indexs3client not requiring MDS creds).
- Configure Metadata Service basic auth creds in kube-setup-ssjdispatcher
=> (PXP-6861): configure Metadata Service creds in kube-setup-ssjdispatcher

Docker/python-nginx/python2.7-alpine3.7/dockerrun.sh, Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
The block that waits for `wsgi.sock` to appear is before `run uwsgi --ini /etc/uwsgi/uwsgi.ini` so it makes us wait 20 seconds for something that will not happen (since the app hasn't started yet). Remove it doesn't seem to cause issues
- Base python 2 and 3 images: don't wait for wsgi.sock to appear, speed up app start up
=> Pybase: don't wait for wsgi.sock

files/squid_whitelist/web_whitelist
Jira Ticket: COV-521
Whitelist opportunityinsights.org to ingest ATLAS dataset into the PRC (https://github.com/uc-cdis/covid19-tools/pull/131)
=> Whitelist opportunityinsights.org

gen3/bin/jupyter.sh
* patch `gen3 jupyter idle` to properly consider the length limit on ambassador cluster names - the `hatchery-reaper` should properly garbage collect hatchery pods with long names now ...
* patch `gen3 jupyter idle` to properly consider the length limit on ambassador cluster names - the `hatchery-reaper` should properly garbage collect hatchery pods with long names now ...
=> fix(jupyter): idle-check 42 char limit on name

kube/services/revproxy/gen3.nginx.conf/ambassador-service.conf
* revproxy sets `cache-control: no-store` for `lw-workspace/proxy`
* revproxy sets `cache-control: no-store` for `lw-workspace/proxy`
=> chore(revproxy): cache- no-store for ambassador

files/squid_whitelist/web_whitelist
dataguids.org has some JS code that performs an AJAX request against dataguids.org (hardcoded).
Ideally, this code should target the actual CI environment to properly test the DRS endpoints / indexd GUID lookup.
In the meantime, in order to unblock the remaining test scenarios, let us whitelist this domain to run the full test suite.
=> fix(qa): Enable communication between Selenium and dataguids.org

kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Tiny fix to guarantee the Selenium sidecar will be ready to run the test when the command is executed.
=> fix(qa): Better ReadinessProbe for gen3qa-check-bucket-access job

kube/services/selenium/selenium-hub-deployment.yaml
In several recent CI failures we are experiencing:
```
ETL "after each" hook: finalize codeceptjs for "run ETL second time @etl" – "after each" hook: finalize codeceptjs for "run ETL second time @etl"
<1s
Error
org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 6a9484aae701f02f8c5056b73bf86b80 Build info: version: '4.0.0-alpha-7', revision: 'f89bec1f87' System info: host: 'selenium-hub-5879985956-ztvsl', ip: '172.24.212.91', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.198-152.320.amzn2.x86_64', java.version: '1.8.0_275' Driver info: driver.version: unknown
``` 
According to the Selenium Hub logs, the session was created at:
`19:45:48` -> `"eventName": "Added session into local session map","attributes": {"logger": …
=> chore(qa): Bumping up Selenium session request timeout

kube/services/selenium/selenium-node-chrome-deployment.yaml
Fix this error:
```
ETL "after each" hook: finalize codeceptjs for "run ETL second time @etl" – "after each" hook: finalize codeceptjs for "run ETL second time @etl"
<1s
Error
org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 6a9484aae701f02f8c5056b73bf86b80 Build info: version: '4.0.0-alpha-7', revision: 'f89bec1f87' System info: host: 'selenium-hub-5879985956-ztvsl', ip: '172.24.212.91', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.198-152.320.amzn2.x86_64', java.version: '1.8.0_275' Driver info: driver.version: unknown
```
=> fix(ci): Adopt new selenium4 var SE_NODE_MAX_CONCURRENT_SESSIONS to configure more sessions per node

files/grafana/dashboards/ci-metrics.json, files/grafana/dashboards/general-ci-metrics.json, files/grafana/dashboards/jenkins-monitoring.json, files/grafana/dashboards/k6-load-testing-results.json, files/grafana/dashboards/selenium-observability.json
Let us keep a copy of our CI PIpeline's observability dashboards in case something wrong happens with our disk volumes.
=> chore(ci): Keeping a copy of our CI dashboards

gen3/bin/gen3qa-run.sh
Better polling logic to determine when the `selenium` sidecar is FULLY READY / up and running.
=> fix(gen3qa-run): Improve polling logic to wait for Selenium to be ready

Docker/python-nginx/python3.6-alpine3.7/nginx.conf
Keep nginx access log entries inline with Fence's app logs.
TODO:
Evidence:
```
jenkins-brain@cdistest_dev_admin:~$ kc logs fence-deployment-54fc575888-bjrfn -c fence | tail -n2
{"gen3log": "nginx", "date_access": "2020-12-21T22:13:05+00:00", "user_id": "-", 
"request_id": "-", "session_id": "-", "visitor_id": "-", "network_client_ip": "-", "network_bytes_write": 9096, 
"response_secs": 0.000, "http_status_code": 200, "http_request": "/aggregated_metrics", "http_verb": 
"GET", "http_referer": "-", "http_useragent": "Prometheus/2.7.1", 
"message": "GET /aggregated_metrics HTTP/1.1"}
--
jenkins-brain@cdistest_dev_admin:~$ kc get pod  fence-deployment-54fc575888-bjrfn -o yaml | grep image
image: quay.io/cdis/fence:chore_test_new_parent_img
```
=> chore(logs): Send nginx access log entries to stdout

Docker/python-nginx/python3.6-alpine3.7/Dockerfile
Adopting a copy of the image stored in our own Quay repo to avoid the following build error:
```
Could not pull base image: API error (500): toomanyrequests: You have reached your pull rate limit. 
You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Improvements
```
- Adopt quay.io image to avoid API error (500): toomanyrequests produced by Dockerhub.
=> chore(pybase): Adopt parent img from quay to avoid pull rate limit errors

gen3/bin/kube-roll-all.sh
* stagger usersync cron job to run between 20th and 40th minute of each hour
* stagger usersync cron job to run between 20th and 40th minute of each hour
=> chore(usersync): stagger cron job time

Docker/Jenkins-Worker/Dockerfile
Updating the NodeJs version from `10.x` to `14.x` in `jenkins-worker` docker file
=> chore: updating the NodeJS version in jenkins worker docker

kube/services/jobs/usersync-job.yaml
This is blocking this PR: https://github.com/uc-cdis/fence/pull/810/files
```
Running fence-create dbgap-sync with user.yaml - see /tmp/fence-create-output_kcmGnI
Traceback (most recent call last):
File "/usr/local/bin/fence-create", line 2, in <module>
from bin.fence_create import main
File "/fence/bin/fence_create.py", line 10, in <module>
from fence.jwt import keys
File "/fence/fence/__init__.py", line 60, in <module>
multiprocess.MultiProcessCollector(registry)
File "/usr/local/lib/python3.6/site-packages/prometheus_client/multiprocess.py", line 23, in __init__
raise ValueError('env prometheus_multiproc_dir is not set or not a directory')
ValueError: env prometheus_multiproc_dir is not set or not a directory
```
=> chore(usersync): Fix usersync for Fence PR #810 (Prometheus client integration)

files/squid_whitelist/web_whitelist
Jira Ticket: [PXP-5703](https://ctds-planx.atlassian.net/browse/PXP-5703)
Note: md.incommon.org is already there but md consumers [are to migrate](https://spaces.at.internet2.edu/display/MDQ/migrate-to-mdq) to this new url, mdq.incommon.org
- Add mdq.incommon.org, the new InCommon metadata service url, to squid whitelist
=> chore(squid-whitelist): add mdq.incommon.org

gen3/bin/kube-setup-prometheus.sh
Helm seems to add repositories only for the user that runs the command (helm repo add).
If we are hosting multiple namespaces on same adminvm then helm doesn't add the repository for each user and prometheus errors out.
=> Add helm repository if it's missing

files/squid_whitelist/web_whitelist
Adding `dap.digitalgov.gov` to the squid whitelist
=> chore(squid): dap.digitalgov.gov

kube/services/jobs/fence-visa-update-cronjob.yaml
Need to get [this](https://github.com/uc-cdis/fence/pull/869) approved first.
Still need to figure out timing such that this cron job doesn't overlap with the usersync. Currently testing in qa environment connected to RAS staging, for around 10 users with visas it takes around 7-8 seconds for this job to run. Would be nice to see how long it would take for more people with bigger visas.
- Added cron job to update all user visas hourly.
=> (PXP-6471) Cronjob to update visas hourly

gen3/lib/dcf/test_dcf.py, kube/services/jobs/usersync-job.yaml, tf_files/aws/encrypted-rds/kube.tf, tf_files/aws/rds/root.tf
Usersync sometimes gets stuck and will hang for days. Adding a 4 hour timeout for usersync jobs.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup
=> Add 4 hour timeout for usersync job

kube/services/jobs/nb-etl-cronjob.yaml
JIRA: COV-736
- The nb-etl job now takes several days to run (5 days in QA) - change the schedule to weekly (Thursday 6:00PM Chicago time)
=> nb-etl-cronjob cron on Thursdays 6:00PM

files/dashboard/usage-reports/src/base.css, files/dashboard/usage-reports/src/dataHelper.js, files/dashboard/usage-reports/src/index.html, files/dashboard/usage-reports/src/reportsMain.js, files/scripts/reports-cronjob.sh, gen3/bin/logs.sh, gen3/lib/logs/daily.sh
Jira Ticket: [HP-75](https://ctds-planx.atlassian.net/browse/HP-75)
- Add a few additional metrics to the reports-cronjob
- Number of logins per provider
- API invocation rates and response codes for `/ga4gh/drs/v1/objects` endpoint
- Signed URL rates split by provider (s3, gcs etc)
=> Add additional metrics to dashboard service

CSOC_Documentation.md, Jenkinsfile, gen3/bin/approve_vpcpeering_request.sh, tf_files/README.md
Jira Ticket: [DDI-106](https://occ-data.atlassian.net/browse/DDI-106)
- This script take an optional flag "--get-route-table" to find the route table id of the VPC which is accepting the peering request
Added new optional flag "--get-route-table"
when the older script was taking manual entries for route table, this will allow an option to programmatically get route table(s) from the accepter VPC
=> code added to get route tables automatically for VPC peering connection

Jenkinsfile
DEPENDS ON https://github.com/uc-cdis/cdis-jenkins-lib/pull/157
Making our list of CI environments dynamic:
https://cdistest-public-test-bucket.s3.amazonaws.com/jenkins-envs.txt
With this change we will be able to mutate the pool of CI environments on the fly.
This is a very powerful mechanism as it will allow us to:
- Lock envs for experiments (taking them out of rotation).
- Cordon environments to protect crime scenes in case we need to conduct some critical investigation.
- This is also a stepping stone for our ephemeral CI envs initiative.
- Instead of hardcoding the list of jenkins environments, we will utilize an easily mutable text file hosted in an S3 bucket.
=> Chore(ci): Dynamic ci envs pool

kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
Saw OOM for cluster-autoscaler a few times in qaplanetv1
https://github.com/kubernetes/autoscaler/issues/3506 
Upped the memory limit to 600mb
=> Fix OOM for cluster-autoscaler on startup

gen3/bin/kube-roll-all.sh
https://ctds-planx.atlassian.net/browse/PXP-7447
related to #1540
Fence waits a bit before crashing when audit logs are enabled but it can't reach audit-service, but deploying audit-service last during roll-all makes Fence wait for too long and the Fence pod ends up restarting until audit-service is up.
- Roll all: deploy audit-service before fence
=> PXP-7447 Roll all: deploy audit-service before fence

kube/services/jobs/covid19-notebook-etl-cronjob.yaml, kube/services/jobs/covid19-notebook-etl-job.yaml, kube/services/jobs/nb-etl-cronjob.yaml
Jira Ticket: [COV-807](https://occ-data.atlassian.net/browse/COV-807)
Goes with https://github.com/uc-cdis/covid19-tools/pull/188
- Make copies of the "nb-etl" files; rename them "covid19-notebook-etl". The new "covid19-notebook-etl" job (daily) only runs notebooks. The old files will stay here until we can completely deprecate the "nb-etl" job (weekly), which runs notebooks + the Bayes model. The "nb-etl" job will eventually be replaced by a "covid19-bayes-model" job that only runs the Bayes model.
=> Add covid19-notebook-etl job

tf_files/aws/modules/eks/cloud.tf
Since we occasionally get jupyter pods stuck waiting on scaling due to issues with EBS volumes being in different zones, this should speed up bringing up jupyter pods. We have to migrate all jupyter EBS volumes to a single AZ after applying this:
```
gen3 ebs jupyter-migrate us-east-1a 
```
=> restrict jupyter nodes to a single az

files/squid_whitelist/web_wildcard_whitelist
Add HEAL to squid whitelist to fix issue with workspace token service in HEAL preprod.
Slack thread: https://cdis.slack.com/archives/C01EEN7LW1E/p1617217431064100
=> Add HEAL to squid whitelist

Docker/python-nginx/python3.6-alpine3.7/Dockerfile
Notes from @m0nhawk:
"The curl command to install rustup is tricky, it’s not interactive (`-y`) and it only installs rustup, not the rust toolchain itself (hence the part with `stable`/`1.51`).
Having `stable` is not a good idea, it’s better be a specific version for reproducibility => using `1.51` instead.
And it doesn’t work as expected because of `PATH` — it’s Alpine and it won’t read `.profile` by default (I have no idea why), that’s why I edited it manually."
- Install Rust and Rust toolchain in `python-nginx` image to fix issues installing cyrptography
=> python-nginx base image Rust install

files/squid_whitelist/web_whitelist
Add download.pytorch.org to squid whitelist for @yilinxu's PRC notebook to download a googlenet model at https://download.pytorch.org/models/googlenet-1378be20.pth
=> Whitelist download.pytorch.org

files/squid_whitelist/web_wildcard_whitelist
Jira Ticket: n/a
Add `.okta.com` to squid web wildcard whitelist, in order to test Okta login flows.
The OIDC urls will look roughly like:
`https://*.okta.com/oauth2/default/.well-known/openid-configuration`
`https://*.okta.com/oauth2/default/v1/authorize`
etc; see [here](https://developer.okta.com/docs/reference/api/oidc/#well-known-openid-configuration) for more detail and [here](https://developer.okta.com/docs/guides/custom-url-domain/overview/) for more about Okta domains.
=> chore(squid-whitelist): Add .okta.com to wildcard wl

Jenkinsfile
The new signature for the runIntegrationTests function is:
```
def runIntegrationTests(String namespace, String service, String testedEnv, String isGen3Release, String isNightlyBuild = "false",  List<String> selectedTests = ['all']) {
```
This `Jenkinsfile` is missing the value for `isNightlyBuild`.
=> fix(ci): new runIntegrationTests function signature

gen3/bin/kube-wait4-pods.sh, gen3/bin/reset.sh, gen3/bin/save-failed-pod-logs.sh
Capture logs from failed pods when K8sReset fails.
- Capture logs from failed pods when K8sReset fails (before the k8s namespace is teared down).
=> fix(save-failed-pods-logs): Capture logs before namespace is wiped out

kube/services/revproxy/gen3.nginx.conf/fence-service.conf
**TLDR:
The revproxy currently implements CSRF checks using the cookie-to-header method.
Fence's new registration form, like other HTML forms, is not compatible with this method. The usual way to implement CSRF protection with HTML forms is using a hidden form field.
So here we exclude the Fence registration endpoints from the revproxy CSRF check. This is OK because Fence implements its own CSRF checks.**
Here is the relevant Fence PR (implementing registration endpoints) https://github.com/uc-cdis/fence/pull/906
For the record, more background on cloud-auto CSRF history:
Fence [has been operating](https://github.com/uc-cdis/fence/blob/61be960499434b39db8793f9cde37741f0709b26/fence/__init__.py#L398-L427) under the assumption that it manages its own CSRF token. 
But actually the revproxy …
=> (PXP-7565): Exclude Fence register-user blueprint from CSRF check

gen3/bin/save-failed-pod-logs.sh
Quick fix to run kubectl logs with both `pod_name` and `container_name`.
=> fix(save-logs): Fetch logs from failed pods when K8sReset fails

kube/services/portal/portal-deploy.yaml
Jira Ticket: [PXP-8080](https://ctds-planx.atlassian.net/browse/PXP-8080)
Disable npm 7 update notifier because it is causing Portal pods to stuck at starting up after 7 days
Doing this change in cloud-automation here so we don't need to cherry-pick for many old portal images
Will also have a PR for Portal for this fix so it can be applied to future images even if they are not being deployed using cloud-automation 
- Disable npm 7 update notifier because it is causing Portal pods to stuck at starting up after 7 days
=> PXP-8080 fix: disable npm notifier

Chef/repo/cookbooks/cdis_admin_vm/attributes/default.rb, Docker/Jenkins-Worker/Dockerfile, Docker/Jenkins/Dockerfile, flavors/adminvm/ubuntu-18-init.sh, flavors/vpn_nlb_central/vpnvm_ubuntu18.sh, gen3/bin/kube-setup-workvm.sh
Due to a security incident Hashicorp has updated the GPG keys used to sign its releases (including providers and plugins etc) 
That's why we see cloud-automation CI runs fail on Terraform tests. 
We need to bump them to a new version that support the new keys. 
Ref: 
https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570
=> Bump terraform version

Jenkinsfile, gen3/bin/kube-wait4-pods.sh, gen3/bin/reset.sh, gen3/bin/save-failed-pod-logs.sh
K8sReset fails with pods in `Running` mode but with several container restarts. We also need to capture these logs.
=> chore(ci-debugging): Capture logs from restarting pods

Docker/Jenkins-Worker/Dockerfile
Testing (determining 2nd Friday of the month):
```jenkins@jenkins-deployment-595d6846c8-8ts9g:/$ pip install pandas
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
Downloading pandas-1.2.4-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
...
jenkins@jenkins-deployment-595d6846c8-8ts9g:/$ python3
Python 3.8.0 (default, Feb 24 2021, 16:32:42)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.date_range('2021-05-01','2021-05-31',freq='WOM-2FRI')
DatetimeIndex(['2021-05-14'], dtype='datetime64[ns]', freq='WOM-2FRI')
```
=> chore(gen3-qa-worker): Add pandas to help with gen3 release date calculations

Docker/Jenkins-Worker/Dockerfile
Updating the installation for k6 when building the Quay Image
```
Failed to fetch https://dl.bintray.com/loadimpact/deb/dists/stable/InRelease 403 Forbidden [IP: 50.112.35.45 443]
5/22/2021, 1:06:04 AMThe repository 'https://dl.bintray.com/loadimpact/deb stable InRelease' is not signed.
```
The Root cause
=> update the Dockerfile for jenkins-worker

gen3/bin/mutate-etl-mapping-config.sh, gen3/bin/mutate-guppy-config.sh
In order to facilitate some automated testing involving the Explorer page through the creation of new Elastic Search indices and point Guppy to a new ephemeral ETL'ed data, we are introducing some automation to the Gen3 CLI so we can call these commands from the integration testing script.
=> chore(ci-automation): Introduce new Gen3 CLI cmds to mutate k8s configmaps

Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh, gen3/lib/g3k_manifest.sh, gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml, gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml, kube/services/fence/fence-deploy.yaml, kube/services/indexd/indexd-deploy.yaml, kube/services/peregrine/peregrine-deploy.yaml, kube/services/pidgin/pidgin-deploy.yaml, kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml, kube/services/sheepdog/sheepdog-deploy.yaml
=> feat(dd-apm): Added initial config for dd apm

gen3/bin/gen3qa-run.sh, kube/services/jobs/gen3qa-check-bucket-access-job.yaml
We should perform the bucket-access-check for both gs and s3 protocols. Not just for Google Buckets.
+ New gen3-qa-controller img version/
=> Fix(prod-test): Also scan s3 buckets in access check script 

gen3/bin/mutate-etl-mapping-config.sh, gen3/bin/mutate-guppy-config.sh
the change will now throw out an error with correct arguments to be passed if the command is missing one of the two arguments when executing the command
=> fix: throw errors on missing arguments and fix sed -i logic

files/squid_whitelist/web_wildcard_whitelist
* Add `anaconda.org` in addition to `anaconda.com` to the squid allow list
=> fix(squid): allow anaconda.org

Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
This is a 2-step process.
First we need to remove these instructions that gather all the metrics in the aggregated_metrics file
and then we disable the pod's side car containers on another PR.
Then we will successfully disable the Prometheus metrics scraping.
This PR needs to be merged first and the new base image has to be adopted by fence and indexd before we can move on to the next step.
=> chore(observability): Remove Prometheus metrics aggregation

files/squid_whitelist/web_whitelist
Related to #1641. That PR introduced a squid bug in that `*.anaconda.org` would overlap with existing rule `cloud.anaconda.org` and resulted in failed tests https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS_GitHub_Org%2Fcloud-automation/detail/PR-1641/1/pipeline/.
With the wildcard we should be fine to remove the explicit duplicate from the list.
=> fix(squid): remove redundant/overlapping rules

files/squid_whitelist/web_whitelist
- allow traffic to fwww.bc.edu, repec.org (ssc repositories) 
https://ctds-planx.atlassian.net/browse/HP-239
=> chore(ssc-dns): allow traffic to ssc repositories

Jenkinsfile
If we suspect jenkins-master is overwhelmed, we can send PR check jobs to this jenkins-ci-worker pod.
=> chore(ci): Introduce special label to run PR check on separate jenkins-ci-worker pod

Jenkinsfile, gen3/bin/save-failed-pod-logs.sh
We are facing issues with:
```
mariner-deployment-75897674bc-shc4x              0/1     CreateContainerConfigError   0          2m23s
```
Hence, we should add this pod status to the log-capturing logic so we can debug it before the crime scene is wiped out by subsequent PR checks.
=> chore(k8sReset-debugging): Capture logs from pods in CreateContainerConfigError state

gen3/bin/mutate-guppy-config-for-guppy-test.sh, gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
We need to be able to mutate the guppy config in our CI environments for 2 test flows:
- DYNAMIC data to test the end-to-end flow of the Export to PFB and Export to Workspace features.
- PREDEFINED data to test Guppy queries based on Queries and Expected Responses (based on Canine DD -- ES index pre-hydrated).
These two utility scripts will be instrumented by gen3-qa tests to help us mutate the k8s configmap to achieve both scenarios.
=> chore(ci): Introduce cli commands to mutate guppy config for CI purposes

gen3/bin/mutate-guppy-config-for-guppy-test.sh
The correct names for the aliases are:
```
"guppy": {
"indices": [
{
"index": "jenkins_subject_alias",
"type": "subject"
},
{
"index": "jenkins_file_alias",
"type": "file"
},
```
=> fix(ci): Fix Guppy mutation script again

gen3/bin/mutate-guppy-config-for-guppy-test.sh
Fix this issue:
```
[17:16:07] INFO: [ES.initialize] getting array fields from es config index "jenkins_config_alias"...
(node:6) UnhandledPromiseRejectionWarning: Error: index_not_found_exception
```
=> fix(ci): Fix Guppy mutation script again (again)

files/scripts/ci-env-pool-reset.sh
CI environments can, occasionally, be quarantined for experiments or due to configuration problems.
e.g.,
```
marcelo  3:20 PM
@qa-bot quarantine-ci-environment jenkins-new
```
This cronjob will reset the pool of CI environments every night in case someone forgets to return the environment to the pool.
=> chore(ci-env-pool): Reset CI environments pool every night

kube/services/portal/portal-deploy.yaml
Jira Ticket: [DEVOPS-62](https://ctds-planx.atlassian.net/browse/DEVOPS-62)
Pass Datadog RUM application ID and client token into Portal. They come from a k8s secret names `portal-datadog-config`
Example for `portal-datadog-config` secret
```
apiVersion: v1
kind: Secret
metadata:
name: portal-datadog-config
type: Opaque
stringData:
datadog_application_id: <MY_DD_APPLICATION_ID>
datadog_client_token: <MY_DD_CLIENT_TOKEN>
```
- Pass Datadog RUM application ID and client token into Portal
=> DEVOPS-62 feat: add datadog to portal

gen3/bin/reset.sh
If a PR is interrupted abruptly, this is never called:
```
AfterSuite(async ({ auditService }) => {
await auditService.do.configureFenceAuditLogging(false); // disable
```
source: https://github.com/uc-cdis/gen3-qa/blob/e9177b0f48fe229f3df4f9c6c698ca2c8736c448/suites/apis/auditServiceTest.js#L52
Therefore we must make sure the `fence-config` k8s secret is refreshed based on its local vm files at the very beginning of each CI run.
=> fix(ci): Reset fence-config secret on every k8sReset operation

kube/services/jenkins-ci-worker/jenkins-worker-ci-deployment.yaml, kube/services/jenkins-worker/jenkins-worker-deployment.yaml, kube/services/jenkins/jenkins-deploy.yaml, kube/services/selenium/selenium-hub-deployment.yaml, kube/services/selenium/selenium-node-chrome-deployment.yaml
This should prevent this:
```
$ kc get events | grep jenkins | grep -i down
11m         Normal    ScaleDown                                                                                      pod/jenkins-deployment-7d4b7f848-7pjl5                 deleting pod for node scale down
qaplanetv1@cdistest_dev_admin:~$
```
=> chore(ci-reliability): Prevent CI infra from being torn down by autoscaler

gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
The configuration is ending up with more double-quotation marks than we actually need.
e.g.,
```
{
"indices": [
{
"index": ""1520.gitops-qa.qa-dcp_subject"",
"type": "subject"
},
{
"index": ""1520.gitops-qa.qa-dcp_file"",
"type": "file"
}
],
"config_index": ""1520.gitops-qa.qa-dcp_file-array-config"",
"auth_filter_field": "auth_resource_path"
}
```
=> fix(ci): Mutate manifest-guppy cm properly

kube/services/jenkins-ci-worker/jenkins-worker-ci-deployment.yaml, kube/services/jenkins-worker/jenkins-worker-deployment.yaml, kube/services/jenkins/jenkins-deploy.yaml, kube/services/selenium/selenium-hub-deployment.yaml, kube/services/selenium/selenium-node-chrome-deployment.yaml
We are still facing problems:
```
3m46s       Normal    ScalingReplicaSet                                                                             deployment/jenkins-deployment                          Scaled down replica set jenkins-deployment-7d4b7f848 to 0
3m41s       Normal    ScalingReplicaSet                                                                             deployment/jenkins-deployment                          Scaled up replica set jenkins-deployment-857c7d6bfb to 1
39m         Normal    UpdatedLoadBalancer
```
=> chore(ci-reliability): Set cluster-autoscaler.kubernetes.io/safe-to-evict correctly

gen3/bin/mutate-guppy-config-for-guppy-test.sh
Fix this error:
```
ERROR: Tue Jul 27 2021 22:08:31 GMT+0000 (Coordinated Universal Time): The new guppy pod never came up with the expected indices.
```
Our jenkins-brain config is using `case` instead of `subject`:
https://github.com/uc-cdis/gitops-qa/blob/master/jenkins-brain.planx-pla.net/manifest.json#L292
And the pre-defined Canine-based index we use for Guppy tests MUST use index type = `subject`:
https://github.com/uc-cdis/gen3-qa/tree/master/suites/guppy/jenkinsSetup
Hence, we need to accommodate this mutation scenario as well.
=> fix(ci): Guppy test config mutation needs to switch from case to subject

gen3/bin/mutate-etl-mapping-config.sh, gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
The current regex that is used to mutate the etl-mapping config map
```
sed -i 's/.*- name: \(.*\)_file$/ - name: '"${prNumber}"'.'"${repoName}"'.\1_file/' etlMapping.yaml
```
is accidentally changing this line here from `gen3.theanvil.io/etlMapping.yaml`:
```
- name: capture_region_bed_file
```
To avoid the malformed yaml that breaks the ETL job, we must utilize a better `sed` instruction:
```
sed -i 's/^[[:space:]][[:space:]]- name: \(.*\)_file$/ - name: '"${prNumber}"'.'"${repoName}"'.\1_file/' etlMapping.yaml
```
=> fix(ci): Improve regex to mutate etl-mapping

gen3/bin/mutate-guppy-config-for-guppy-test.sh
there’s an extra comma after "subject"
```
$ kc get cm manifest-guppy -o yaml
apiVersion: v1
data:
auth_filter_field: auth_resource_path
config_index: jenkins-brain.planx-pla.net_array-config
indices: |-
[
{
"index": "jenkins_subject_alias",
"type": "subject",
},
```
=> fix(ci): Fix guppy test configmap mutation logic

kube/services/datadog/datadog-node-agent.yaml
Addition of statsd port to the agent yaml so that we could configure our own customizable metric inside datadog UI
=> Adding statsd port to the datadog node agent yaml

kube/services/jobs/gentestdata-job.yaml
The default 3600s token lifetime is not enough we need to generate a huge amount of fictitious data.
This change will allow us to override the token expiration time.
=> chore(gentestdata): Allow token expiry date override

kube/services/jobs/gen3qa-check-bucket-access-job.yaml
This will eliminate the need to invoke this test through the `gen3/bin/gen3qa-run.sh` script.
The new gen3-qa-controller image has the ability to run tests with an embedded `selenium-standalone` binary and a google chrome all within the same container (https://github.com/uc-cdis/gen3-qa/pull/668).
=> chore(gen3qa-check-bucket-access): Running gen3-qa tests + embedded selenium-standlone

kube/services/revproxy/nginx.conf
Jira Ticket: [PXP-8363](https://ctds-planx.atlassian.net/browse/PXP-8363)
Add `samesite="Lax"` to cookies of `session`, `visitor`, `csrftoken` and `service_releases`
This shouldn't breaks anything since some browsers (Chrome/Edge) has already been using `Lax`
as default value of `samesite` if not declared
To fix vulnerability documented in Veracode scan report (link in Jira ticket)
- Add `samesite="Lax"` to cookies of `session`, `visitor`, `csrftoken` and `service_releases`
=> PXP-8363 Fix/samesite cookie

gen3/bin/kube-setup-metadata.sh, kube/services/metadata/metadata-deploy.yaml
Jira Ticket: [HP-291](https://ctds-planx.atlassian.net/browse/HP-291), [HP-320](https://ctds-planx.atlassian.net/browse/HP-320)
* Create configuration scripts for metadata-service
* Move aggregate MDS configuration to our standard manifest config process
* Remove `USE_AGG_MDS` and `AGG_MDS_NAMESPACE` from `Gen3Secrets/g3auto/metadata/metadata.env` and set those variables in a `manifest: {}` block in `manifest.json`
* Migrate the appropriate agg MDS config to the relevant manifest repo under a `metadata/aggregate_config.json` path
* Run `gen3 kube-setup-metdata` and roll the metadata service in Kubernetes
=> feat(metadata): use manifest to drive config

Docker/Jenkins-CI-Worker/Dockerfile
Preparing new gen3-qa-in-a-box model where each PR check runs on its own ephemeral CI pod with a google chrome headless browser and a selenium-standalone (to eliminate the selenium-hub + nodes from the CI infra).
=> chore(gen3-qa-in-a-box): Prepare jenkins ci worker img for gen3 qa in a box

files/scripts/jenkins-cronjob.sh
fixing this:
```
g3kubectl exec -c jenkins "jenkins-ci-worker-deployment-79ffb9d56-7ddf9" -- bash -c " sudo find /home/jenkins/agent/workspace/ -name "GitHub_Org_*" -type d -mtime +5 -prune -print -exec /bin/rm -rf '{}' ';'"
Error from server (BadRequest): container jenkins is not valid for pod jenkins-ci-worker-deployment-79ffb9d56-7ddf9
```
=> fix(jenkins-disk-cleanup): Run command in the correct container

Docker/Jenkins-Worker/Dockerfile
Release automation task is failing due to:
```
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/site-packages (from cffi>=1.4.0->pygit2) (2.20)
Building wheels for collected packages: pygit2
Building wheel for pygit2 (PEP 517): started
Building wheel for pygit2 (PEP 517): finished with status 'error'
ERROR: Command errored out with exit status 1:
...
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.8/pygit2._libgit2.c'
creating build/temp.linux-x86_64-3.8
building 'pygit2._pygit2' extension
creating build/temp.linux-x86_64-3.8/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include -I/usr/local/include/python3.8 -c src/blob.c -o build/temp.linux-x86_64-3.8/src/blob.o
In file included from …
```
=> Fix/install libgit2 to unblock py3.8 automation

kube/services/indexd/indexd-deploy.yaml
Without a readinessProbe k8s won’t know when new pods are healthy enough to be placed in the rotation of the load balancers, which will result in ZDT during a `gen3 roll indexd` operation.
=> fix(zdt): Introduce readinessProbe to indexd

kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
We are experiencing some memory leak for autoscaler while running it in qaplanetv2:
```
kc get pods --all-namespaces | grep "cluster-autoscaler"
kube-system        cluster-autoscaler-655b7ff57b-gjrrj                         0/1     CrashLoopBackOff   4          4m29s
```
=> chore(autoscaling): Trying to fix autoscaler in qaplanetv2

kube/services/jobs/gen3qa-check-bucket-access-job.yaml
The job is currently failing in bdcat prod -- I think it's due to the lack of immutability around our dependencies.
We have faced the same issue in our CI Pipeline recently and we fixed it with this solution:
https://github.com/uc-cdis/gen3-qa/pull/696/files
=> fix(gen3qa-check-bucket-access): Pin chromedriver version to fix the gen3qa-check-bucket-access job

Docker/Jenkins-CI-Worker/Dockerfile
We should push more metrics to DataDog so we can achieve better monitoring for our CI processes related to gen3 CLI operations / PROD infra provisioning / batch jobs / etc.
=> chore(observability): Add datadog py lib to jenkins worker img

kube/services/hatchery/hatchery-deploy.yaml
- Hatchery deployment: change `HOSTNAME` to `GEN3_ENDPOINT`
=> change HOSTNAME to GEN3_ENDPOINT

gen3/bin/kube-setup-mariner.sh, kube/services/indexd/indexd-deploy.yaml, kube/services/mariner/auth, kube/services/mariner/mariner-deploy.yaml, kube/services/mariner/mariner-nfs-pv.yaml, kube/services/mariner/mariner-nfs-pvc.yaml
Jira Ticket: [PXP-8909](https://ctds-planx.atlassian.net/browse/PXP-8909)
- mariner persistent volume and persistent volume claim added as part of automatic deployment
- add mariner pod and mariner engine to indexd ingress policy
=> Feat/mariner deploy aws gateway.

kube/services/portal/portal-deploy.yaml
Increase data-portal livenessProbe failureThreshold to 10 because the PRC portal fails to come up
=> Increase data-portal livenessProbe failureThreshold to 10

tf_files/aws/modules/squid/cloud.tf, tf_files/aws/modules/squid/variables.tf
When deploying to a different AWS region than `us-east-1` the Terraform `aws_ami` data source cannot find the public AMI (as it is only available in `us-east-1`).
This PR adds a dedicated AWS provider configured to the `us-east-1` region to ensure the AMI can be found even if the deployment (and the base provider) is configured for another region.
It also tries to remove hard coded values by adding variables and using existing parameters.
=> fix(tf-squid-module): add cross region support

tf_files/aws/modules/eks/cloud.tf, tf_files/aws/modules/eks/variables.tf
Remove dependency on hardcoded default AvailabilityZones. Replace
with dynamic lookup from current aws_availability_zones data source.
Removes the dependency of the EKS TF module on the availability_zones hardcoded default values, and the need for custom configuration, while retaining the option to configure the AZs if required.
=> fix (AWS EKS module update)

kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml
Jira Ticket: [HP-623](https://ctds-planx.atlassian.net/browse/HP-623)
Fixing intermittent issue of  `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` from aggMDS sync job
`aws-es-proxy` was changed to use a customized HTTP client from verison 1.0+, and this new client is the cause of throwing these timeout issues
Pass an option `-timeout` to increase its timeout from 15s (default) to 180s, note this option is oly supported from version `1.2+`
- Increase timeout for `aws-es-proxy` client
- Envs that is using `AggMDS` should consider to use `aws-es-proxy: 1.2+`
=> HP-623 Fix/aws es timeout

files/squid_whitelist/web_whitelist, files/squid_whitelist/web_wildcard_whitelist
Adding `.slack.com` to wildcard whitelist
=> Adding .slack.com to wildcard-whitelist

gen3/bin/kube-setup-access-backend.sh
Removes 'workspace' policy from 'all_users_policies' in the default useryaml used by access-backend. This will prevent access-backend PRs from automatically adding in the 'workspace' policy to all users, which we want to avoid.
=> Stop access-backend from giving random users workspace access

Docker/Jenkins-CI-Worker/Dockerfile
putting an early change in to wipe out quay build cache
=> invalidated the quay build cache

files/squid_whitelist/web_whitelist
adding argoproj.github.io to squid whitelist to install argo in vhdc prod
=> feat add argo to squid whitelist

gen3/lib/logs/snapshot.sh
Jira Ticket: [PXP-9536](https://ctds-planx.atlassian.net/browse/PXP-9536)
`gen3 logs snapshot` fails to snapshot all pods' logs when it encounters a pod in the "Pending" phase. For an example, please search for "snapshot" on the [RunTests stage of a recent Nightly Builds Jenkins run](https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS_GitHub_Org%2Fcdis-manifest/detail/PR-4202/1/pipeline/354) and also see [the incomplete list of snapshotted logs](https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS_GitHub_Org%2Fcdis-manifest/detail/PR-4202/1/artifacts/).
- Fix `gen3 logs snapshot` so that it no longer fails when a pod is in the "Pending" phase.
=> (PXP-9536): fix `gen3 logs snapshot` when there are "Pending" pods

apis_configs/user.yaml, gen3/bin/kube-setup-fenceshib.sh, gen3/bin/kube-setup-peregrine.sh, gen3/bin/kube-setup-pidgin.sh, gen3/bin/kube-setup-sftp.sh, gen3/bin/kube-setup-sheepdog.sh, gen3/bin/kube-setup-spark.sh, gen3/bin/kube-setup-tty.sh
- Fix the default user.yaml so it passes validation
=> Default user.yaml passes validation

files/squid_whitelist/web_whitelist
whitelist apt.kubernetes.io - Kubernetes apt repository
whitelist apt.kubernetes.io - Kubernetes apt repository
=> chore: Whiteslist apt.kubernetes.io

flavors/squid_auto/squid_running_on_docker.sh, flavors/squid_auto/updatewhitelist-docker.sh, flavors/squid_auto/updatewhitelist.sh, flavors/squid_nlb/updatewhitelist.sh, flavors/squid_nlb_central/updatewhitelist.sh, tf_files/aws/commons/cloud.tf, tf_files/aws/commons/variables.tf, tf_files/aws/modules/squid_auto/cloud.tf, tf_files/aws/modules/vpc/cloud.tf, tf_files/aws/modules/vpc/variables.tf
Enable squid to be ran on amazon linux 2 instances. We can use custom ami's f.ex an AMI with FIPS enabled. 
To override default behaviour (ubuntu instance) we need to supply the following variables 
```
squid_image_search_criteria = "amazon-eks-node-1-21*"
ami_account_id="707767160287"
ha-squid_instance_drive_size=25
branch="feat/squid_al2"
```
Also attaching SSM IAM policy so we can use ssm to manage instances in case ssh isn't working.
=> Enable squid running on AL2

kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml, kube/services/revproxy/gen3.nginx.conf/fence-service-ga4gh.conf, kube/services/revproxy/gen3.nginx.conf/fence-service.conf
Remove unnecessary `revproxy` timeouts for `fence` and `presigned-url-fence` services. A revert of #1804, which is no longer necessary after performance improvements to Fence sync code.
=> Remove unnecessary revproxy timeouts for fence and presigned-url-fence

kube/services/revproxy/gen3.nginx.conf/cohort-middleware-service.conf
Jira Ticket: [PXP-9789](https://ctds-planx.atlassian.net/browse/PXP-9789)
* Closing external access to cohort-data/* endpoints. The cohort-data endpoints should  only be used by internal services, and never be exposed to users/browsers.
=> close external calls to cohort-data/* endpoints

kube/services/revproxy/gen3.nginx.conf/dicom-server-service.conf
- DICOM server: no limit to payload size so we can upload large DICOM files
=> dicom-server client_max_body_size 0

Docker/Jenkins2/Dockerfile, Docker/Jenkins2/install-python3.8.sh
=> install all tools on jenkins2

doc/gitops.md, gen3/bin/gitops.sh, gen3/bin/mutate-etl-mapping-config.sh, gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
Jira Ticket: [PXP-9849](https://ctds-planx.atlassian.net/browse/PXP-9849)
Previously, `gen3/bin/mutate-guppy-config-for-pfb-export-test.sh` assumed that the first and second entires in the `etlMapping.yaml` are `subject` and `file` types, respectively. However, `subject` [appears as the second entry in PRC's etlMapping.yaml](https://github.com/uc-cdis/cdis-manifest/blob/620ff071135db7064d3a625b3b9a87e6db19c258/chicagoland.pandemicresponsecommons.org/etlMapping.yaml#L166), resulting in a guppy config with mismatched types (e.g. an index `4509.cdis-manifest.covid19_subject` having type `file` (see Guppy logs in ticket)).
[Guppy pod has been failing to start](https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS_GitHub_Org%2Fcdis-manifest/detail/PR-4509/3/tests) during PFB Export …
=> (PXP-9849): Fix mutate-guppy-config-for-pfb-export-test.sh so that index and type match

files/squid_whitelist/web_whitelist
Add data.cityofchicago.org to squid whitelist
For PRC ETL https://github.com/uc-cdis/covid19-tools/pull/265
=> Add data.cityofchicago.org to squid whitelist

files/scripts/ci-env-pool-reset.sh
Removing `jenkins-perf` from the pool of jenkins test environment so we can do performance tests without the environment being reset.
=> removing jenkins-perf from jenkins test pool

.secrets.baseline, kube/services/ohdsi-atlas/README.md, kube/services/ohdsi-atlas/config-local.js
Jira Ticket: [PXP-9641](https://ctds-planx.atlassian.net/browse/PXP-9641)
- code to let Atlas send "keep session alive" messages to its parent (when Atlas is running in iframe)
=> Create config-local.js including iframe "keep alive" code

tf_files/aws/commons/kube.tf
This fixes an issue in cloud-automation where if a Postgres newer than 9.6 is deployed terraform will fail. The reason is that the parameter group version is not in sync with the engine version. 
This patch will derive the parameter group version. This will not work with posture < 10 
does not work with Postgres < 10 (which is out of support @ AWS anyways)
=> derive postgres parameter group version

tf_files/aws/commons/cloud.tf, tf_files/aws/commons/variables.tf
This hands down the availability zones configured in config.tf to the VPC module.
Make sure to follow the DEV guidelines (https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Describe what this pull request does.
Hand down availability zones configured in config.tf to the VPC module, allowing deployment outside of us-east-1
- Add short descriptive bullet points for each section if relevant. Keep in mind that they will be parsed automatically to generate official release notes.
- Test manually.
- Maintain or increase the test coverage (if relevant).
- Update the documentation, or justify if not needed.
-->
=> Availability zones outside of us-east-1

kube/services/fence/fence-deploy.yaml, kube/services/jobs/fence-db-migrate-job.yaml
Jira Ticket: [PXP-8028](https://ctds-planx.atlassian.net/browse/PXP-8028)
To run Fence DB migrations with Alembic, we need Alembic to be able to find its configuration files, which are at `/fence`
=> PXP-8028 Fence DB migration: cd to where it can find Alembic files

gen3/bin/kube-setup-revproxy.sh, kube/services/revproxy/gen3.nginx.conf/documentation-site/documentation-site.conf, kube/services/revproxy/nginx.conf, kube/services/revproxy/revproxy-deploy.yaml
In the future we would like to improve this from using `redirect` to `proxy_pass` so we can preserve the URL in browser
- specific a `document_url` in `manifest-global` to let `<HOSTNAME>/documentation` redirects to that external doc site
=> feat: add doc url

tf_files-1.0/aws/modules/eks/cloud.tf
adding a line to ignore custom suffix changes for the service_linked_role to prevent the "autoscaling" role from being destroyed and re-created. This will make things easier for us when migrating other commons to tf1.
=> adding a line to ignore custom suffix changes for the service_linked_role

files/squid_whitelist/web_wildcard_whitelist
Adding .pedscommons.org to whitelist
=> adding .pedscommons.org to whitelist

gen3/bin/kube-setup-hatchery.sh, kube/services/hatchery/hatchery-deploy.yaml
Jira Ticket: [BRH-301](https://ctds-planx.atlassian.net/browse/BRH-301)
- Add ability to launch prismacloud containers using hatchery for security purposes. 
- Currently requires to manually update prisma api key in json format under this path in the adminvm 
- `~/Gen3Secrets/prisma/apikey.json` 
- format has to be the following: 
```
{
"AccessKeyID": "XXXX",
"SecretKey": "XXXX"
}
```
This PR extends `kube-setup-hatchery` to create a kubernetes secret with for prisma cloud credentials, and extending the hatchery deployment to look for this secret and use it, if it exists.
=> BRH-301: Extend hatchery to launch prismacloud containers

gen3/bin/job.sh, gen3/bin/kube-setup-networkpolicy.sh, kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
- Updated cronjob apiVersion to `batch/v1` from `batch/v1beta1` that is deprecated. 
- Small fix for network-policies to get the server version
- Gave cluster-autoscaler more memory/cpu and permissions
=> Fix apiversion of cronjobs and fix cluster-autoscaler

doc/kube-setup-revproxy.md, gen3/bin/kube-setup-revproxy.sh
Jira Ticket: [GPE-679](https://ctds-planx.atlassian.net/browse/GPE-679)
We are deprecating the Revproxy Service ELB in favor of an AWS ALB. We strongly recommend deploying the AWS ALB via kube-setup-ingress instead.
Documentation was updated to reflect this change. Please see [kube-setup-revproxy.md](https://github.com/uc-cdis/cloud-automation/blob/master/doc/kube-setup-revproxy.md) and [kube-setup-ingress.md](https://github.com/uc-cdis/cloud-automation/blob/master/doc/kube-setup-ingress.md)
**Improvements**
The Revproxy Service ELB is no longer deployed by default. You now have to add/set the new "deploy_elb" flag to true in the "manifest-global" configmap to deploy it.
The previous PR was merged without release notes. Lines 16-21, 264-266, 292-298 were added to the "kube-setup-revproxy" …
=> updated revproxy documentation

gen3/bin/kube-setup-argocd.sh, kube/services/netpolicy/gen3/services/argocd_netpolicy.yaml, kube/services/revproxy/gen3.nginx.conf/argocd-server.conf
- adding networkpolicies for argocd
- annotating the argocd namespace for network policy use
- fixing the indentation in the argocd nginx conf file
=> Fixing the argocd setup script

kube/services/jenkins/rolebinding-devops.yaml
the gitops-sa account was not able to access the argo namespace because the default namespace was not provided to reference gitops-sa.
=> the gitops-sa account was not able to access the argo namespace

kube/services/jobs/opencost-report-argo-job.yaml
Removing extra `}` in slack curl request causing slack messages to fail.
=> fix(opencost): remove extra curly bracket

.secrets.baseline, gen3/bin/kube-setup-argo.sh
Adding a lifecycle policy for the argo bucket to the kube-setup-argocd script. Please see [GPE-544](https://ctds-planx.atlassian.net/browse/GPE-544) for more details.
=> editing kube-setup-argo script to contain a lifecycle policy

gen3/bin/waf-rules-GPE-312.json
The changes that were made: 
- Changed the AWS-AWSManagedRulesCommonRuleSet from version 1.3 to version 1.4
- Changed AdminProtection_URIPATH rule to override "Challenge"
- Added AWS-AWSManagedRulesLinuxRuleSet
- SizeRestrictions_Cookie_HEADER - Allow
- SizeRestrictions_BODY - Allow
- SizeRestrictions_URIPATH - Allow
- SizeRestrictions_QUERYSTRING - Count
- CrossSiteScripting_BODY - Count
- Removed the bot rules set entirely
=> Made a few updates to the WAF rules after testing.

.secrets.baseline, gen3/bin/kube-setup-argo.sh
editing the kube-setup-argo script to prevent it from deleting the s3 cred secret in the argo ns if run a non-default ns since it won't be re-created in that case.
=> s3-creds Secret 

kube/services/datadog/values.yaml
removing the system-probe container for datadog due to container crash with fips (please refer to GPE-783 for more information.
=> removing the system-probe container from datadog

kube/services/portal/portal-deploy.yaml, kube/services/portal/portal-root-deploy.yaml
Limits are needed to prevent pods from using more resources than the limits. In this case there is high resource usage only at the start and is not really an issue once it stablizes.
On the flip side, very high values in limits make it hard for the pod to get scheduled since k8s looks for a node that has more capacity than the limits specified.
So having 4 cpu and 4 GB limits is only slowing down starting the service, not really protecting from pod being too expensive.
=> Remove limits in portal kube config

files/squid_whitelist/web_whitelist
The URL for the PRC job has changed: https://github.com/uc-cdis/covid19-tools/pull/273
=> Whitelist biorender.com => marketing.biorender.com

kube/services/argo/values.yaml
We have recently changed the amount of workflows allowed at once on Prod to be 3 (down from 10). This will change back to 10 every time we deploy Argo.
=> changing "parallelism" parameter from 10 to 3 per GPE-876

gen3/bin/kube-setup-sheepdog.sh
updating the kube-setup-sheepdog script so it can grant access to the new qa peregrine users for the devplanetv2 migration.
=> updating the kube-setup-sheepdog script for qa environments

Jenkinsfile, kube/services/jobs/etl-cronjob.yaml, kube/services/jobs/fence-db-migrate-job.yaml, kube/services/jobs/fence-visa-update-cronjob.yaml, kube/services/jobs/fence-visa-update-job.yaml, kube/services/jobs/s3sync-cronjob.yaml, kube/services/jobs/usersync-job.yaml
For qa environments, we want the slack notifications to display the specific environment instead of "qaplanetv1"
=> Switch gen3Env to hostname instead of environment

gen3/bin/kube-setup-metadata.sh
- don't run unnecessary cm sync when seting up MDS if rolling all
=> fix: don't run unnecessary cm sync if rolling all

kube/services/datadog/values.yaml
Remove pelican export log ingestion due to too excess logging.
=> fix(pelican-log-ingestion): Remove pelican export log ingestion

gen3/bin/kube-setup-system-services.sh, tf_files/aws/modules/eks-nodepool/cloud.tf, tf_files/aws/modules/eks/cloud.tf
adding EBSCSI Driver policy to the EKS Workers policy as the CSI Driver is required for clusters above 1.23
=> EBSCSI Driver policy

Docker/awshelper/Dockerfile
We were getting the following error due to an issue with pyyaml 5.4:
#12 22.63           raise AttributeError(attr)
#12 22.63       AttributeError: cython_sources
#12 22.63       [end of output]
please see: https://github.com/yaml/pyyaml/issues/724
pinning the pyyaml version until it is resolved.
=> pinning the pyyaml version due to bug.

flavors/squid_auto/startup_configs/squid.conf
Removing squid cache to see if that resolves self-signed certificate errors we have been seeing with our Java applications. Tested this change in qaplanetv1, devplanetv2/qaplanetv1, and unfunded clusters.
=> Removing Squid Cache

files/squid_whitelist/web_whitelist
add  proxy.golang.org to squid web whitelist
=>  update squid web whitelist

kube/services/monitoring/values.yaml
adding node affinity, to prevent prometheus exporter pods from getting created for fargate nodes
=> adding a toleration to prometheus

kube/services/datadog/datadog-application.yaml
- Requires argocd 2.6.1+ so run `gen3 kube-setup-argocd` first, or manually upgrade argocd to newest verison.
=> Add values from external git repository

files/scripts/healdata/heal-cedar-data-ingest.py
- HEAL CEDAR ingestion script: ignore study metadata record that is neither unregistered nor registered
=> fix: skip study if it is neither registered nor unregistered

gen3/bin/gitops.sh
Tested manually
gitops sync will fail if there is a json syntax error anywhere in the manifest.json
=> GPE-1122 adding logic to exit a gitops sync if the new json contains invalid json

gen3/bin/create-es7-cluster.sh
This script will allow users to spin up a new elasticsearch 7 cluster that will use the same settings as the existing elasticsearch 6 cluster in preparation for a blue/green deployment. It will extract VPC, instance type, instance quantity, EBS storage size, KMS key, access policy, etc.
=> Gen3 Command to Create a New ES7 Cluster with the Same ES6 Cluster Settings

.secrets.baseline, gen3/bin/awsrole.sh, gen3/bin/kube-setup-argo.sh, kube/services/argo/workflows/fence-usersync-cron.yaml, kube/services/argo/workflows/fence-usersync-wf.yaml
making changes to allow argo workflows to run from any namespace. In this case, we need this functionality to be able to run the "usersync" argo workflow job and usersync must run in the namespace in question and not in the "argo" namespace.
=> Argo Changes to Allow Workflow Runs From All NS

Docker/jenkins/Jenkins-CI-Worker/Dockerfile, Docker/jenkins/Jenkins-Worker/Dockerfile
=> fix: java installation

.github/workflows/image_build_push.yaml, .github/workflows/image_build_push_jenkins.yaml, .github/workflows/image_build_push_squid.yaml, .secrets.baseline, Docker/jenkins/Jenkins-CI-Worker/Dockerfile, Docker/jenkins/Jenkins-Worker/Dockerfile, kube/services/jobs/usersync-job.yaml
Data simulator now uses python 3.9, see https://github.com/uc-cdis/data-simulator/pull/99
Add setuptools to the Jenkins-CI-Worker image to fix `No module named 'distutils.cmd'` error ([ref](https://github.com/pypa/get-pip/issues/124))
Upgrade `git` version
And fix java install
=> Jenkins dockerfiles improvements

kube/services/ohdsi-webapi/ohdsi-webapi-config.yaml, kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
Jira Ticket: [VADC-775](https://ctds-planx.atlassian.net/browse/VADC-775)
- Add new config for integrating teamproject and arborist check: these properties are needed for enabling "teamproject" authorization mode in WebAPI and telling WebAPI where the Arborist endpoint is living for actually getting authorization information.
- The WebAPI deployment now depends not only on Fence, but also needs a direct link to Arborist
- This assumes Arborist and WebAPI are on the same internal network
[VADC-775]: https://ctds-planx.atlassian.net/browse/VADC-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: add new config for integrating teamproject and arborist check

gen3/bin/kube-setup-ohdsi.sh, kube/services/ohdsi-webapi/ohdsi-webapi-config.yaml, kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
Jira Ticket: [VADC-775](https://ctds-planx.atlassian.net/browse/VADC-775)
- reverts https://github.com/uc-cdis/cloud-automation/pull/2397 , to set ARBORIST_URL using the `gen3/bin/kube-setup-ohdsi.sh` script
- compared to previous PR, this one assumes the arborist service is located on the same host as OHDSI - WebAPI
[VADC-775]: https://ctds-planx.atlassian.net/browse/VADC-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: set ARBORIST_URL using the kube-setup-ohdsi.sh

files/squid_whitelist/web_whitelist
Needed to connect to Regenstrief's Rabbitmq server from a MIDRC VM (`regenstrief-uchicago-rabbitmq`)
=> Add rmq.n3c.ncats.io to Squid whitelist

kube/services/revproxy/gen3.nginx.conf/guppy-service.conf
Jira Ticket: [PPS-588](https://ctds-planx.atlassian.net/browse/PPS-588)
- Add CSRF protection for Guppy paths
- After merging this, envs must use a data-portal version that contains https://github.com/uc-cdis/data-portal/pull/1464. Otherwise the communication between portal and guppy will be interrupted
[PPS-588]: https://ctds-planx.atlassian.net/browse/PPS-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PPS-588 add guppy csrf

gen3/bin/kube-setup-system-services.sh, kube/services/karpenter/nodeTemplateDefault.yaml, kube/services/karpenter/nodeTemplateGPU.yaml, kube/services/karpenter/nodeTemplateJupyter.yaml, kube/services/karpenter/nodeTemplateWorkflow.yaml, kube/services/revproxy/revproxy-deploy.yaml
- Adding "internet: yes" label
We are switching off of Calico to AWS VPC CNI to manage our network policies. We believe AWS VPC CNI to have more restrictive defaults than our previous version of Calico, so revproxy needs to have an explicit allow for all egress traffic. 
- Updating AWS VPC CNI version
We are moving off of Calico and to AWS VPC CNI to manage our networkpolicies. The VPC CNI plugin is able to manage network policies in version 1.14.1
- Mounting the BPF File System
Mounting this file system in the "user data" section of all our Karpenter node templates as this is required for the VPC CNI plugin to manage network policies
=> VPC CNI Migration From Calico

gen3/bin/migrate-to-vpc-cni.sh, kube/services/karpenter/nodeTemplateDefault.yaml, kube/services/karpenter/nodeTemplateGPU.yaml, kube/services/karpenter/nodeTemplateJupyter.yaml, kube/services/karpenter/nodeTemplateWorkflow.yaml
adding a script that will allow users to migrate to use the AWS VPC CNI to manage networkpolicies after upgrading their cluster to 1.25
=> adding "migrate to vpc cni" script to cloud-auto

kube/services/ingress/ingress.yaml
updating the security policy used for https listener to be newer and fips compliant.
=> Update ingress.yaml to use newer fips based tls policy

packer/configs/web_wildcard_whitelist
- Add azure blob storage to web_wildcard_whitelist
=> Add azure blob storage to web_wildcard_whitelist

gen3/lib/logs/snapshot.sh
- `gen3 logs snapshot`: in addition to `containers` logs, also get `initContainers` logs
=> gen3 logs snapshot: also get initContainers logs

.secrets.baseline, files/scripts/healdata/heal-cedar-data-ingest.py
Fixed a bug in the cedar ingestion script
=> fix cedar ingestion problems

files/dashboard/maintenance-page/index.html
Add alt text to maintenance page images
=> Add alt text to maintenance page images

gen3/bin/iam-serviceaccount.sh, gen3/bin/kube-setup-ecr-access-cronjob.sh
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-672
- ECR access job: fix conflict during role creating when the role name already exists for a different namespace in the same AWS account
=> MIDRC-672 Fix ECR access job role name conflict

gen3/bin/kube-setup-ohdsi.sh
- Instead of deleting existing fence-client, we want the script to fail if `fence-create create-client` command fails.
=> Fail if fence-create client fails in kube-setup-ohdsi

kube/services/jobs/arborist-rm-expired-access-cronjob.yaml, kube/services/jobs/covid19-bayes-cronjob.yaml, kube/services/jobs/etl-cronjob.yaml, kube/services/jobs/fence-visa-update-cronjob.yaml, kube/services/jobs/google-delete-expired-access-cronjob.yaml, kube/services/jobs/google-delete-expired-service-account-cronjob.yaml, kube/services/jobs/google-init-proxy-groups-cronjob.yaml, kube/services/jobs/google-manage-account-access-cronjob.yaml, kube/services/jobs/google-manage-keys-cronjob.yaml, kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml, kube/services/jobs/healthcheck-cronjob.yaml, kube/services/jobs/s3sync-cronjob.yaml
Updated deprecated cronjob apis
=> fix(cronjob-apis): Updated decprecated cronjob apis

gen3/bin/kube-setup-cedar-wrapper.sh
- Skip setting cedar ingestion client creds in CI
=> fix: skip setting up cedar-ingest client cred in ci

gen3/bin/kube-roll-all.sh
When indexd starts before arborist comes up, errors like this are observed:
```
[fence.blueprints.data.indexd][  ERROR] could not create new record in indexd; got response: {'error': 'Arborist is not configured; cannot perform authorization check'}
```
=> Roll arborist before indexd

kube/services/netpolicy/gen3/services/sower_netpolicy.yaml, kube/services/netpolicy/gen3/services/ssjdispatcherjob_netpolicy.yaml
PFB exports are not working when networkpolicies are deployed. It appears that this was due to an error with the networkpolicy for sowerjobs, so I am correcting that here.
=> correcting networkpolicy format for ssjdispatcher and sower

gen3/bin/kube-setup-aws-es-proxy.sh, kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml, kube/services/aws-es-proxy/aws-es-proxy-priority-class.yaml, kube/services/jobs/etl-cronjob.yaml, kube/services/jobs/etl-job.yaml
adding a priority class for aws-es-proxy and adding larger requests for etl-job to test in CI environment
=> Priority Class and More Resource Requests

gen3/bin/kube-setup-hatchery.sh
Jira Ticket: [ISO-1859](https://ctds-planx.atlassian.net/browse/ISO-1859)
- Give hatchery access to Cost Usage Report in AWS, so that hatchery can report on user level compute costs. 
[ISO-1859]: https://ctds-planx.atlassian.net/browse/ISO-1859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add CUR access IAM policy to hatchery

gen3/bin/kube-setup-cohort-middleware.sh, kube/services/ohdsi-atlas/ohdsi-atlas-config-local.yaml
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1063
- new config to enable "global cohorts" feature in Atlas and cohort-middleware
=> Feat: new settings for the "global cohorts" feature

files/scripts/healdata/heal-cedar-data-ingest.py, kube/services/jobs/cedar-ingestion-job.yaml
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-1520
To support clinicaltrials.gov API V2 for HEAL CEDAR ingestion job
- HEAL CEDAR ingestion: don't update clinicaltrials.gov from CEDAR values
=> HP-1520 Fix/ct gov

files/squid_whitelist/web_whitelist
charts.bitnami.com is in the squid_whitelist twice
=> Removing duplicate value

files/squid_whitelist/web_whitelist
Simply adding https://data.qdr.syr.edu/ to the whitelist to allow for HEAL functionality
=> adding qdr production to squid whitelist

gen3/bin/awsrole.sh, gen3/bin/kube-setup-argo.sh
The argo UI uses a separate service account, so that service account needs to be annotated with the aws Role so artifacts can be viewed in the UI
=> adding changes to give argo UI access to buckets so artifacts can be viewed in the UI

kube/services/argo/values.yaml
Link to JIRA ticket if there is one: N/A
* [`any`](https://jqlang.github.io/jq/manual/#any) in jq will return string for either true or false, so bash needs to have string comparison
=> fix: bash comparison for true values in argo slack webhook notify

files/scripts/config-update.sh
script to update the gen3 secrets after migration
=> script to update the gen3 secrets after migration

gen3/bin/kube-setup-cluster-level-resources, kube/services/cluster-level-resources/app.yaml
=> Up-to-date setup for cluster-level resources

gen3/test/bootstrapTest.sh, gen3/test/fenceStuffTest.sh, kube/services/ohdsi-atlas/ohdsi-atlas-config-local.yaml, kube/services/ohdsi-webapi/ohdsi-webapi-config.yaml, tf_files/aws/modules/eks/lambda.tf
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1241
- feat: set webapi token expiration to 15 min and refresh when 4 min left to simulate a session timeout (inactivity timeout) of 15 min
=> Feat: set webapi token exp. to 15 min and refresh when 4 min left

kube/services/karpenter/nodeTemplateDefault.yaml, kube/services/karpenter/provisionerDefault.yaml
=> Changing karpenter config to rely on pre-FIPS'd images

gen3/bin/jupyter.sh, gen3/bin/kube-setup-ambassador.sh, gen3/bin/prometheus.sh, kube/services/jobs/hatchery-reaper-job.yaml
making changes so hatchery reaper job relies on mimir instead of Prometheus. Also, removing Prometheus from "kube-setup-ambassador"
=> Using Mimir for Hatchery Reaper Job

kube/services/jobs/indexd-single-table-migration-job.yaml, kube/services/jobs/indexd-single-table-migration.yaml
- Add job to migrate to single table indexd
=> (PPS-819): Indexd Migration Script

gen3/bin/s3.sh
* gen3_s3_info check for existing bucket
=> fix: gen3_s3_info check for existing bucket

gen3/bin/kube-setup-aws-es-proxy.sh
Elasticsearch 7 endpoint will be the default. If you want to use ES6, make sure to set "ES7" "false" in the manfist.json.
=> Making ES7 domain default

kube/services/jobs/psql-db-copy-aurora-job.yaml
fix to include special characters in db name
=> fix to include special characters in db name

kube/services/jobs/indexd-userdb-job.yaml
The new indexd image uses poetry to manage the virtual environment, so we need the job logic to work with the new image. To do this, the job should work with either the "python" command or "poetry run python" command.
=> updating userdb job to work with new al images

kube/services/ohdsi-webapi/ohdsi-webapi-config.yaml
Link to JIRA ticket if there is one:  https://ctds-planx.atlassian.net/browse/VADC-1554
- fixes error `Two authorization rules expected for ‘teamproject’=/abc, found=3` by using the `/authz/request` endpoint instead of `/authz/mapping`
- see also https://github.com/uc-cdis/WebAPI/pull/166
=> Fix: use /auth/request instead of /auth/mapping Arborist endpoint

.gitignore, gen3/bin/kube-roll-all.sh, gen3/bin/kube-setup-gen3-user-data-library.sh, kube/services/gen3-user-data-library/gen3-user-data-library-deploy.yaml, kube/services/gen3-user-data-library/gen3-user-data-library-service.yaml, kube/services/revproxy/gen3.nginx.conf/gen3-user-data-library-service.conf
Link to JIRA ticket if there is one:  [BDC-326
](https://ctds-planx.atlassian.net/issues/BDC-326?jql=ORDER%20BY%20created%20DESC)
- Adds gen3-user-data-library
=> feat(BDC-326): Adds gen3-user-data-library

apis_configs/indexd_multi_table/indexd_settings.py, gen3/bin/kube-setup-indexd.sh
dcf prod needs to use a new "indexd_settings.py" file in order to use the new single table for indexd. We can add a new settings.py file that will look in the "indexd_multi_table" directory for this configuration. 
The kube-setup-indexd script will check the manifest.json to see if "indexd_single_table" is set to "true".
=> updating the kube-setup-indexd job to apply single table driver settings.py for specific environments.

.secrets.baseline, Jenkinsfile, gen3/bin/db.sh, gen3/bin/s3.sh, gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml, gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml, gen3/test/dbTest.sh, gen3/test/s3Test.sh
Fixing "gen3 helper test suite" to support new Aurora architecture.
=> adding fixes for gen3-helper-test-suite

kube/services/argo-events/workflows/configmap.yaml, kube/services/argo-events/workflows/sensor-created.yaml, kube/services/karpenter-reconciler/karpenter-reconciler-cronjob.yaml
This change adds newer cost-tracking tags to workflow nodes. This will let us get more visibility into the types of costs we are incurring, as well as where they are occurring.
=> Let's add the new cost-tracking tags to workflows

kube/services/revproxy/helpers.js, kube/services/revproxy/nginx.conf
- Update nginx config to remove deprecated js_include (It was deprecated quite a while ago, in 0.4.0 or something)
=> Update deprecated js_include in nginx configs

Docker/awshelper/Dockerfile
update awshelper to use Ubuntu 24.04 FIPS as base image
=> Update awshelper Dockerfile

gen3/bin/kube-setup-gen3-workflow.sh
Link to JIRA ticket if there is one:  [MIDRC-945] (https://ctds-planx.atlassian.net/browse/MIDRC-945)
* Gen3 Workflow service account supports s3:DeleteBucket action
[MIDRC-945]: https://ctds-planx.atlassian.net/browse/MIDRC-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIDRC-945 Add `s3:DeleteBucket` in kube-setup-gen3-workflow

kube/services/ohdsi-webapi/ohdsi-webapi-config.yaml
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1589
- slightly increase webapi timeout to not conflict with gen3 one 
- assumes gen3 timeout is at 15 min (900 sec)
=> Feat: slightly increase webapi timeout to not conflict with gen3 one

kube/services/wts/wts-deploy.yaml
- reduce wts liveness probe to every 60s to reduce DB load
=> reduce liveness probe for wts to every 60 seconds
